### ISSUE TITLE
Fast integration tests

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#10050]
**Description**
Kyma developers should be able to deliver new features (or fix bugs) quickly. They should know if the changes will pass integration tests in a few minutes. Integration tests should be optimized:
1. Move tests that do not require full kyma installation to the lower layer in the [test pyramid](https://martinfowler.com/articles/practical-test-pyramid.html) - a good example would be cluster-users test that is the slowest in the suite and interacts only with kubernetes apiserver.
2. Minimize the number of deployments (pods) created during tests. Each deployment takes time (download image, start containers, wait for them to be ready, execute a test, terminate pod). Our testing tool (octopus) actually encourages developers to increase that number. Octopus creates a pod for each test definition (we have already 21 for integration test and 49 for upgrade test). Waiting for the test pods to be deployed is a waste of time - in this time you could already have the test executed. Consider merging multiple images and test definitions or do not use octopus at all. Octopus can be useful for stability checks on long-running clusters but in the case of integration tests running on pull request, the feedback loop should be as short as possible (every second matter).
3. Reduce the number of test fixtures. Each test creates similar test fixtures like dummy microservice (httpbin) or dummy function. The text fixture could be reused for different checks (the same function can be used to verify serverless, API gateway, event triggers, and application connector). Sharing test fixtures make tests more coupled, but the benefits are much higher than the drawbacks.

Considering the recommendations above there are 2 options to proceed:
- refactor existing tests in an iterative way by slowly reducing execution time
- start from scratch by creating 1 test fixture and create a test suite that utilizes checks defined in the existing tests (cherry-pick them) avoiding duplication of the tests (e.g. testing several times function build)

**The flow that should be tested**
- deploy SAP Commerce mock and expose it through API Gateway
- register application (SAP Commerce mock) in the default namespace,
- create function, 
- trigger function with order.created.v1
- call commerce webservices API (order details) from function
- expose function through API Gateway
- include central management plane in the flow (runtime agent) - for SKR testing in Spinnaker

Ideally, all the steps should be done as a Kubernetes deployment:
- `kubectl apply -f commerce-mock.yaml`
- `kubectl apply -f my-commerce-exetension.yaml`

The steps above can be used as a test fixture. In the test itself we need just to verify if:
- the event sent from Varkes (using varkes API) reached the function
- the function can retrieve order details from Varkes
- the function is available through API Gateway

**Acceptance criteria**
- [x] tests executed in less than 5 minutes
- [x] tests can be executed on a single node cluster with 16GB RAM and 4 CPU
- [x] each new test should not extend execution time more than a few seconds 
- [x] the flow described above is tested

**Reasons**
Integration and upgrade tests are extremely slow. 
- 30 minutes on minikube (40 min with provisioning) - only 11 tests of 21
- 40 minutes on GKE (60 min with provisioning)
There is also upgrade test that takes 75-90 minutes.

**Attachments**

There is an integration test that is testing application connector, service catalog, serverless, eventing and the execution time of such test is less than 90 seconds: https://github.com/kyma-incubator/local-kyma/runs/1457751055?check_suite_focus=true#step:6:1

**Comment by aerfio** [comment]
We've introduced k3s pipeline which installs serverless chart and runs slimmed down version of tests, you can have a look at that here: https://status.build.kyma-project.io/?job=pre-master-serverless-integration-k3s
PR which introduced that: https://github.com/kyma-project/test-infra/pull/2939

In a typical scenario this pipeline takes ~15 min, but only jobguard takes 7-8min, the rest are our integration tests. In the following sprints we'll remove as much tests from the main pipeline in kyma and put it in that k3s one.

Unfortunately we do not meet your acceptance criteria (we're above 5min with our tests 😛 ), but function build takes a lot of time

**Comment by tobiscr** [comment]
An approach how SKR end2end tests could be implemented in Spinnaker in [this document](https://github.tools.sap/huskies/Knowledge-docs/blob/skr-end2end-test/skr-test-setup/skr-e2etest-tecspec.md).

**Comment by pbochynski** [comment]
The integration tests are executed in about 3 minutes. See: https://status.build.kyma-project.io/job-history/kyma-prow-logs/logs/kyma-integration-k3s
