### ISSUE TITLE
Configure any containerised application from the Console UI

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#10088]
**Description**

Provide a UI for micro services ( equivalent to functions UI ) that will allow users to see configuration of a containerised application:
 - source docker container
 - replication and scaling configuration
 - bound service instances
 - accessible API ( API rules )
 - event subscriptions 

We could reuse a lot from functions UI. 

When creating a new micro-service the user should provide the:
 - link to the publicly pull-able docker container

On the details view user should be able to:
 - define ENVS (static and from secrets)
 - define API rules ( as in function UI )
 - define triggers ( as in function UI )  
 - define service instance bindings ( as in function UI )
 - define limit and requested values for computation resources
 - define number of replicas ( or even replication rules for HPA )

**AC**
 - [ ] user has a dedicated view under development category to manage microservice and its configuration
 - [ ] Update [deploy-a-microservice](https://kyma-project.io/docs/master/root/getting-started/#getting-started-deploy-a-microservice)
 - [ ] Use the new [experimental console backend](https://github.com/kyma-incubator/pamela/pull/1)

**Reasons**

People who evaluate Kyma may have the wrong impression that it is just for running functions. There is no sign in the UI telling first-time users that they can run any containerised applications, bind services to them and subscribe them to events.
We have it documented [deploy-a-microservice](https://kyma-project.io/docs/master/root/getting-started/#getting-started-deploy-a-microservice). Note that this flow makes the user jump from multiple views. It makes it hard to comprehend

**Comment by valentinvieriu** [comment]
I would like to add some recommendations regarding taxonomy for the acceptance criteria:

- [ ] We should use the terminology used by Kubernetes, and align as much as possible with Kubernetes
- [ ] We should not introduce a new Custom Resource as we did with Functions
- [ ] We should align the functions creations with the container creation workflow

**Comment by kwiatekus** [comment]
Whenever any deployment is deployed to  kyma, in the console UI, the deployment shows as “Error”. After when pod is up and running, it shows up “Running”.
We should try to improve it - show up a transitive `deploying` state.

**Comment by kwiatekus** [comment]
First step : allow to declare a dockerised workload from console UI : https://github.com/kyma-project/kyma/issues/10211
