### ISSUE TITLE
Implement a /publish endpoint for NATS as a messaging backend 

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/kyma#10098]
**Description**

Support sending cloudevents to NATS as a messaging backend using the NATS publishing proxy.

**Ideas**

- Try the cloudevents builtin support by [NATS](https://github.com/cloudevents/sdk-go/tree/master/protocol/nats/v2).

**Task list**

- [ ] Come up with a naming convention for NATS subjects which maps to Kyma subscriptions.
- [ ] Accept/validate cloudevents from the /publish endpoint.
- [ ] Persist cloudevents into NATS.
- [ ] Use embedded NATS in the tests.
