### ISSUE TITLE
Reconcile a NATS subscription

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#10104]
**Description**
Eventing Controller should reconcile NATS subscriptions

** Task List **
- [ ] Create NATS subscription
- [ ] Update NATS subscription
- [ ] Delete NATS subscription

Hint: use the embedded NATS and the NATS management API in the unit tests
