### ISSUE TITLE
Validate the interface that is provided by KEB for us 

### ISSUE THREAD

**Issue by berkanercan** [kyma-project/kyma#10106]
**Task List**
- [ ] Create steps for provisioning BEB, first a "read-only" step and after that the complete steps.
- [ ] We need to log everything about service offering of the enterprise messaging service.
- [ ] Implement the logic to fail the provisioning, if there is no EMS available.
