### ISSUE TITLE
Implement new eventing solution for OSS

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#10148]
**Description**

The current implementation of eventing in kyma is based on knative-eventing. A new solution will be implemented based on the a subscription mechanism inspired by the cloudevents-subscription spec.

Goals:
 - [x] run in cluster nats server
 - [x] send events to nats server
 - [x] subscribe to events on the nats server and have events delivered using http-POST to the workload
 - [ ] support creating subscriptions using `kyma-cli`
 - [x] support creating subscriptions using the kyma ui
