### ISSUE TITLE
Rollout of new installation

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#10812]
**Description**
Rollout the new installer coming out of https://github.com/kyma-project/kyma/issues/10297

  - [x] Cutover
      - [x] deprecate installer and old install command,  minikube command, console command, PR: https://github.com/kyma-project/cli/pull/951
      - [x] remove alpha from new commands. PR:  https://github.com/kyma-project/cli/pull/955
  - [x] rename alpha command in all pipelines. PR: https://github.com/kyma-project/test-infra/pull/3988
  - [x] documentation updates
      - [x] CLI: update docs to cover edge cases when using K3s (https://github.com/kyma-project/cli/issues/680)
      - [x] Kyma documentation changes (https://github.com/kyma-project/kyma/issues/10355)

**Reasons**

**Attachments**

**Comment by rakesh-garimella** [comment]
The documentation updates have alerady been resolved.

**Comment by a-thaler** [comment]
Alpha command got removed and new command is rolled out
