### ISSUE TITLE
Refresh Kyma documentation to match current state and the roadmap

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#10857]
**Description**

The target structure of the documentation:
- Overview 
   - value proposition
   - architecture
- Main concepts (areas) with purpose and high-level architecture
  - serverless
  - eventing
  - service consumption
  - application connectivity
  - API exposure
- Tasks:
  - deploy function
  - deploy microservice
  - send event
  - trigger workload with event
  - ...
  - to be defined

### ToDo

- [x] Review the existing content on the website [#10876](https://github.com/kyma-project/kyma/issues/10876) @pbochynski 
- [x] Come up with and implement the new doc structure (content) @klaudiagrz @NHingerl 
- [x] Implement the new docs structure (website) [#681](https://github.com/kyma-project/website/issues/681) @kwiatekus 
- [x] (Re)move or adjust the existing content:
    - ~Remove Rafter docs from the website~ [#10927](https://github.com/kyma-project/kyma/issues/10927) @kazydek 
    - ~Remove Helm Broker docs from the website~ [#10928](https://github.com/kyma-project/kyma/issues/10928) @klaudiagrz ✅ 
    - ~Remove Control Plane from the website~ [control-plane#676](https://github.com/kyma-project/control-plane/issues/676) @klaudiagrz 
    - Remove `minikube`
    - ~Adjust Serverless docs~ @kazydek ✅ [#11163](https://github.com/kyma-project/kyma/issues/11163) 
    - ~Adjust Eventing docs~ @alexandra-simeonova ✅ [#11200](https://github.com/kyma-project/kyma/issues/11200)
    - ~Adjust Observability docs~ @NHingerl [#11228](https://github.com/kyma-project/kyma/issues/11228)
    - ~Adjust old Service Management docs~ @klaudiagrz 
    - ~Adjust old Application Connector docs~ @majakurcius ✅ [#11622](https://github.com/kyma-project/kyma/issues/11622)
    - ~Adjust Security docs~ @mmitoraj ✅ 
    - ~Adjust Service Mesh docs~ @mmitoraj ✅ 
    - ~Adjust API exposure docs~ @mmitoraj ✅ 
    - ~Adjust Kyma general docs~
- [x] Update the content to meet Kyma 2.0 vision (Kyma 2.0 phase 2)  - the content is updated for Kyma 2.0, the rest of Service Management and Application Connector content will be updated after Service Catalog migration (2.X)
    - ~Write Get Started Guides [#10470](https://github.com/kyma-project/kyma/issues/11470)~ @majakurcius 
    - Describe Application Connectivity 2.0 [#11047](https://github.com/kyma-project/kyma/issues/11047) @majakurcius 
    - Describe Service Management 2.0 [#11290](https://github.com/kyma-project/kyma/issues/11290) @klaudiagrz 
- [x] Provide the content for the new landing page
- [x] Update the content strategy, templates, and other related community docs [community#543](https://github.com/kyma-project/community/issues/543)
- [x] Re-think our approach to diagrams to make them more visible against the white background, and update the related guidelines [community#542](https://github.com/kyma-project/community/issues/542) @klaudiagrz 

**Area**

area/documentation

**Reasons**

Kyma evolved from an extensibility platform to an application runtime over the last few years. It should be reflected in the documentation. 
Documentation should serve Kyma users - the developers who build their application on top of Kyma. It should contain list of the solutions for the common problems. The place for low-level documentation for kyma contributors is in the GitHub source code and related readme files.

**Assignees**

@kyma-project/technical-writers

**Comment by kwiatekus** [comment]
One of the Task oriented document is tracked here : https://github.com/kyma-project/kyma/issues/10845

**Comment by majakurcius** [comment]
@kyma-project/technical-writers:
- [ ] We also need to update the [MILV file with the list of ignored files](https://github.com/kyma-project/kyma/blob/release-2.0/milv.config.yaml) to match the paths to documents in the 2.0 documentation.

**Comment by klaudiagrz** [comment]
The [website](https://kyma-project.io/) and the docs have already been restructured. We will continue to provide further improvements and add more K2.0 content, but the goal of this issue is already achieved 🙂
