### ISSUE TITLE
Enable users to scale a function based on a custom metric 

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#11225]
**Description**

As a user I want more flexibility when defining scaling rules per function.
I want to define min and max replicas as well as metrics and target utilisation levels 
 - CPU & memory Utilisation ( standard on kubernetes metric server )
 - any custom metric ( for example: incomming  request rate scraped from istio ( provided that KEDA is included in kyma ))

**AC**
 - [x] There is no hard dependency between serverless and KEDA; Users can still opt not to use KEDA and use the built-in HPA based scaling
 - [x] As a user I want  guidance docu ( recipe ) showing me how to scale my workloads with KEDA (tutorial showing how to scale based on incoming request rate with scale to 0)
 - [x] serverless Function must become an entity scalable by any scaler, i.e KEDA (support for scale subresource) 
 - [x] If KEDA is installed users can define define a scaler manifest ( yaml ) that is targeting my function 
 - [x] Scale to 0 should be supported

**Execution**
 - [x] https://github.com/kyma-project/kyma/issues/12838
 - [x] [Change default HPA scaling configuration](https://github.com/kyma-project/kyma/pull/14976)
 - [x] [Make functions scalable by external scalers](https://github.com/kyma-project/kyma/pull/14704)
 - [x] [Document how to scale based on prometheus metrics](https://github.com/kyma-project/kyma/pull/15305)
 

**Reasons**

Currently we allow to setup scaling based on CPU utilisation only (**APP_FUNCTION_TARGET_CPU_UTILIZATION_PERCENTAGE**).
It is not flexible enough. Scaling strategies may vary depending of the workload use case therefore various scaling strategies should be allowed ( i.e event-driven by request rate )

Additionally, the 50% CPU threshold for HPA autoscaling does not do exactly what we anticipate it should do. The presence of istio side car caontainer( with high demand on cpu on its own ) makes this strategy unreliable as HPA controller sees the cpu consumption on the pod level.

---
<details>
    <summary>:warning: Funnel process - do not remove!</summary>
    </br>

Name|Value
:--- | :---
theme | Enterprise-grade
business value | 5
technical value | 2
user value | 5
open-source value | 10
effort | 
requested by | 
</details>

**Comment by kwiatekus** [comment]
We thought originally that we should [introduce prometheus adapter](https://github.com/kyma-project/kyma/issues/9056) as a managed component in kyma, but it might be idle in case somebody if fine with just the standard CPU and memory utilisation targets. 

Instead, we would like to enable users to define scaling rules based on built-in or ANY custom metrics that is available in the runtime. We would like to show how custom metrics could be enabled but we refrain from enabling them for all as there are no golden metrics suitable for all and they really depend on the use case.

**Comment by kwiatekus** [comment]
Next steps: #15290
