### ISSUE TITLE
Configurable logging

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#11236]
**Description**

The current logging setup is only configurable via installation overrides and restricts the user of changing the configuration dynamically at runtime without triggering the kyma upgrade procedure. Furthermore it is tightly coupled/packaged with the Loki integration and is dependent on istio as a service mesh.

Goal is to decouple the log collection and shipment layer from the actual logging backend and UI. The kyma core should not even bring any backend but simply enabled the user to collect and ship logs via a simple configuration change at runtime. There should be no dependency to istio to still ship logs if there are disruptions with the service-mesh itself. There should be an optional in-cluster backend and UI deployable by the user.

![logging](https://user-images.githubusercontent.com/7479371/149982740-e2a60066-8826-4b9a-b52b-20be2860a825.png)

Preparation:
- [x] Investigate on how to configure fluent-bit at runtime without being dependend on the kyma lifecycle (https://github.com/kyma-project/kyma/issues/11105)
- [x] Come up with a technical concept: https://github.com/kyma-project/community/tree/main/concepts/observability-configurable-logging

Actions:
- [X] New documentation structure overall (https://github.com/kyma-project/kyma/issues/11228)
- [X] Basic Operator in place with helm chart
  - [x] #11663
  - [x] #11823
  - [X] #11945
  - [x] #11831
  - [x] #13213
  - [x] https://github.com/kyma-project/kyma/issues/13831
  - [x] #13146
  - [x] #14141
  - [x] #14309
  - [x] #14141
- [x] Minimal scope for managed fluent-bit without supported scenarios (Beta scope, aligned with https://github.com/kyma-project/community/pull/675/files)
    - [x] https://github.com/kyma-project/kyma/issues/14554
    - [x] https://github.com/kyma-project/kyma/issues/14555
    - [x] https://github.com/kyma-project/kyma/issues/14556
    - [x] https://github.com/kyma-project/kyma/issues/14558
    - [x] https://github.com/kyma-project/kyma/issues/14559
    - [x] https://github.com/kyma-project/kyma/issues/14459
- [x] Minimal scope for supported OpenSearch-HTTP scenario (Final scope, aligned with https://github.com/kyma-project/community/pull/675/files)
    - [x] https://github.com/kyma-project/kyma/issues/14557
    - [x] https://github.com/kyma-project/kyma/issues/14560
    - [x] https://github.com/kyma-project/kyma/issues/14562
    - [x] https://github.com/kyma-project/kyma/issues/14564
    - [x] https://github.com/kyma-project/kyma/issues/14565
    - [x] https://github.com/kyma-project/kyma/issues/13961
    - [x] https://github.com/kyma-project/kyma/issues/14310
- [x] #12029
- [x] #13141
- [x] Performance
  - [x] #13144
  - [x] https://github.com/kyma-project/kyma/issues/14243
  - [x] https://github.com/kyma-project/kyma/issues/13833
- [x] Threat Modelling
         

Topics which are not required for a first initial scope are covered in https://github.com/kyma-project/kyma/issues/13142

---
<details>
    <summary>:warning: Funnel process - do not remove!</summary>
    </br>

Name|Value
:--- | :---
theme | Modularization
business value | 10
technical value | 10
user value | 10
open-source value | 10
effort | 
requested by | 
</details>

**Comment by a-thaler** [comment]
@gowrisankar22 we are heading towards a first beta release maybe already with Kyma 2.3. We are still in performance analysis having some findings which require to adjust the concept

**Comment by a-thaler** [comment]
The documentation is making good progress as well. If you are interested in a pre-read, look here: https://deploy-preview-14063--kyma-project-docs-preview.netlify.app/docs/kyma/preview/01-overview/main-areas/observability/obsv-04-telemetry-in-kyma/ That is not covering the discussed API additions of above comment

**Comment by a-thaler** [comment]
Based on the new proposal we re-vamped the backlog. It might look impressive from the amount of tasks. Indeed the tasks are all well-defined with not much uncertainty left so that they can be implemented with a faster progress. We see so much value in the adjusted API that we want to include it before the release.

**Comment by a-thaler** [comment]
MVP is done and will bundled with 2.6
