### ISSUE TITLE
Configurable tracing based on open standards

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#11231]
**Description**
The current tracing solution is a simple in-cluster solution to get started quickly and get some insights in a fast way. It does not respect enough high availability aspects and changing load requirements. Furthermore it is not flexible on client instrumentation side as well does not support to integrate other backend systems.

We should evolve that domain by introducing a proper layer in-between for supporting flexibility on client and backend side with the goal of not deciding and operating the technology of choice inside the cluster as part of the kyma installation. Furthermore open standards should be used as much as possible for flexible integration, mainly on the in-band trace data submission but also on the trace propagation band.

The concept should harmonize with the solution coming out of https://github.com/kyma-project/kyma/issues/11236

Concept:
- Introduce a separate layer for collecting and shipping trace data. That could be realised by the vendor-neutral [OpenTelemetry-Collector](https://github.com/open-telemetry/opentelemetry-collector) supporting multiple receiver and exporters.
- Turn the in-cluster trace backend into an optional pre-integrated component.
- Switch the default trace propagation protocol to [w3c-tracecontext](https://www.w3.org/TR/trace-context/) as it is the most open and aligned standard nowadays and supported by a lot of tools in the CNCF
- Support a dynamic configuration of the OTEL-collector with a dynamic reload, so that configuration can be done convenient at runtime and not at install/upgrade time

![tracing-future](https://user-images.githubusercontent.com/7479371/191002255-3a9bff59-ab0c-4eea-a178-78af88535304.png)

- [x] Preparations:
  - [X] Investigate consequences of switching X-B3 protocol to w3c-tracecontext, can a conversation of B3 supported somewhere in the request flow? https://github.com/kyma-project/community/blob/main/concepts/observability-strategy/configurable-tracing/03-tracing-pocs.md
  - [X] Investigate if OTEL collector is mature enough for tracing aspects and come up with a deployment model (https://github.com/kyma-project/kyma/issues/10119)
  - [x] Extend the concept to cover traces:  https://github.com/kyma-project/community/blob/main/concepts/observability-strategy/configurable-tracing/README.md
  - [x] Configurable logging is available: https://github.com/kyma-project/kyma/issues/11236
  - [x] Investigate if there is a even more lightweight Jaeger setup as alternative (skipped, as it will be transformed to a blueprint there is no need to find a replacement)
  - [X] Investigate how trace propagation can be done easy in a function (javascript/python) (already supported, however, needs to be adapted to OTLP
  - [x] Investigate on the istio sampling rate, how can it be controlled in a centralized way (https://github.com/kyma-project/community/blob/main/concepts/observability-strategy/configurable-tracing/03-tracing-pocs.md)
- [x] Core Feature:
  - [x] Build a custom Otel Collector image with minmal plugins only: a receiver for Istio traces and tail-based sampling processor (https://github.com/kyma-project/kyma/issues/15830)
  - [x] If a pipeline is defined, the Telemetry Operator deploys Otel Collector (https://github.com/kyma-project/kyma/issues/15708)
  - [x] When the last pipeline is deleted, the Telemetry Operator removes the Deployment (https://github.com/kyma-project/kyma/issues/15708)
  - [x] Define basic settings for the Otel Collector Deployment (batch, memoryLimiter, resourceLimits) (https://github.com/kyma-project/kyma/issues/15837)
  - [x] Configure Otel Collector with tracePipeline settings (https://github.com/kyma-project/kyma/issues/15831)
  - [x] Limit the setup to a singular pipeline only. To keep it simple, there can be only 0 or 1 pipeline. Using a status can be fine for now (so the second pipeline is not getting refused but is erroneous)https://github.com/kyma-project/kyma/issues/15836
  - [x] Status support (https://github.com/kyma-project/kyma/issues/16201)
  - [x] Proper limits in place (documented and built-in) so that the collector never crashes but starts refusing input (https://github.com/kyma-project/kyma/issues/15837)
  - [x] Expose relevant Otel Collector metrics for troubleshooting (https://github.com/kyma-project/kyma/issues/15708)
  - [x] Support OTLP output in GRPC and HTTP (https://github.com/kyma-project/kyma/issues/15708)
  - [x] Support Secret rotation (https://github.com/kyma-project/kyma/issues/15832)
  - [x] Support basicAuth support (https://github.com/kyma-project/kyma/issues/15829)
  - [x] The telemetry components are used to observe the service-mesh and with that should not run inside, so it has no dependency to istio not anything is exposed. (https://github.com/kyma-project/kyma/issues/15708)
  - [x] Understand what a client must provide in regards to source attributes and what can be added when missing by processors like the k8s-attributes-processor: https://github.com/kyma-project/kyma/issues/16300
  - [x] Hardening of the settings: https://github.com/kyma-project/kyma/issues/16198
  - [x] Finalized API: https://github.com/kyma-project/kyma/issues/16345
- [x] Surroundings
  - [x] Enable new feature by default: https://github.com/kyma-project/kyma/issues/16299
  - [X] New documentation structure overall (https://github.com/kyma-project/kyma/issues/11228)
  - [x] Document new architecture and have technical reference in place (https://github.com/kyma-project/kyma/pull/16336)
  - [x] Have a sample app based on otel sdk used for testing and demonstration and tutorial
    - tutorial with OTEL demo app: https://github.com/kyma-project/examples/tree/main/trace-demo
  - [x] Switch propagation protocol in istio (https://github.com/kyma-project/kyma/issues/11638)
  - [X] Support propagation in eventing (https://github.com/kyma-project/kyma/issues/10957)
  - [X] Support trace propagation in functions and provide guides (https://github.com/kyma-project/kyma/issues/11327)
  - [x] Switch serverless to OTLP protocol (https://github.com/kyma-project/kyma/issues/15569)

Attachments:
- Concept - https://github.com/kyma-project/community/blob/main/concepts/observability-strategy/configurable-tracing/README.md

---
<details>
    <summary>:warning: Funnel process - do not remove!</summary>
    </br>

Name|Value
:--- | :---
theme | Modularization
business value | 10
technical value | 10
user value | 10
open-source value | 10
effort | 
requested by | 
</details>

**Comment by a-thaler** [comment]
Release of first open source version is planned for 2.10

**Comment by rakesh-garimella** [comment]
Closing the Epic as all the Stories have been implemented.
