### ISSUE TITLE
Modify local installation to use kyma-installer

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#1146]
Local installation script should build kyma-installer from sources based on current installer image.

To do:
- [x] adapt local installation based on released installer -> @strekm -> PR #1182
- [x] adapt local installation based on released installer (windows scripts) -> @crabtree -> PR #1351
- [x] adapt installation based on installer build locally -> @jakkab -> PR #1202
- [x] create generic script that concatenates provided yaml files. AC: The script returns pretty-printed combo yaml to stdout-> @jakkab -> PR #1249 

- [x] document local development (explain how kyma-installer works, how scripts work and so on) -> @strekm 
- [x] switch local installation to use local combo yaml -> @jakkab -> PR #1285 
- [x] fix cluster installation to use installer (bug introduced by changing installer.yaml deployment to use kyma-installer) -> @crabtree -> PR #1215

**Comment by strekm** [comment]
in context of local development release of kyma-installer is not needed. local kyma-installer is being built on the fly. We should mention in documentation that local installation is installation under the development.
