### ISSUE TITLE
Api-gateway based on gloo edge [PoC]

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#11732]
**Description**

Validate the possibility to use [Gloo Edge](https://www.solo.io/products/gloo-edge/) as an API gateway for Kyma.

AC:
- [ ] manual how to install gloo edge in Kyma cluster
- [ ] manual how to expose microservice or function using gloo edge with custom domain
- [ ] comparison table with api-gateway features and gloo edge alternatives (e.g. JWT token validation, OAuth 2.0 scopes validation, mutators, etc.)

**Reasons**

The actual solution is based on api-gateway controller creating istio & ory resources. this solution proves to be error-prone and limiting the implementation of customer's use-cases. Having a lightweight envoy-based api-gateway will bring the needed flexibility for exposing workloads. 

**Attachments**

https://www.solo.io/products/gloo-edge/

---
<details>
    <summary>:warning: Funnel process - do not remove!</summary>
    </br>

Name|Value
:--- | :---
theme | Enterprise-grade
business value | 9
technical value | 9
user value | 8
open-source value | 5
effort | 
requested by | 
</details>

**Comment by strekm** [comment]
unfortunately, i need to push this to he future milestone since we are busy with other prios

**Comment by loewenstein** [comment]
@pbochynski is it still planned to replace Istio Gateway with the solo.io edge gateway? Will that be transparent for the use of the `APIRule` resource?

**Comment by loewenstein** [comment]
@pbochynski so the APIRule controller will generate Istio CRs? Is there a comparison available between solo and Istio, some guidelines for why choosing which over the other?

**Comment by strekm** [comment]
Based on research of gloo edge and POC of Istio external auth we decided to drop gloo edge in favor of istio based solution. i'm closing this one in favour of https://github.com/kyma-project/kyma/issues/12669
