### ISSUE TITLE
Multiple domains

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#11839]
**Description**

Kyma users should have the possibility to expose their workload under their domain not only kyma sub-domain. This should be implemented using gardener [cert-management](https://github.com/gardener/cert-management) and [dns-management](https://github.com/gardener/external-dns-management). 

AC:
- [ ] [shoot specification for managed kyma offering should be updated with necessary extensions](https://github.com/kyma-project/control-plane/issues/875)
- [ ] [step by step tutorial with yaml examples of resources to apply](https://github.com/kyma-project/kyma/issues/11828)
- [ ] troubleshooting guide
- [ ] Busola wizard for exposing workload
- [ ] extension added to all existing managed offerings clusters

**Reasons**

Using gardener cert-management & dns-managements allows kyma users to expose their workloads under given domain in managed and secured way.  

**Attachments**

https://github.com/kyma-project/kyma/issues/5578

**Comment by strekm** [comment]
TODO:
 - review allowList & blockList in api-gateway to eliminate the need of changing configuration of api-gateway
 
 3. Add `httpbin.workload.kyma-goat.ga` to the end of api-gateway domain whitelist parameter: `--domain-whitelist=`. Use a comma as a separator.
   ```bash
   kubectl edit deployment -n kyma-system api-gateway
   ```
