### ISSUE TITLE
Istio as an optional component

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#11840]
**Description**

It should be possible to install Kyma components without istio when it is not essential for the component functionality. For other cases (like api-gateway) istio installation should not be a prerequisite. It should be possible to install first only istio custom resource definitions as a first step.
Istio introduces

Acceptance criteria:
- [ ] istio CRDs are applied with other Kyma CRDs in the prerequisites step
- [ ] istio becomes regular component on the list (installed in parallel to other components)
- [x] [istio sidecar injection is disabled by default](https://github.com/kyma-project/kyma/issues/11637) - opt-in instead of opt-out
- [ ] [kyma controllers do not use istio for kubernetes API server calls](https://github.com/kyma-project/kyma/issues/11731)

**Reasons**

Istio is now a prerequisite for installing other Kyma components. For some components like api-gateway which build on top istio ingress gateway it is justified, but many others could be installed and work properly without istio. Kyma transforms into more lightweight and modular solution. Istio dependencies can be refactored in the way that istio itself can be installed in parallel to other components or not installed at all.

---
<details>
    <summary>:warning: Funnel process - do not remove!</summary>
    </br>

Name|Value
:--- | :---
theme | Modularization
business value | 6
technical value | 10
user value | 2
open-source value | 5
effort | 
requested by | 
</details>

**Comment by pbochynski** [comment]
With the modularization of Kyma the issue is automatically resolved. Istio becomes a module and istio CRDs are installed only as a part of istio module installation. All other modules that depend on istio should check only the existence of required APIs and report warnings if the dependency is missing. The istio API can be provided by the Kyma Istio module but can also be satisfied by another istio installation.
