### ISSUE TITLE
Jetstream Backend Implementation

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#12388]
## Description

Implement a new eventing backend based on NATS-Jetstream. 
The current NATS based backend provides different delivery guarantees compared to other Backends. With Jetstream we will be able to provide similar at-least-once guarantees.

## Acceptance:

- [x] #12389
- [x] #12390
- [x] #12391
  - Currently there is no need to configure storage, max size etc individually per subject. This allows us to use one stream for the entire backend.
  - This approach also allows us to setup the stream immediately when the backend is started
- [x] works with the existing Subscription CRD
- [x] push-based consumer
- [x] configurable max-in-flight (mapped to MaxAckPending)
- [ ] ~~#13697~~ 
- [x] #13736
- [x] event delivery policy: use jetstream default for now
- [x] e2e test exists (fast integration)
- [x] #14013

## Implementation
- [x] #13223
- [x] #13224
- [ ] ~~implement selecting the new controller / dispatcher / EPP using the Eventing Backend~~

---
<details>
    <summary>:warning: Funnel process - do not remove!</summary>
    </br>

Name|Value
:--- | :---
theme | Enterprise-grade
business value | 8
technical value | 8
user value | 8
open-source value | 8
effort | 
requested by | 
</details>

**Comment by mfaizanse** [comment]
More issues:
- https://github.com/kyma-project/kyma/issues/13544
- https://github.com/kyma-project/kyma/issues/13546

**Comment by mfaizanse** [comment]
- https://github.com/kyma-project/kyma/issues/14475

**Comment by k15r** [comment]
Jetstream is now the default backend. Closing as completed

**Comment by robinnarsinghranabhat** [comment]
@k15r  I cannot find any way to use WorkQueuePolicy for my retention. 
I have multiple worker servers and I only want the available to process the message. 

Also, I couldn't find any documentation on using pull-consumer rather than push-consumer approach.
