### ISSUE TITLE
Istio 1.12.x bump

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#12668]
**Description**

Upgrade Istio to 1.12.x. Changes needs to be done only for main branch. 

AC:

- [x] [new image available in Kyma external repository](https://github.com/kyma-project/test-infra/issues/4487)
- [x] [istio component chart updated to version 1.12.x](https://github.com/kyma-project/kyma/issues/12675)
- [x] [security scans green for main branch](https://github.com/kyma-project/kyma/issues/13532)
- [x] [release notes for 2.1](https://github.com/kyma-project/kyma/issues/13531)
- [x] [run manual tests [M]](https://github.com/kyma-project/kyma/issues/13530)
- [x] [istio reconciler uses istioctl 1.12.x to install istio 1.12.x](https://github.com/kyma-incubator/reconciler/issues/456)
- [x] [verify grafana dashboards (check if an update is recommended)](https://github.com/kyma-project/kyma/issues/13581)
- [x] verify kiali features
- [x] verify trace propagation and trace data transport to jaeger
- [x] notify monitoring team to verify that metric cardinality has not increased (Envoy metrics)
- [x] bump istioctl in reconciler pipelines
- [x] [gardener cluster can be hibernated](https://github.com/kyma-project/kyma/issues/13617)

**Reasons**

For security & support reasons we should be up to date with the latest Istio release.

Attachments

https://istio.io/latest/news/releases/1.12.x/announcing-1.12/

**Comment by strekm** [comment]
unfortunately at this moment we are not able to bump because of opened issues:
- https://github.com/istio/istio/issues/36261
- https://github.com/istio/istio/issues/36258
Investigated workaround is too risky option on production in my opinion. 
Bump is on hold.

**Comment by loewenstein** [comment]
What's the plan now for when we'll get Istio 1.12 in Kyma?

**Comment by strekm** [comment]
@loewenstein unfortunately we decided we can't deliver istio 1.12 shape just yet. Once istio will provide fixes we will re-evaluate it. 
Stay tuned
Magda
