### ISSUE TITLE
[MVP] Secure workload with oidc token using Istio

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#12669]
**Description**

Provide manual set of steps to secure application with oidc  (e.g. IAS) token. Implement first version of Istio oauth2 external authorizer which is validating IAS token. Research already implemented solutions out there (e.g. oauth2-proxy). Provided solution should be tested with performance and functional tests. 

AC:
- [x] [tutorial on how to secure application with JWT](https://github.com/kyma-project/kyma/issues/13556)
- [ ] technical design for proposed solution
- [ ] proposal for migration procedure in api-gateway
- [ ] proposal for automatization basing on provided tutorial (minimazing effort on user side)
- [x] [performance tests comparison with ORY oathkeeper](https://github.com/kyma-project/api-gateway/issues/83)
- [ ] thread modeling 

**Reasons**

ORY stack proves to have performance issues. Existing implementation of api-gateway seems to be problematic making enhancements hard to introduce forcing our users to use istio directly. 

**Attachments**

https://istio.io/latest/docs/tasks/security/authorization/authz-custom/

**Comment by TorstenD-SAP** [comment]
Minutes of the meeting with responsible experts from SGS (Maik Müller, Petra Barzin) regarding compliance with the Product Security Standard (in particular [SEC-276](https://wiki.wdf.sap.corp/wiki/display/PSSEC/SEC-276), [SEC-230](https://wiki.wdf.sap.corp/wiki/display/PSSEC/SEC-230), [SEC-231](https://wiki.wdf.sap.corp/wiki/display/PSSEC/SEC-231), [SEC-232](https://wiki.wdf.sap.corp/wiki/display/PSSEC/SEC-232) and [SEC-374](https://wiki.wdf.sap.corp/wiki/display/PSSEC/SEC-374):
Both experts stated, that we are compliant with the mentioned standards. The authentication related requirements are fulfilled by outsourcing the authentication to an external IdP (most requirements must be fulfilled by the IdP but this is outside of our scope and responsibility) and using the issued tokens for authorizing the communication with the API Gateway. The requirement to use mTLS (SEC-374) is/can be fulfilled by using Istio. The only open question left was how we plan to authorize requests from the API gateway to the respective microservice.

For an easy and convenient way to use our solution and fulfill compliance with standards for our customers I recommend to provide an out-of-the box solution with Istio and IAS or at least provide well documented best practices for this.

**Comment by TorstenD-SAP** [comment]
I've documented the results of the discussions with the SGS colleagues and the contact persons for SAP IAS in this [Github issue](https://github.wdf.sap.corp/ce-security-circle/kyma-security/issues/61)

**Comment by pbochynski** [comment]
> I've documented the results of the discussions with the SGS colleagues and the contact persons for SAP IAS in this [Github issue](https://github.wdf.sap.corp/ce-security-circle/kyma-security/issues/61)

The link is not available even for me. Please don't link internal SAP issues in the open source project. I believe you can extract public information and paste it here.

**Comment by strekm** [comment]
Using Istio external auth is not needed in this approach. Scenario can me implemented with [Istio authorization policy](https://istio.io/latest/docs/reference/config/security/authorization-policy/) and [Istio request authentication](https://istio.io/latest/docs/reference/config/security/request_authentication/)

**Comment by pbochynski** [comment]
Q3 is over. Please update the timeline.

**Comment by strekm** [comment]
closing since scope of this task is moved to: https://github.com/kyma-project/api-gateway/issues/30
