### ISSUE TITLE
Serverless Benchmarking

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#12849]
**Description**

We want to gain better visibility in serverless performance and be able to detect positive/negative trends in serverless qualities.

We want to keep track of 2 different  flavours of performance (lifecycle, individual functions). 

 - [x] measure time between function creation time until pod ready (prio 1) - done [here](https://github.com/kyma-project/kyma/pull/12914)
 - [x] [individual runtimes](https://github.com/kyma-project/kyma/issues/12849#issuecomment-1019885908) (python, nodejs) - could be simple as collecting locust reports (prio 2)

**Execution plan**

 - run periodically on nightly:
   - deploy test fixtures (individual functions, function orchestrated in a chain) & apply load - run test suites jobs
 - collect average metrics after each test run
   -  using kyma observability tools and optionally locust reports
 - store resulting data to google cloud big query:
   - time to start and become ready
   - response time
   - requests per second vs response per second
   - error rate (200 vs 500)
 - plot the data on dashboards ( re-use grafana setup from test-infra )
 - alert that will inform us that performance is trending down (?) 

**AC**

 - runtime performance test should be independant on the runtime itself so that we get the same set of data for various types of runtimes and be able to compare them

**Reasons**

We want to measure if serverless refactoring is improving performance or causing performance losses

**Attachments**

**Related Issues**
https://github.com/kyma-project/kyma/issues/10154

---
<details>
    <summary>:warning: Funnel process - do not remove!</summary>
    </br>

Name|Value
:--- | :---
theme | Technical Debt
business value | 5
technical value | 8
user value | 2
open-source value | 5
effort | 
requested by | 
</details>

**Comment by kwiatekus** [comment]
We have 2 flavours of performance (lifecycle vs runtime). We probably have to separate those:

Runtime
 - individual runtimes (python, nodejs) - could be simple as collecting locust raports
 - chain of functions - focus on workflow aspect - how long from initial trigger until the finish
 
 Function controller (lifecycle)
  - measure time between function creation time until pod ready

Phases (all automated):
1) Deploy cluster (nightly)
2) Deploy Test Fixtures (functions)
3) Export Data (i.e locust raport & prometheus metrics)
4) Storing in S3 bucket

Consumption (human)
App that fetches the time records
1) present the charts

**Comment by dbadura** [comment]
Shouldn't we also gather metrics for function updates?

**Comment by kwiatekus** [comment]
Phase 2 PRs - benchmarking individual runtimes
- [ ] https://github.com/kyma-project/test-infra/pull/4790
- [ ] https://github.com/kyma-project/third-party-images/pull/167
- [ ] https://github.com/kyma-project/test-infra/pull/4736

**Comment by kwiatekus** [comment]
Phase 3 postponed 
https://github.com/kyma-project/kyma/issues/13132

**Comment by kwiatekus** [comment]
We have a fixture of all kinds of function runtimes deployed and load tested ( via locust ) every 12 hrs
Results are collected and stored in cloud big query and plotted in the grafana from sql queries

https://monitoring.build.kyma-project.io/d/CdzgqX1nz/serverless-controller?orgId=1&from=now-7d&to=now

![Screenshot 2022-02-01 at 12 48 04](https://user-images.githubusercontent.com/6783567/151963219-29e036d5-3ead-4aee-b2fd-a2b94555f039.png)

Immediate conclusions from the data:
 - python functions are not performing with a lot of concurent requests. NodeJS based one cope with that much better - we can document performance profiles of the runtimes. Users will get more confidence when designing the functions.
 - smaller python runtimes ( XS, S ) prove to be useless - [we need to adjust the allocated resource ](https://github.com/kyma-project/kyma/pull/13226)
