### ISSUE TITLE
Automated test for ory reconciliation

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#12968]
**Description**
Create an automated integration test for ory component reconciler

**Reasons**

The ory component reconciler have frequently issues like timeouts, patches can not be applied. 
Therefore an automated integration test should be setup which takle's the happy path main usecases for ory reconcilation.

**Attachments**

Issues that popped up: https://github.com/kyma-incubator/reconciler/issues/459,  https://github.com/kyma-incubator/reconciler/issues/465,  https://github.com/kyma-incubator/reconciler/issues/595 , https://github.com/kyma-project/kyma/issues/12735

**UseCases to be tested**

1. ory installation with evaluation profile on k3d
    Expected result:
    - ory pods should be running ( ory-hydra, oathkeeper, hydra-maester)
    - check that there is not hpa in place (only one pod per mentioned one)
    
2. ory installation with production profile on gardener
    Expected result:
    - ory pods should be running ( ory-hydra, oathkeeper, hydra-maester, ory-postgres)
    - check that there is hpa in place including scaled pods reflecting chart values

3. [stretch] rerun reconciler and check if pods did not get restarted

AC:
- [x] [POC integration test for ORY](https://github.com/kyma-incubator/reconciler/issues/637)
- [x] [test implemented for ORY eval profile installation](https://github.com/kyma-incubator/reconciler/issues/638)  
- [x] [test implemented for ORY prod profile installation](https://github.com/kyma-incubator/reconciler/issues/639)
- [x] [pipeline for ORY on eval implemented](https://github.com/kyma-project/test-infra/issues/4656)
- [x] [pipeline for ORY on prod implemented](https://github.com/kyma-project/test-infra/issues/4657)
