### ISSUE TITLE
Configurable metrics

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#13079]
**Description**
The current monitoring solution is a simple in-cluster solution to get started quickly and get some insights in a fast way. It does not respect enough high availability aspects, is not flexible on client instrumentation side (supporting OTLP for example) and it is not flexible for integration of other backend systems. 

We should evolve that domain by introducing a proper layer in-between for supporting flexibility on client and backend side with the goal of not deciding and operating the technology of user choice inside the cluster as part of the kyma installation. Furthermore open standards should be used as much as possible for flexible integration, mainly OTLP for data transport.

The concept should harmonize with the solution coming out of https://github.com/kyma-project/kyma/issues/11236 and https://github.com/kyma-project/kyma/issues/11231

Concept:
- Introduce a separate layer for collecting and shipping metrics data being independent on the prometheus-operator specific way of configuration. That could be realised by the vendor-neutral [OpenTelemetry-Collector](https://github.com/open-telemetry/opentelemetry-collector) supporting multiple receiver and exporters.
- Turn the in-cluster monitoring backend into an optional pre-integrated component.
- Support a dynamic configuration of the OTEL-collector with a dynamic reload, so that configuration can be done convenient at runtime and not at install/upgrade time
- Add support for scraping in prometheus format
- Add support for typical K8S metrics like kublet/node/apiserver..

![monitoring-future](https://user-images.githubusercontent.com/7479371/223171511-7759df00-6163-470a-8f81-64e603997a5e.png)

Preparations:
- [x] Extend the logging concept to cover metrics as well:  https://github.com/kyma-project/community/pull/685
- [x] Extend the logging concept to cover dynamic configuration of the otel-collector:  https://github.com/kyma-project/community/pull/685
- [x] Decouple kyma from prometheus-operator resources, use annotations instead: https://github.com/kyma-project/kyma/issues/11300
- [x] Configurable logging is available: https://github.com/kyma-project/kyma/issues/11236

Features:
- [x] Basic Metric Gateway
  - [x] If a pipeline is defined, the Telemetry Manager deploys a dedicated Otel Collector as gateway handling metrics only (https://github.com/kyma-project/kyma/issues/16996)
  - [x] Have basic processors in place like k8sattributeprocessor (https://github.com/kyma-project/kyma/issues/16996)
  - [x] When the last pipeline is deleted, the Telemetry Operator removes the Deployment (https://github.com/kyma-project/kyma/issues/16996)
  - [x] Limit the setup to a singular pipeline only (https://github.com/kyma-project/kyma/issues/16996)
  - [x] Status support (https://github.com/kyma-project/kyma/issues/16996)
  - [x] Validate resource limits/collector config by performance tests and adjust (https://github.com/kyma-project/kyma/issues/17069)
  - [x] Support OTLP output in GRPC and HTTP via the MetricPipeline API (https://github.com/kyma-project/kyma/issues/16996)
  - [x] Support Secret rotation (https://github.com/kyma-project/kyma/issues/16996)
  - [x] Support custom headers (https://github.com/kyma-project/kyma/issues/16996)
  - [x] E2E tests (https://github.com/kyma-project/telemetry-manager/issues/72)
  - [x] Support for multiple pipelines (https://github.com/kyma-project/kyma/issues/17223)
  - [x] Service name enrichment (https://github.com/kyma-project/telemetry-manager/issues/373)
  - [x] mTLS support for backends (https://github.com/kyma-project/telemetry-manager/issues/367)
  - [x] Manual scaling (https://github.com/kyma-project/telemetry-manager/issues/430)
  - [x] mTLS support for the gateway (https://github.com/kyma-project/telemetry-manager/issues/597)
- [X] Application scrape support (https://github.com/kyma-project/telemetry-manager/issues/513)
- [X] Kyma Dashboard view (https://github.com/kyma-project/telemetry-manager/pull/433)
- [x] Prepare MVP
  - [x] Finalize API by validating that description and constraints are in place
  - [x] Documentation with Architecture and usage guide (https://github.com/kyma-project/telemetry-manager/pull/362)
  - [x] Adjust otel-demo example to include metric dispatching
- [X] Finalizations
  - [x] Reflect metric agent status In metric pipeline status (https://github.com/kyma-project/telemetry-manager/issues/563)
  - [x] Add metric endpoint to module status (https://github.com/kyma-project/telemetry-manager/issues/622)
  - [x] Fix resource attributes of istio metrics (https://github.com/kyma-project/telemetry-manager/issues/606)
  - [X] Check if kube-system metrics could be ignored always (https://github.com/kyma-project/telemetry-manager/issues/607)
  - [x] Move metric resources from develop profile into release profile (https://github.com/kyma-project/telemetry-manager/issues/623)

**Reasons**

**Attachments**

---
<details>
    <summary>:warning: Funnel process - do not remove!</summary>
    </br>

Name|Value
:--- | :---
theme | Modularization
business value | 10
technical value | 10
user value | 10
open-source value | 10
effort | 
requested by | 
</details>

**Comment by a-thaler** [comment]
Started to work on a concrete concept: https://github.com/kyma-project/community/pull/685

**Comment by a-thaler** [comment]
We will first realize the minimal version of configurable tracing https://github.com/kyma-project/kyma/issues/11231 to gain more experience with the otel-collector and have a basic setup in place. The monitoring topic is much more complex and getting that experience first will accelerate the solution

**Comment by a-thaler** [comment]
Rollout to fast channel is aimed for 20.12.23

**Comment by a-thaler** [comment]
Final documentation can be found at https://kyma-project.io/#/telemetry-manager/user/04-metrics, feature will be part of release 1.6.0.
