### ISSUE TITLE
Reconciliation fix

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#13099]
## Description

Prio 1
- [ ] kyma-project/kyma#11704
- [ ] kyma-project/kyma#9766

Prio 2
- [ ] kyma-project/kyma#13059

**Comment by radufa** [comment]
The third point is fixed by PR: https://github.com/kyma-project/kyma/pull/13070

**Comment by k15r** [comment]
all tasks done
