### ISSUE TITLE
Investigate GitOps deployment for functions 

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#13125]
**Description**

Kyma serverless supports sourcing functions from git. 
The handling of git 

Currently we allow for two options:
 - sourcing only the function code from git repository. This doesn't allow to deploy function as a whole (i.e you cannot set git repo as a source of truth for function CR, api-rule configuration, event subscriptions etc ) so it is not a comprehensive deployment model.
 -  deploying functions via kyma CLI ( incl. source code - i.e `handler.js`+ `package.json` AND function configuration i.e `config.yaml` mainfest file ).  Those artefacts can only be used to deploy functions via CLI - NOT from git.
 
Kyma users are missing a git-sourced deployment model for functions.
We should  check if its possible to have a gitcontroller/operator that would allow taking both (sources and manifests) from git  and deploy them to kyma.
 
**Assumptions**

 - As a user I can configure git repo as a source of truth for my resources based from k8s manifests
 - As a user I can configure git repo as a source of truth for functions sourced from code + `config.yaml` manifest
 - As a user I can find recipes and best practices in documentation 
 - As a user I cannot configure git-sourced manifests that would reconcile kyma resources
 - As a user I can still use kyma CLI to deploy functions

**Reasons**

Kyma users need a deployment model for their kyma hosted applications (functions, microservices, configurations, secrets) that 
 - can be automated
 - is following best practices of CI/CD ( i.e test on DEV, promote to PROD )
 - can be driven from git repository changes
 - allow for deployment variants consistent with k8s programming model  ( i.e helm overrides or kustomize overlays )

**Subtasks**

 - [x] [Validate ideas for delegating git logic](https://github.com/kyma-project/kyma/issues/13206)
 - [x] [Investigate using flux to fetch git repos in function controller](https://github.com/kyma-project/kyma/issues/13072)
 - [x] [Design contract between function controller and GitController](https://github.com/kyma-project/kyma/issues/12889) (exclude git logic) 
 - [x] [Document recipes for function deployment ( any app deployment )](https://github.com/kyma-project/kyma/issues/13127)

---
<details>
    <summary>:warning: Funnel process - do not remove!</summary>
    </br>

Name|Value
:--- | :---
theme | Enterprise-grade
business value | 10
technical value | 10
user value | 8
open-source value | 10
effort | 
requested by | 
</details>

**Comment by paschdan** [comment]
I guess that the gitops operation should not be added to kyma, unless you are willing to add resources on already prod-ready gitops tools (fluxcd, argocd)

what you want is in my opinion already possible:

* create your yamls:
  * function CR
  * git repo
  * api rules

* apply those yamls via gitops tool of your choice

the only downside, when it comes to functions is the following bug:

when a git repo and a function are applied at the same time, there can be race conditions, where the function controller sets the function to false, because it does not find the referenced git repo

we worked around this problem the following way:

* we wrote a helm chart, that can deploy the gitrepo, the functioncr and api rules
* we added an helmhook after install, that annotates the function

this way the function controller reconciles the function and the git repository is now ready.


this helm chart can then deployed via argo / fluxcd ( i guess both are able to deploy helm charts)


maybe you guys could add a retry mechanism in the function reconciler when a git-repo is referenced?

**Comment by kwiatekus** [comment]
Thank you @paschdan 

You're right, the GitOps operator is not useful on all kinds of runtimes (i.e in all stages). 
As @abbi-gaurav said there are good reasons to use push based deployment.. but also there are good reasons to employ git pull based deployments of applications to kyma.
All in all we dont want to impose it and we want to have it optional ( please see linked epic [here](https://github.com/kyma-project/kyma/issues/13176#issuecomment-1021374815)

I have logged the function vs. git repository CR race condition [here](https://github.com/kyma-project/kyma/issues/13179). thank you for letting us know

**Comment by kwiatekus** [comment]
@abbi-gaurav 
With regards to your comments, we believe we can separate the serverless from gitOps capabilities and design a clear contract
https://github.com/kyma-project/kyma/issues/13072#issuecomment-1031239550

**Comment by dbadura** [comment]
> As a user I can configure git repo as a source of truth for functions sourced from code + `config.yaml` manifest

Shouldn't we treat `config.yaml` as something local and use kyma CLI to generate CRs, which can be applied by standard GitOps operator?

**Comment by kwiatekus** [comment]
We realised that it would be possible to employ a gitops operator ( flux ) to fetch git sources of functions.
However, it would impose collisions with gitops instances installed by the user.

We decided to refactor the Git-fetching logic and extract it to a separate controller.
That would give us possibilities to gain more control over the git fetching process.
This should be tracked here:
https://github.com/kyma-project/kyma/issues/13545

Moreover, we have added [documentation](https://github.com/kyma-project/kyma/issues/13127) and [example](https://github.com/kyma-project/examples/pull/196) showing the users how to deploy their functions according to k8s and devops best practices.
