### ISSUE TITLE
[Configurable Logging] Prepare release and verify upgrade procedure

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#13143]
**Description**
When https://github.com/kyma-project/kyma/issues/11236 is ready to be released, several things need to be done in order to get the new component installed by default and the old functionality disabled

**Criterias**
- [x] The new component is enabled by default by all means of installation (CLI, pure reconciler, SAP offering) (PR #15057)
- [x] Feature toggle is disabled by default -> New fluent-bit is pushing logs to loki as loki-logPipeline is active
- [x] Old fluent-bit is not pushing logs to loki anymore (disable output plugin by re-using the disabled feature flag)
- [x] Docu is not describing anymore how to enable the feature (PR #15070)
- [x] Docu is not using "alpha" anymore. The CRD stays alpha for now but the feature itself is regular
- [x] Assure that an upgrade from standard kyma 2.5 cluster works as expected
  - [x] Open Source
  - [x] SKR
- [x] Have release notes ready
- [x] Ensure to have a cleanup script to delete the logging fluent-bit DaemonSet (PR #15092)
- [x] Migration guide for OSS users (PR https://github.com/kyma-project/kyma/pull/15122)

**Comment by skhalash** [comment]
The following acceptance criterium will not be done:

* Old fluent-bit is not pushing logs to Loki anymore (disable output plugin by re-using the disabled feature flag)

In order to achieve this, we would have to replace the old fluent-bit output with null and then, in a subsequent version, disable the subchart rendering. This 2-step process seems to be too much. Anyway, the old fluent bit will push logs during a short time window after the upgrade until the cleanup script is executed, which is an acceptable tradeoff.
