### ISSUE TITLE
Eventing based on AMQP

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#13154]
## Description
Connect to AMQP based eventing backends

## Problem

With the current webhook based dispatching for external eventing backends it is required to expose the workload to the public using eg an API-Rule. An AMQP based dispatcher will allow subscribing to an external eventingbackend while still keeping the workload inaccessible from the internet.

## Acceptance Criteria
- [ ] extend the current list of supported eventing backends with an AMQP based publisher/dispatcher
- [ ] currently existing subscriptions work without modification on the new eventing backend
- [ ] fast-integration test works with the new backend
- [ ] prow jobs exist for the following scenarios: simple subscribing and dispatching, switching to and from the new backend

**Comment by mfaizanse** [comment]
Point to ponder:
- What about scaling of the dispatcher?

**Comment by mfaizanse** [comment]
- Should we use the same publisher-proxy? or update it to use AMPQ?
   - For `atleast-once delivery` we need to use AMQP while publishing.
   - Right now, we are not advertising BEB as `atleast-once delivery` supported, so using the current publisher-proxy could be fine.

**Comment by nachtmaar** [comment]
**ToDos** in order to **close** the **iteration** of the work on AMQP (not the whole EPIC):
- [ ] Document how to: 
  - create Event Mesh instance
  - getting the Event Mesh secret
  - how to convert Event Mesh Service Key to K8S secret
 - how to run/deploy the controller/EPP
- [ ] Write down follow-up ToDos in a new ticket

**Comment by nachtmaar** [comment]
The code lives [here](https://github.com/kyma-project/kyma/compare/main...nachtmaar:amqp-controller?expand=1).

**Comment by nachtmaar** [comment]
ToDos (more details in my handover notes):
- [] `Write tests` (unit and integration)
- Code:
  - [] Remove hardcoded beb-rf stuff
  - [] handle ToDoS in code
 - For local deployment
   - [] Auto generate secret from file for EMS AMQP, e.g. with kustomize
   - [] Fix runAsUser: 1000 for eventing-controller when using make deploy ?
   - [] AMQPSubscription is not installed as part of make deploy(k apply -f config/crd/bases/eventing.kyma-project.io_amqpsubscriptions.yaml)
- CRD:
  - [] Use `Kyma Subscription CRD` instead of AMQPSubscription
 - Backend switching:
   - [] Cleanup all queues/topics when switching back from AMQP to NATS/BEB

I think splitting the work by components can make the ticket parallelizable:
- Eventing Controller
- Event-Publisher-Proxy

**Comment by k15r** [comment]
Due to higher priority of the modularization this topic needs to be shifted back in the roadmap
