### ISSUE TITLE
Bump k8s-tools image version

### ISSUE THREAD

**Issue by Halamix2** [kyma-project/kyma#13200]
**Description**

- [x] bump `k8s-tools` on `release-1.24` branch - #13191
    - [x] bump dependent images - #13220
- [x] bump `k8s-tools` on `release-2.0` branch - #13192
- [x] bump `k8s-tools` on `main` branch - #13193

**Attachments**

https://github.com/kyma-project/third-party-images/pull/170
