### ISSUE TITLE
POC: Use predicates to filter out unnecessary reconciliation requests in EventMesh reconciler

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#13307]
**Current Situation:**
Right now whenever we update the status (or update subscription) in the EventMesh reconciler, it triggers another reconciliation, which is extra and unnecessary.

**Idea:**
We can use predicates to filter out unnecessary reconciliation calls. 
For example, if the ResourceGeneration is not increased (e.g. no change in Spec) then we can just check if reconciliation is needed or not. If it is not needed, then we can skip that reconciliation.

In case of EventMesh, we queue a new reconciliation every 10 minutes even though there has been no change in the Spec because we need to check if the corresponding EventMesh server subjects are healthy. This queued recociliation would not be effected by this filtering using predicates because these queued reconciliations do not pass through predicates - as verified by @raypinto [here](https://github.com/kyma-project/kyma/issues/13307#issuecomment-1048552493).

**Cons:**
As this would save us some extra reconciliations but on the other hand, using the predicate may effect some edge cases like deletion of subscription, so need to do tests all the cases before we release it for prod.

**Tasks:**
- [ ] Create Predicates to check if reconciliation is necessary
   - Check if ResourceGeneration is not increased.
   - Check if the Subscription Status, Sink Status and the APiRule status is Ready.
   - If above conditions are satisfied, do not reconcile.
- [ ] Check if the number of reconciliations are reduced [compared to these results.](https://github.com/kyma-project/kyma/issues/13026#issuecomment-1029848795)

**References**:
- https://sdk.operatorframework.io/docs/building-operators/golang/references/event-filtering/
- https://stuartleeks.com/posts/kubebuilder-event-filters-part-2-update/

**Comment by raypinto** [comment]
Tasks:
- [ ] Add lastSuccessfulReconciliationTimeStamp to Status
- [ ] Create Predicates to check if reconciliation is necessary
   - Check if ResourceGeneration is not increased
   - Check if Status is ready and if the lastSuccessfulReconciliationTimeStamp is less than 10 minutes
   - If above conditions are satisfied, do not reconcile

**Comment by k15r** [comment]
If i understood this correctly then:

**Comment by raypinto** [comment]
@k15r You're right!  We filter unnecessary reconciles by using a predicate (on the Subscription watcher) that filters based on the ResourceGeneration field. The only reason we would need `lastSuccessfulReconciliationTimeStamp` is to make sure we do not filter the mandatory 10th minute reconciliation for BEB subscriptions.

**Comment by raypinto** [comment]
You are right @k15r!  We do not need the `lastSuccessfulReconciliationTimeStamp` since the 10 min reconciliation takes place by requeuing the reconciliation - which does not go through the predicate. I've verified this and works as expected.

I've checked that adding a simple predicate reduces the reconciliation by 1, but in some cases would have to be handled with some extra logic - eg. deletion of a subscription calls the updateFunc predicate, which does nothing based on our logic of checking ResourceGeneration and hence the operation hangs)
