### ISSUE TITLE
Automated test for Istio component

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#13517]
**Description**

Implement Istio component test triggered on istio or istio-resources components changes. Test should check Istio sidecar injection Kyma specific configuration and communication inside service mesh. 

AC:
- [x] [POC - Istio component test](https://github.com/kyma-project/kyma/issues/13515)
- [x] [test implemented for Istio eval profile installation](https://github.com/kyma-project/kyma/issues/14256)  
- [x] [test implemented for Istio prod profile installation](https://github.com/kyma-project/kyma/issues/14257)
- [x] [test implemented for Istio prod profile verifying sidecar injection](https://github.com/kyma-project/kyma/issues/14258)
- [ ] [pipeline for Istio on eval implemented](https://github.com/kyma-project/test-infra/issues/5411)
- [ ] [pipeline for Istio on prod implemented](https://github.com/kyma-project/test-infra/issues/5412) 

**Reasons**

Reducing effort of manual testing on Istio bumps.

**Attachments**
