### ISSUE TITLE
MessagingBackend interface should not be imposed on different backends

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#13528]
**Description**

Currently the MessagingBackend interface is being forced on various backends that are not related and hence the handler implementations are not flexible enough. We propose to change this by implementing Backend specific interfaces (for mocking purposes during testing) and using/enhancing them as required for each backend.

**Tasks**

- [ ] Implement this for NATS backend
- [ ] Implement this for BEB backend
- [ ] Implement this for Jetstream backend
