### ISSUE TITLE
Improvements for Git Function Reconciliation

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#13545]
**Description**

Improve reconciliation loop for git functions.

**Execution**
 - [x] Phase 0 ["Split the reconciliation logic between inline and GIT"](https://github.com/kyma-project/kyma/issues/13600)

 - [x] Phase 1 ["Eliminate redundant git operations"]
 - replace git checkout.. with  fetching or caching
 - adapt git fetching logic  in function build phase 

- [x] Phase 2 [" Next performance improvements"](https://github.com/kyma-project/kyma/issues/14235)
 
 **AC**

 - git sources for functions are not excessively fetched. We have to avoid pulling the whole repo just to check if there are changes to be deployed (see #13982 )
 - it should be visible on a function level at which git reference is currently used ( which branch, tag, commit )
 - git functions should survive runtime hibernation
 - git functions should survive being migrated between worker nodes
 - functions referencing non existing git reference should be reconciled with backoff
  
**Ideas**
 - eliminate storage via "watching" git repo ( i.e git fetch for "watching" and git pull only before building ) - this might be github specific - needs investigation
 - incorporate state machine in function controller reconciliation logic

**Reason**
Cleanup in CRDs, resource optimisation for git function reconciliation
 - Function controller builds the container and deploys
 - Git controller fetches the function code and exposes function sources to the  function controller

**Comment by kwiatekus** [comment]
Follow up task: ["Git Function CRD API cleanup"](https://github.com/kyma-project/kyma/issues/13828):
