### ISSUE TITLE
Implement code/testing guidelines

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#13559]
**Description**

As a follow-up of [defining the code/test guidelines](https://github.com/kyma-project/kyma/issues/12820) we need to follow the guidelines in the code and tests.

**Acceptance Criteria**

- Code and tests are following strictly the [guidelines](https://github.com/kyma-project/community/blob/main/concepts/eventing-code-guidelines.md)

Subtasks:
- [ ] Follow GWT pattern
- [ ] Use Functional Options Pattern
- [ ] Follow naming scheme for **table-driven tests**: name/given/want

**Migration of recommended libraries**:
- [ ] #13565
    - [x] #15925
- [x] #16431
- [x] #13561
- [x] #13564
- [x] #13560

**Reasons**

Code and testing Guidelines are supposed to help us by agreeing on a common set of rules. However, they are only worth something then we also follow them. 
- For new code they are already in place.
- Old code will be migrated as part of this epic.

**Attachments**
