### ISSUE TITLE
Istio 1.13.x bump

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#13620]
**Description**

Upgrade Istio to 1.13.x.

AC:

- [ ] [new image available in Kyma external repository](https://github.com/kyma-project/test-infra/issues/5109)
- [ ] [istio component chart updated to version 1.13.x](https://github.com/kyma-project/kyma/issues/13618)
- [ ] [istio reconciler uses istioctl 1.13.x to install istio 1.13.x](https://github.com/kyma-incubator/reconciler/issues/935)
- [ ] security scans green for main branch
- [ ] release notes for 2.2
- [ ] [run manual tests](https://github.com/kyma-project/kyma/issues/13619)
- [ ] update grafana dashboards if needed
- [ ] verify kiali features
- [ ] verify trace propagation and trace data transport to jaeger
- [ ] notify monitoring team to verify that metric cardinality has not increased (Envoy metrics)
- [ ] bump istioctl in reconciler pipelines
- [ ] gardener cluster can be hibernated

**Reasons**

For security & support reasons we should be up to date with the latest Istio release.

Attachments

https://istio.io/latest/news/releases/1.13.x/announcing-1.13/
