### ISSUE TITLE
Automated updates of observability upstream components

### ISSUE THREAD

**Issue by lindnerby** [kyma-project/kyma#13747]
**Description**

Since the process of tending to chart upgrades is tedious and time consuming, we want to automate the process as much as possible.
For this we need to first compare our charts with upstream charts - look at customisations and describe why we did them. Decide if we need to keep them and gain an overview of all customisations.

**Items**

- [x] https://github.com/kyma-project/kyma/issues/13806
- [ ] #13756
- [ ] #13749
- [ ] #13757
- [ ] #13753
- [ ] #13751
- [ ] #13754
- [ ] #13755
- [ ] #13748
- [ ] #13750
- [ ] Notifications for available upgrades
- [ ] Identify and close test coverage gaps
- [ ] Automatic PR creation
- [ ] Pipelines for testing with upgraded versions

**Comment by skhalash** [comment]
Closing the issue since most of the components will be deprecated, this investment is not worth it.
