### ISSUE TITLE
Switching Eventing Backends

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#13800]
As an admin for kyma eventing I want an easier / more kubernetes like setup process for my eventing backend. At the moment i have to label a secret to switch the backend to EventMesh. The result of this switching process can be seen in an otherwise unused eventingbackend CR. I want to use this CR to specify all configuration for my selected backend. 

For EventMesh this means i want to specify the secret here
For Nats this means i want to configure limit, maximum inflight etc in this resource.
Along with that configuration i want that CR to display all relevant state information about the health of the selected backend. If eventing supports additional backends in the future all of those backends should also be configured using this CR.

**Tasks**:
- [x] #14129
- [x] #14332
- [x] #14128 
- [ ] Update documentation on how to switch backends

**Comment by nachtmaar** [comment]
**Tasks**:
- [ ] Change eventingbackend CR to allow defining a secret for BEB (e.g. eventingbackend.Spec.Beb.secretRef=<name of secret>)
- [ ] Enable specifying the eventing backend type to be used (e.g. `eventingbackend.Spec.Type=nats`)
- [ ] Allow specifying config on the eventingbackend CRD
  - [ ] Beb secrets
  - [ ] Nats config options such as limit, maximum inflight
- [ ] migration in Kyma Reconciler
- [ ] change code in eventing backend controller to read active eventing backend from eventingbackend CR instead of label on Secret
**Info**:
- eventingbackend CR is currently created as part of the eventing charts: https://github.com/kyma-project/kyma/blob/main/resources/eventing/charts/controller/templates/eventingbackend.yaml

**Comment by k15r** [comment]
Switching will be taken care off by the new eventing manager
