### ISSUE TITLE
Improve Usability of Function CRD

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#13828]
**Description**

Provide a stable version of Function CRD incorporating the sub-type division between the inline and git-sourced types

**AC**
 - [x] Clean up spec fields that are spread on the root level (i.e source related) - [branch](https://github.com/m00g3n/kyma/tree/fn-crd-refactor)
 - [x] Clean up scaling related fields (and support scale subresource to make Function scalable by any scaler) - [PR](https://github.com/m00g3n/kyma/pull/3)
 - [x] Implement conversion webhooks so that old specs requested by non-migrated clients are supported - [Issue](https://github.com/kyma-project/kyma/issues/14593)
 - [x] Plan an issue for next serverless apiversion support in kyma CLI [issue](https://github.com/kyma-project/cli/issues/1314)
 - [x] Plan an issue for next serverless apiversion support in Kyma Dashboard
 - [x] Document CRD changes - [issue](https://github.com/kyma-project/kyma/issues/15002)
 
**Reasons**
 - cleaning up API of the Function CRD

**Attachments**
![serverless-architecture drawio](https://user-images.githubusercontent.com/6783567/180386324-71585751-3d8e-44d1-ace2-426cf772a58d.png)

[serverless-architecture.drawio.zip](https://github.com/kyma-project/kyma/files/8588716/serverless-architecture.drawio.zip)

**Comment by Disper** [comment]
Work plan:
- [ ] generate the project 
- [ ] put it into the repository
- [ ] adapt function controller to support watching
- [ ] create new reconciler to handle it
- [ ] add tests to cover scenarios

**Comment by kwiatekus** [comment]
We need to poc the following:

 - getting rid of GitRepo CRD !!
 - propose changes in Function CRD (eliminate git related pros ??)
 - design GitFunction CRD 
 - decision whether we need a dedicated controller (or have a reconciliation branch in the function controller)

**Comment by m00g3n** [comment]
https://github.com/kyma-project/kyma/pull/14142

**Comment by kwiatekus** [comment]
Currently blocked by missing conversion between versions
https://github.com/kyma-project/kyma/issues/14593
