### ISSUE TITLE
Revisit Application Connector tests

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/kyma#13977]
**Description**

We need to provide a clear suite of tests that will go through all the functionalities that Application Connector presents.
Right now we have multiple tests that run through the same scenario and test the same code.

The desired state would be to have:
- ~~a FIT scenario that goes through the whole flow available without Compass and testing available Application Gateway auth methods~~
  - ~~called either from lambda via internal eventing (presents some coupling to the Serverless and Eventing area)~~
  - ~~called from within a cluster with regular call~~
- ~~a FIT scenario that goes through Compass integration, tests the whole registration flow with Commerce Mock, sends an event through the mTLS gateway, and checks whether the external API of Commerce Mock can be called (make sure the cleanup is done properly in Compass)~~
- A test checking the functionalities of Application Gateway (proxying, various auth methods available - we could introduce mocks here for checking different methods)
- A test checking whether Applications are properly synchronized by the Compass Runtime Agent (we can use the static Compass tenant and just check if Compass Runtime Agent downloaded and applied the proper YAML)
- A test checking Connectivity Validator functionality (consider using a static TLS certificate and just sending a request there)

ad 1) we have multiple Octopus tests in Go that should be removed as they are no longer used (https://github.com/kyma-project/kyma/issues/13338)
ad 2) we need to clean up old prow pipelines (https://github.com/kyma-project/kyma/issues/11870)

**Reasons**

A clear test structure and responsibility division will reduce maintenance effort and provide better quality for the area. It will be transparent which components fail and which require some attention.

**Acceptance Criteria**
- [x] Mentioned test cases implemented
- [x] Unnecessary tests removed
- [x] Testing should take minimal possible execution time
- [x] Tests implemented should be easily maintainable

**Comment by Disper** [comment]
[This testing strategy draft documentation](https://github.tools.sap/pandas/testing-strategy) might be somehow relevant.

**Comment by janmedrek** [comment]
I have updated the test cases - with the modularization on the horizon we want to make sure that tests for the Application Connector module are separated.

**Comment by VOID404** [comment]
Gateway Tests PR: [#1450](https://github.com/kyma-project/kyma/pull/14504)

**Comment by akgalwas** [comment]
The following requirements were defined for the test project structure:
- It will be added here: https://github.com/kyma-project/kyma/tree/main/tests/components
- There will be separate subfolder for each test-suite
- There will be separate image built for each test-suite
- Each test-suite subfolder will contain all the manifests and code needed by the testsuite

**Comment by akgalwas** [comment]
Authorisation methods supported by Application Gateway:
- no authorisation
- Basic Auth
- OAuth (grant client credentials flow)
- OAuth protected with mTLS (please ee #14401)
- mTLS
- csrf
  - no authorisation
  - Basic Auth
  -  OAuth (grant client credentials flow)
  - OAuth protected with mTLS
  - mTLS

**Comment by akgalwas** [comment]
Work plan:
- [ ] 1. Prepare and merge initial PR with test project structure (#1450)
- [ ] 2. Prepare initial structure of test app and merge it into test project structure. Use the minimal 
- [ ] 3. Implement pipeline for testing Application Gateway
- [ ] 4. Implement supported authentication methods in test application
- [ ] 5. Implement all test-cases in Application Gateway test-suite
- [ ] 6. Prepare initial design for Connectivity Validator test-suite
- [ ] 7. Implement Connectivity Validator test-suite
- [ ] 8. Implement pipeline for testing Connectivity Validator 
- [ ] 9. Prepare initial design for Compass Runtime Agent test-suite
- [ ] 10. Implement Compass Runtime Agent test-suite
- [ ]  11. Implement pipeline for testing Compass Runtime Agent

**Comment by janmedrek** [comment]
@VOID404, @mvshao please separate the following cases into linked GH issues:
- Application Gateway tests + pipeline
- Connectivity Validator tests + pipeline
- Compass Runtime Agent tests + pipeline

You can also move the above comments from @akgalwas to those issues, and keep this one transparent as a collective epic for a new test suite for the whole area. 🙂

**Comment by franpog859** [comment]
The Application Gateway tests are done, @janmedrek

**Comment by franpog859** [comment]
I created a follow-up issue https://github.com/kyma-project/kyma/issues/15666 for this one https://github.com/kyma-project/kyma/issues/15037 as we wanted to first create an integration test that enables us to abandon the manual release testing and then enhance the tests with all of the additional CRA responsibilities checks
