### ISSUE TITLE
Making CleanEventTypes not optional breaks eventing tests

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#14293]
**Description**

When we want to make `CleanEventTypes` field in the Subscription status non-optional, in other words to remove `omitempty` [here](https://github.com/kyma-project/kyma/blob/9046447c9818993c2107b3c81d3fcb3276d1fe64/components/eventing-controller/api/v1alpha1/subscription_types.go#L189), the eventing tests fails when we run `make test-local`. The tests do not fail when you run them from the IDE.

**Expected result**

`make test-local` does not fail

**Actual result**

`make test-local` fails with failing tests where condition matchers that obtain `nil` condition when an actual condition was expected.

The status should show the `CleanEventTypes` in `subscription.status` as empty array instead of not showing the field in status at all. For example:
```
status:
    cleanEventTypes: []

```

**Steps to reproduce**

- Remove `omitempty` [here](https://github.com/kyma-project/kyma/blob/9046447c9818993c2107b3c81d3fcb3276d1fe64/components/eventing-controller/api/v1alpha1/subscription_types.go#L189)
- Run `make test-local`

**Tasks**
- [x] Remove `omitempty` [here](https://github.com/kyma-project/kyma/blob/9046447c9818993c2107b3c81d3fcb3276d1fe64/components/eventing-controller/api/v1alpha1/subscription_types.go#L189) from `CleanEventTypes` field in the Subscription status.
- [x] Check if the expected behaviour (Actual result) is achieved.
- [x] Make sure the unit/integration tests are green.
