### ISSUE TITLE
 Implement the newly designed eventing-backend CRD

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#14332]
In the proposal [Add the Eventing backend CRD design proposal #671](https://github.com/kyma-project/community/pull/671/files) a newly designed EventingBackend CRD is proposed. This ticket is about reflecting the changes in the EventingBackend Reconciler.

This ticket follows the following assumption:
We only support **one** `EventingBackend` (the name and namespace of the eventing-backend  are [defined](https://github.com/koala7659/kyma/blob/remove-registry-and-connector-charts-2/components/eventing-controller/pkg/env/backend_config.go#L14) in the backend reconciler with default values). As soon as we support multiple active backends, this will change of course.

**Tasks**:
- [ ] Implement the newly designed eventing-backend CRD.
  - [ ] Add the `Eventing Backend Ready condition` type to the controller
  - [ ] Add `spec.config` support to the controller
- [ ] Switch to beb if `spec.type=beb` and `spec.config.secretRef` is valid
  - [ ] Implement eventing-backend reconciler to react on changes on new backend CR.
    - [ ] e.g. changing `maxInflight` is reflected on underlying eventing infrastructure
