### ISSUE TITLE
Java runtime for kyma serverless

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#14357]
**Description**

Introduce a serverless java runtime that is based on JDK  designed for fast execution in a container.

**AC**
 -  modern JRE  based on SAP Java Stack 
 -  logs from the runtime can be collected
 -  traces and java specific metrics (i.e heap size) can be pushed via java flavoured open-telemetry SDK

**Minimal Requirements**
- [ ] POC- use SAP Machine java stack - https://github.com/kyma-project/serverless-manager/issues/329
- [ ] build and run local java containers with user provided handlers and dependencies - https://github.com/kyma-project/kyma/issues/15825 - in progress
- [ ] build and run java function in Kyma runtime - https://github.com/kyma-project/kyma/issues/15660
- [ ] java runtime available only with a feature toggle - disabled on managed runtimes

**Requirements**
- [ ] use SAP Java stack (Sap Machine)
- [ ] observability tools for java functions - https://github.com/kyma-project/kyma/issues/15847
- [ ] Update documentation - https://github.com/kyma-project/kyma/issues/16376

**Additional features**
- [ ] GraalVM as java runtime (?) - could it be combined with SAP Java Stack ?
- [ ] Benchmark java runtime and add it to: https://github.com/kyma-project/kyma/tree/main/tests/serverless-bench
- [ ] Update CLI
- [ ] Update Busola

**Known bugs**
- [ ] User cannot use custom dependency in Java Runtime

**Reasons**

Having java as function runtime may increase kyma adoption among teams with a strong dedication to Java ( i.e team skillset )
Java is widely adopted language among many developers ( incl. those on kyma customers side ).
It might help transforming  big monolithic enterprise java applications into micro-service architecture and delivering parts of it as functions. This will all contribute to kyma becoming enterprise grade runtime.
 
 

**Attachments**
 - https://fission.io/docs/usage/languages/java/
 - https://quarkus.io/guides/funqy
 - https://sap.github.io/SapMachine/

**Comment by osigge** [comment]
Hello.
Great to see you're looking into serverless java functions!
Do you plan to include Fission or will you build your own implementation, just "inspired" by fission?

**Comment by ralikio** [comment]
I want to suggest considering support for newer JDK versions than 1.8 and possible usage of GraalVM.

**Comment by purplehaze** [comment]
Great to see movement in right sap->kyma-java direction :)

**Comment by kwiatekus** [comment]
> Hello. Great to see you're looking into serverless java functions! Do you plan to include Fission or will you build your own implementation, just "inspired" by fission?

@osigge we dont plan to bring fission as part of kyma serverless. we already have all the mechanics for building container and deploying it on k8s.  We will look into different runtime approaches (dockerfile basically) used in different FaaS solutions to see which one best suits kyma
