### ISSUE TITLE
Istio 1.14.x bump

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#14490]
**Description**

Upgrade Istio to 1.13.x.

AC:

- [x] [provision test clusters](https://github.com/kyma-project/kyma/issues/14474)
- [x] [new image available in Kyma external repository](https://github.com/kyma-project/test-infra/issues/5531)
- [x] [istio component chart updated to version 1.14.x](https://github.com/kyma-project/kyma/issues/14488)
- [x] [istio reconciler uses istioctl 1.14.x to install istio 1.14.x](https://github.com/kyma-incubator/reconciler/issues/1103)
- [x] release notes for kyma 2.4
- [x] [run manual tests](https://github.com/kyma-project/kyma/issues/14489)
- [x] Update grafana dashboards and verify that they are working
- [x] verify kiali features (huskies)
- [x] verify trace propagation and trace data transport to jaeger (huskies)
- [x] notify monitoring team to verify that metric cardinality has not increased (Envoy metrics) (huskies)
- [x] kiali should be bumped to 1.50+ version (huskies) https://github.com/kyma-project/kyma/pull/14589

**Reasons**

For security & support reasons we should be up to date with the latest Istio release.

Attachments

https://istio.io/latest/news/releases/1.14.x/announcing-1.14/

**Comment by lindnerby** [comment]
@strekm The Kiali upgrade is prepared with https://github.com/kyma-project/kyma/pull/14589 and we are ready for this Istio 1.14 bump to be completed to merge it.
