### ISSUE TITLE
Proposal for refactoring eventing subscription CRD filters

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#14552]
### Context

We discussed in this [epic](https://github.com/kyma-project/kyma/issues/13797) that we want to write a proposal first before jumping into any implementation since this needs some 🧠 power. Since it is hard to describe what the outcome of the proposal is we had the idea that the proposal shall provide us answers to questions and we just need to come up with the questions:

### These questions shall be answered by the proposal

- [x] What are the current **ways to subscribe** to events / which **rules** does eventing have to follow in these cases:
    - **Cases**:
        - [x] `external` event (via gateway, https://gateway.<domain>/myapp/events)
        - [x] `internal` event (via event-publisher-proxy)
        - [x] events sent `directly` to the underlying eventing system (e.g. `Event Mesh`)
        - [x] NATS vs. Event Mesh
    - **Reasoning**: This is a good introduction to the proposal and gives the reader an overview over the current state before proposing a better solution.
- [x] How would eventing look like `without` the `limitations/validations` which we only do for Event Mesh ?
    - or **formulated differently**: Which information are only required by the user to subscribe to events and which information are required only by the backend and could be inferred/created by us ?
    - **Reasoning**: This can help us get an idea of what we can make easier for the user.
- [x] in case we want to remove backend specific (e.g. event-mesh) limitations from subscription CRD to source code. how can this be achieved ? 
   - [x] How can we make it generic for multiple backends? 
   - [x] How can be provide backend specific configs per subscription?
- [ ] What is required in order to jump into the `implementation` of the task ?

### Scope of the proposal

- Merging the proposal on [https://github.com/kyma-project/community](https://github.com/kyma-project/community) means that:
    - [x] `Follow-up tickets` for the implementation of this epic are created.
    - In case the proposal comes up with multiple options:
        - [x] Then there should be `team agreement` on what is the `preferred option`.
        - [x] The `pros and cons` of the different options should be described to help the reader understand the options.

**Comment by mfaizanse** [comment]
https://github.com/kyma-project/community/pull/697

**Comment by k15r** [comment]
remaining estimate: 5

**Comment by mfaizanse** [comment]
## Tasks

- [ ] Create new version for Subcription CRD.
  - [ ] Implement [convertion logic](https://book.kubebuilder.io/multiversion-tutorial/conversion.html) for old CRD version to new CRD version.
- [ ] Define validation webhook for new Subcription CRD.
- [ ] Implement event type cleaner for JetStream.
- [ ] Implement event type cleaner for EventMesh.
- [ ] Implement handler for JetStream.
- [ ] Implement handler for EventMesh.
- [ ] Implement JetStream reconciler for new Subcription CRD.
  - [ ] Pre-requisite: [Proposal for Subscription.status](https://github.com/kyma-project/kyma/issues/14892)
- [ ] Implement EventMesh reconciler for new Subcription CRD.
  - [ ] Pre-requisite: [Proposal for Subscription.status](https://github.com/kyma-project/kyma/issues/14892)
- [ ] Implement new publishing logic for JetStream in event-publisher-proxy.
- [ ] Implement new publishing logic for EventMesh in event-publisher-proxy.
  - Question: Shall we still support the old way of pubishing for existing customers?
- [ ] Eventing reconciler tp upgrade kyma cluster with new CRD

**Comment by mfaizanse** [comment]
We need to decide about the upgrade flow, how will we support the old subscription CRD before jumping into implementation.
