### ISSUE TITLE
Make the eventing-upgrade pipeline a pre-submit job to the release branches

### ISSUE THREAD

**Issue by vpaskar** [kyma-project/kyma#14569]
**Description**

As a follow-up to https://github.com/kyma-project/kyma/issues/13395, where the job was stabilised and set to required, we now want to make the it a pre-submit job to the release branches. 

As a pre requisite:
- [x] Fix the upgrade issue: https://github.com/kyma-project/kyma/issues/13789
   NOTE: We have done if for our eventing upgrade job, therefore it is not a blocker for this issue.

**Tasks:**
- [x] Make the job mandatory first on main branch
- [ ] If the job is stable on main branch then copy it to release-branches
   - [ ] make it to trigger on all PR regardless the eventing components were modified or not.

**Comment by mfaizanse** [comment]
@k15r Why this https://github.com/kyma-project/kyma/issues/13789 still a pre-requisite? We had a fix for our eventing upgrade pipeline.

**Comment by VladislavPaskar** [comment]
After https://github.com/kyma-project/kyma/issues/15215 was closed and upgrade job seems to be stable,  we can make this job mandatory

**Comment by VladislavPaskar** [comment]
The upgrade job is already required, only the second tasks remains.
