### ISSUE TITLE
Kyma installation on Mac M1 fails

### ISSUE THREAD

**Issue by veichtj** [kyma-project/kyma#14647]
**Description**
Installation of Kyma on Mac M1 does fail on different component issues.

**Expected result**
Kyma can be successfully installed on Mac M1 without any special adjustments.

**Actual result**

Installation fails on different components, with different error messages

**Steps to reproduce**
Install Kyma 2.2 locally on Mac M1 

**Installation currently fails on following components:**
- [x] [Installation of Application connector should run successful](https://github.com/kyma-project/kyma/issues/14617)
- [x] [Installation of Kiali component should run successful](https://github.com/kyma-project/kyma/issues/14615)
- [x] [Installation of istio component should run successful](https://github.com/kyma-project/kyma/issues/13391)

**Comment by janmedrek** [comment]
We've went through the issue for Kiali and it's the Istio Sidecar that fails, I've created the ticket, will close the component ones: https://github.com/kyma-project/kyma/issues/14797

**Comment by dariusztutaj** [comment]
Istio 1.15 is also not working on M1

**Comment by dragosnutu** [comment]
I was able to successfully install kyma on Mac M1. I am wondering what is the specific issue that does not work here?

I do have some issues with deploying a function or a service stating that the local registry can't be accessed. Is this related or this is some other issue?

```
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "k3d-kyma-registry:5000/default-demofun:bcdb6cadda32d13168474795275702856238535ca3ffe5e4edfadae378830acf": creating push check transport for k3d-kyma-registry:5000 failed: Get "https://k3d-kyma-registry:5000/v2/": dial tcp: lookup k3d-kyma-registry on 10.43.0.10:53: no such host; Get "http://k3d-kyma-registry:5000/v2/": dial tcp: lookup k3d-kyma-registry on 10.43.0.10:53: no such host
```
