### ISSUE TITLE
New Application Connectivity tests - Test suite for Application Gateway

### ISSUE THREAD

**Issue by mvshao** [kyma-project/kyma#14654]
**Description**
This task aims to implement separate Application Gateway tests into a separate minimal suite, written in Go. 
The general idea is described [here](https://github.com/kyma-project/kyma/issues/13977#issuecomment-1148410870).

**Acceptance criteria**
- [x] New project created under the following directory: https://github.com/kyma-project/kyma/tree/main/tests/components
- [x] All authentication methods listed [here](https://github.com/kyma-project/kyma/issues/13977#issuecomment-1148492062) covered.
- [x] All test-cases listed [here](https://github.com/kyma-project/kyma/issues/13977#issuecomment-1148462789) covered.
- [x] Test is deployable on Kubernetes.
- [x] Makefile compatible with pipeline

**Related issue**
Test's build pipeline: [test-infra#5563](https://github.com/kyma-project/test-infra/pull/5563)
#13977

**Comment by VOID404** [comment]
# Workplan

- [ ]  Endpoints + AppCR entries ([docs](https://kyma-project.io/docs/kyma/main/03-tutorials/00-application-connectivity/ac-04-register-secured-api/)):
    - [x]  no authorisation
    - [x]  Basic Auth
    - [x]  OAuth protected with mTLS (please see #14401)
    - [ ]  OAuth (grant client credentials flow)
    - [ ]  mTLS (a.k.a CertGen)
    - [ ]  CSRF with:
        - [ ]  no authorisation
        - [ ]  Basic Auth
        - [ ]  OAuth (grant client credentials flow)
        - [ ]  OAuth protected with mTLS
        - [ ]  mTLS
    - [ ]  Expired scenarios
- [ ]  Logging
    - [ ]  in test-app
    - [ ]  in tests
- [ ]  Log formatting?
- [ ]  Deployments
    - [ ]  Dockerfile
    - [ ]  Helm Charts
    - [ ]  `Makefile`

**Comment by akgalwas** [comment]
Plan
- [ ] Prepare initial PR with project structure. It should test BasicAuth with positive authorisation only. The goal is to deliver MVP and allow parallel work. https://github.com/kyma-project/kyma/pull/14743
- [ ] Prepare pipeline for building Gateway tests 
https://github.com/kyma-project/test-infra/pull/5563/files
- [ ] Prepare pipeline for executing Gateway tests 
- [ ] Enhance test with path related scenarios https://github.com/kyma-project/kyma/pull/14762
- [ ] Enhance test with kubernetes resources related tests https://github.com/kyma-project/kyma/pull/14763
- [ ] Enhance test with CSRF scenarios
  - [ ] Implement Basic Auth case 
  - [ ] Consider adding different authentication methods 
- [ ] Enhance test with proxying related tests

**Comment by Disper** [comment]
Gateway OAuth cache issue has been extracted to [this issue](https://github.tools.sap/kyma/backlog/issues/2774)

**Comment by franpog859** [comment]
Everything is merged. Please, reopen it if something is missing
