### ISSUE TITLE
Post-new flow Application Connectivity documentation enhancement 

### ISSUE THREAD

**Issue by majakurcius** [kyma-project/kyma#14740]
**Description**

Following the switch to the new flow in Application Connectivity, add more details to Application Connectivity documentation.

**TODO:**

Part1:

  - [x] In [ac-03-application-gateway.md](https://github.com/kyma-project/kyma/blob/main/docs/05-technical-reference/00-architecture/ac-03-application-gateway.md), mention that the path in the Compass scenario contains the API Bundle and API definition. See [this PR](https://github.com/kyma-project/kyma/pull/12259/files).
  - [x] In [ac-01-application-gateway-details.md](https://github.com/kyma-project/kyma/blob/main/docs/05-technical-reference/ac-01-application-gateway-details.md), describe the structure of the Secret storing credentials. See [this PR](https://github.com/kyma-project/kyma/pull/12259/files). 
  - [x] In [ra-01-configuring-runtime.md](https://github.com/kyma-project/kyma/blob/main/docs/05-technical-reference/ra-01-configuring-runtime.md), mention that Compass Runtime Agent fetches credentials from Director and creates secrets used by Application Gateway. See [this comment](https://github.com/kyma-project/kyma/pull/12259/files#r723025197). 
  - [x] In [ra-01-configuring-runtime.md](https://github.com/kyma-project/kyma/blob/main/docs/05-technical-reference/ra-01-configuring-runtime.md), mention how Application, API Bundle, and API definition are mapped. See [this comment](https://github.com/kyma-project/kyma/pull/12259/files#r723031762). 
  - PR: #14777 

~Part 2:~
  - ~Consider adding a new troubleshooting guide for App Gateway. See [this comment](https://github.com/kyma-project/kyma/pull/12259/files#r723011612).~ 
  ~See also [this comment](https://github.com/kyma-project/kyma/issues/11620#issuecomment-874595455) on Central Application Gateway and Central Connectivity Validator.~
Will be done as a separate issue #14807 

**Related issues**
#11047
#12353

**Comment by majakurcius** [comment]
This document is a mine of information: https://github.tools.sap/framefrog/documentation/tree/master/investigations/gateway-url-in-app
