### ISSUE TITLE
Support k8s 1.23 & prepare support for k8s 1.24

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#14760]
**Description**
Currently kyma support k8s 1.21. As the service catalog got removed we finally can support the next versions 1.22 and 1.23

Furthermore the support for version 1.24 should be prepared by already having a pipeline in place to identify problems fast and start addresing them.

AC:
- all pipelines are upgraded to k8s 1.23
- CLI provisioning is adjusted to new versions
- documentation is updated
- migration guide with potential manual actions is ready
- there is one new k3d based pipeline running on k8s 1.24 (pre-main-kyma-integration-k3d-k8s-preview)

**Reasons**
Support for k8s 1.21 will be discontinued

**Tasks**
- [x] [k8s update] @a-thaler Verify k8s 1.21 support on k3d
- [x] [k8s update] @a-thaler  Default version for Kyma CLI is k8s 1.23 (https://github.com/kyma-project/cli/pull/1306)
- [x] [k8s update] @kasiakepka [Testing (all prow jobs) is based on K8S 1.23](https://github.com/kyma-project/test-infra/issues/5702)
- [x] [k8s update] @kasiakepka [Default version for kubectl is 1.23 (Docu, Prow)](https://github.com/kyma-project/test-infra/issues/5703)
- [x] [k8s update] @NHingerl document new version and add release notes (https://github.com/kyma-project/kyma/pull/14800)
- [x] [k8s update] @kasiakepka Verify that kyma can run with k8s 1.24 (with preview prow job) https://github.com/kyma-project/test-infra/pull/5685

**Attachments**

- Previous updates
  - [k8s 1.21](https://github.com/kyma-project/kyma/issues/13135)
- Resulting problems
  - https://github.com/kyma-project/test-infra/issues/5755
- k8s 1.24 problems
  - https://github.com/kyma-project/kyma/issues/14809
---
<details>
    <summary>:warning: Funnel process - do not remove!</summary>
    </br>

Name|Value
:--- | :---
theme | Technical Debt
business value | 2
technical value | 10
user value | 10
open-source value | 10
effort | 
requested by | 
</details>

**Comment by a-thaler** [comment]
Updating the preview to 1.24 revealed this problem: https://github.com/kyma-project/kyma/issues/14809

**Comment by a-thaler** [comment]
Epic was solved with kyma 2.6 already
