### ISSUE TITLE
Define testing requirements for Kyma modules

### ISSUE THREAD

**Issue by varbanv** [kyma-project/kyma#14940]
**Description**

As part of the modularization effort for Kyma, we need to ensure that all modules deliver consistent quality, no matter if the module is provided by Kyma teams or not.
To that end, we need to define and document all the requirements around testing a module must meet in order to be part of the Kyma ecosystem. 

**Acceptance criteria**
- [ ] Define the type of tests required
- [ ] Define how the test results would be delivered
- [ ] Define how the test results would be evaluated
- [ ] Define the "pass' vs "fail" criteria
- [ ] Define ownership of the tests
- [ ] The requirements should be valid for all modules
- [ ] There should be a clear on-boarding process related to the above
- [ ] Define a governance framework related to module testing requirements 

**Notes**
Here are some examples of tests that should potentially be required:

- Deploy module in current Kyma version and verify component health
- Deploy module in next Kyma version and verify component health
- Perform module upgrade in current Kyma version and verify component health
- Perform module upgrade in next Kyma version and verify component health
- Perform Kyma upgrade from current to next version and verify component health
- Perform Kubernetes upgrade from current version to next and verify component health

**Comment by tobiscr** [comment]
Testing strategy is prepared as part of the governance model and [documented in the Wiki](https://github.tools.sap/pandas/testing-strategy/tree/master/modularisation).

**Comment by tobiscr** [comment]
@varbanv : can we close this issue as duplicate of https://github.tools.sap/pandas/backlog/issues/1?

If we need some public documentation for Kyma modules, we should probably handle that as part of the governance model as this will probably also required some public documentation.
