### ISSUE TITLE
Guidance for running Redis on Kyma

### ISSUE THREAD

**Issue by varbanv** [kyma-project/kyma#14974]
**Description**

Document guidance on how to run Redis on Kyma following best practices and industry standards.

**Reasons**

Users that want to run Redis in Kyma clusters should do so in a consistent and secure manner, following best practices and industry standards. 
If we provide detailed guidance on how to deploy and use Redis in-cluster, we can improve the user experience and reduce issues with cluster resources and security. 

**Acceptance Criteria**
- [ ] Documented process for installing Redis in a Kyma cluster
- [ ] Documented process for day 2 operations
- [ ] Document any best-practices around usage of the Redis instance in-cluster
- [ ] Evaluate the option to provide Redis as a module in Kyma

---
<details>
    <summary>:warning: Funnel process - do not remove!</summary>
    </br>

Name|Value
:--- | :---
theme | Enterprise-grade
business value | 10
technical value | 0
user value | 10
open-source value | 10
effort | 
requested by | 
</details>

**Comment by pbochynski** [comment]
SAP open-sources a new Redis operator: https://github.com/SAP/redis-operator. It looks like a good starting point for the guide.
