### ISSUE TITLE
Improve liveness health check for NATS JetStream

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#15046]
As a follow up of [ticket](https://github.com/kyma-project/kyma/issues/14964).

**Pre-requisites:**
- ~~https://github.com/kyma-project/kyma/issues/15096~~ (Not needed anymore).

**Current Situation:**

We are using the `/` endpoint for liveness checks in NATs [statefulsets](https://github.com/kyma-project/kyma/blob/6ccb994fcee2ea84413fe6cf4b56589eef504584/resources/eventing/charts/nats/templates/statefulset.yaml#L213). The `/` endpoint returns health status as OK even when jetstream gets disabled by that NATs pod instance.

The NATS helm [charts](https://github.com/nats-io/k8s/tree/main/helm/charts/nats) are updated to include the proper health checks and we need to sync ours charts as well.

**Info:**
`/healthz` [internally](https://github.com/nats-io/nats-server/blob/main/server/monitor.go#L2945) also does some health checks for JetStream server, streams and consumers.

- `/healthz?js-enabled=true` will return non-healthy status if JetStream is disabled on that instance.
-  `/healthz?js-enabled=true&js-server-only=true` will only check JetStream server but not the streams and consumers.

**Tasks:**

- [ ] Change [liveness check](https://github.com/nats-io/k8s/blob/22478d2cc639117b2e357e52fc9fc581363f5bcd/helm/charts/nats/templates/statefulset.yaml#L416) from `/` endpoint to `/healthz` as updated in the latest NATS helm [charts](https://github.com/nats-io/k8s/tree/main/helm/charts/nats). Check this [description](https://github.com/nats-io/k8s/pull/613#issue-1487467527) for NATS version specific recommendation for liveness endpoint.
- [ ] Decide it we should use the `/healthz` because it will check all the things including streams, consumers etc. And in our case we only identify the issue when we use `/healthz`.
- [ ] Test the upgrade (production profile) from kyma `2.9.3` to `2.10.0-rc1`
   - [ ] Keep publishing events during the upgrade to try to reproduce the issue. 

**Follow-up:**
- [ ] Maybe contribute to the NATS `/healthz` to only check the given stream via query parameter. e.g. `/healthz?check-stream=kyma` etc.

**Comment by mfaizanse** [comment]
TODO: Check when will be the next release for NATS server. If its too late then we an go with suggestion 2.

**Comment by mfaizanse** [comment]
Investigation:
- Does using the `/healthz?js-enabled=true&js-server-only=true` really resolve the issue when jetstream gets disabled.
- Whats makes JetStream disable? Which cases? And from which cases can we recover from?
   - e.g. When the storage is full, then why JetStream gets disabled? Is it expected behaviour or a bug?

**Comment by raypinto** [comment]
Also look into the readiness checks!

**Comment by marcobebway** [comment]
This [PR](https://github.com/nats-io/k8s/pull/613) introduces a fix the liveness/readiness probes.

**Comment by mfaizanse** [comment]
https://github.com/nats-io/k8s/issues/594

**Comment by mfaizanse** [comment]
Questions:
- Is downtime okay with statefulset recreation?
- Would PVCs will remain and no data loss.

**Comment by mfaizanse** [comment]
Next Todo's:
- [ ] Bring back eventing reconciler.
- [ ] Add a pre-action to remove the NATs statefulset if it has `podManagementPolicy = OrderedReady`, so that new Statefulset is created by NATs helm.
- [ ] Make sure the PVCs are not deleted during the upgrade process. No data loss.

**Comment by mfaizanse** [comment]
https://github.com/kyma-incubator/reconciler/pull/1151

**Comment by mfaizanse** [comment]
Waiting for the new `kyma-cli` release with the eventing controller, so the upgrade job for the last PR succeed.
