### ISSUE TITLE
JetStream Performance Evaluation across Cloud Providers

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#15198]
**Description**

With the latest JetStream reliability tests, we observed a difference in performance across Cloud Providers. With this ticket, we would like to evaluate, compare and document performance of NATS JetStream across Cloud Providers (i.e. Azure, AWS and GCP).

Previous Performance Evaluations done (all on GCP):
- https://github.com/kyma-project/kyma/issues/13736
- https://github.com/kyma-project/kyma/issues/14111
- https://github.com/kyma-project/kyma/issues/14451 (HA)

**ToDos**
- [x] Do the same performance evaluations for Azure and document the findings
- [x] Do the same performance evaluations for AWS and document the findings
- [x] Do the same performance evaluations for GCP and document the findings

**Hint**
- Put the findings [here](https://github.com/kyma-project/community/tree/main/concepts/eventing/performance%20evaluation)
- Use the same tool which was used for GCP. 
  - Run it for 1-2 days.
  - Do it for HDD and SSD based storage.
  - Use the production profile.

**Comment by muralov** [comment]
Results are documented [here](https://github.com/kyma-project/community/tree/main/concepts/eventing/performance%20evaluation/nats-jetstream/different-cloud-providers)
