### ISSUE TITLE
Deliver Releasable and testable artefacts for KEDA Manager

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#15290]
**Description**
We have already enabled functions to be scaled by external scalers
We have documented recipes how to scale using Keda API
Now we want to deliver Keda as a configurable kyma module installable via dedicated operator 

**Execution**
 - [x] investigate [keda-olm-operator](https://github.com/kedacore/keda-olm-operator) in the context of `kyma-lifecycle-manager`
 - [x] project structure - https://github.com/kyma-project/kyma/issues/15232
 - [x] basic smoke tests - https://github.com/kyma-project/keda-manager/issues/4
 - [x] ci pipeline - https://github.com/kyma-project/keda-manager/issues/5
 - [x] generate module template for Keda Module - https://github.com/kyma-project/keda-manager/issues/16
 - [x] add readme for for Keda manager - https://github.com/kyma-project/keda-manager/issues/8

**AC**
Keda Module 
 - conforms with modular architecture
 - could be tested independently
 - could be versioned, released and rolled independently

**Reason**
We want to give kyma users convenient tooling to scale kyma hosted workloads based on their own strategies, technology stack and requirements
We want to include KEDA as Kyma Module

**Related Issues**
https://github.com/kyma-project/kyma/issues/13176
https://github.com/kyma-project/community/pull/701
https://github.com/kyma-project/kyma/issues/13759
