### ISSUE TITLE
Istio 1.15.x bump with the Istio cni plugin

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#15347]
**Description**

Upgrade Istio to 1.15.x. with cni plugin enabled

AC:

- [x] [provision test clusters](https://github.com/kyma-project/kyma/issues/15338)
- [x] [new image available in Kyma external repository](https://github.com/kyma-project/test-infra/issues/5954)
- [x] [istio component chart updated to version 1.15.x](https://github.com/kyma-project/kyma/issues/15348)
- [x] [istio reconciler uses istioctl 1.15.x to install istio 1.15.x](https://github.com/kyma-incubator/reconciler/issues/1173)
- [x] [cni enabled for k3d provisioning](https://github.com/kyma-project/cli/issues/1373)
- [x] preview note for managed kyma informing about introducing Istio cni plugin
- [x] release notes for kyma 2.8
- [x] [run manual tests](https://github.com/kyma-project/kyma/issues/15349)
- [x] Update grafana dashboards and verify that they are working
- [x] verify kiali features (huskies)
- [x] verify trace propagation and trace data transport to jaeger (huskies)
- [x] notify monitoring team to verify that metric cardinality has not increased (Envoy metrics) (huskies)

**Reasons**

For security & support reasons we should be up to date with the latest Istio release.

Attachments

https://istio.io/latest/news/releases/1.15.x/announcing-1.15/
https://istio.io/latest/docs/setup/additional-setup/cni/
