### ISSUE TITLE
run manual tests after upgrade for istio 1.15.x

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#15349]
@

**Description**
Verify the correctness of Istio deployment and upgrade in 1.15.x by running manual tests.

**Reasons**

Istio bump in kyma

**Attachments**
https://github.com/kyma-project/kyma/issues/15347

# Tests

## Executed on gardener:

- [x] [[istio test] Access between namespaces](https://github.tools.sap/xf-goat/testing/issues/35)
- [x] [[Upgrade test] Istio reconcilation](https://github.tools.sap/xf-goat/testing/issues/29)
- [x] [Uninstall istio test](https://github.tools.sap/xf-goat/testing/issues/13) --> After `kyma undeploy --component istio` the dashboards are still there
- [x] [[Upgrade test] Istio downgrade](https://github.tools.sap/xf-goat/testing/issues/9)
- [x] [[Load test] Istio / ORY scaling + reconciliation](https://github.tools.sap/xf-goat/testing/issues/5)

### Load test results:

**No Istio sidecar**

- OAuth2 Oathkeeper secured rule

```yaml
running (1m01.0s), 000/500 VUs, 19898 complete and 0 interrupted iterations
default ✓ [======================================] 500 VUs  1m0s

     ✓ Successfull calls

     █ setup

     checks.....................: 100.00% ✓ 19898      ✗ 0    
     data_received..............: 53 MB   869 kB/s
     data_sent..................: 2.1 MB  34 kB/s
     http_req_blocked...........: avg=18.39ms  min=232ns   med=479ns    max=1.52s    p(90)=612ns    p(95)=792ns   
     http_req_connecting........: avg=5.82ms   min=0s      med=0s       max=1.26s    p(90)=0s       p(95)=0s      
     http_req_duration..........: avg=1.49s    min=10.53ms med=1.55s    max=7.71s    p(90)=1.76s    p(95)=1.93s   
     http_req_failed............: 0.00%   ✓ 0          ✗ 19899
     http_req_receiving.........: avg=699.79µs min=29.24µs med=75.69µs  max=893.39ms p(90)=238.05µs p(95)=520.58µs
     http_req_sending...........: avg=1.73ms   min=46.75µs med=150.39µs max=825.35ms p(90)=1.08ms   p(95)=2.06ms  
     http_req_tls_handshaking...: avg=10.96ms  min=0s      med=0s       max=1.4s     p(90)=0s       p(95)=0s      
     http_req_waiting...........: avg=1.49s    min=240.8µs med=1.55s    max=7.71s    p(90)=1.76s    p(95)=1.93s   
     http_reqs..................: 19899   326.348652/s
     iteration_duration.........: avg=1.51s    min=10.73ms med=1.55s    max=8.58s    p(90)=1.77s    p(95)=1.94s   
     iterations.................: 19898   326.332252/s
     vus........................: 500     min=500      max=500
     vus_max....................: 500     min=500      max=500
```

- Allow (VS only) results

```yaml
running (1m00.9s), 000/500 VUs, 41979 complete and 0 interrupted iterations
default ✓ [======================================] 500 VUs  1m0s

     ✓ Successfull calls

     █ setup

     checks.....................: 100.00% ✓ 41979      ✗ 0    
     data_received..............: 111 MB  1.8 MB/s
     data_sent..................: 3.8 MB  63 kB/s
     http_req_blocked...........: avg=3.5ms    min=198ns   med=404ns    max=562.61ms p(90)=532ns    p(95)=588ns   
     http_req_connecting........: avg=1.5ms    min=0s      med=0s       max=358.65ms p(90)=0s       p(95)=0s      
     http_req_duration..........: avg=713.5ms  min=2.33ms  med=688.64ms max=3.55s    p(90)=791.76ms p(95)=866.19ms
     http_req_failed............: 0.00%   ✓ 0          ✗ 41980
     http_req_receiving.........: avg=151.82µs min=27.3µs  med=60.95µs  max=183.96ms p(90)=89.81µs  p(95)=104.98µs
     http_req_sending...........: avg=218.84µs min=49.94µs med=119.06µs max=249.79ms p(90)=163.75µs p(95)=208.98µs
     http_req_tls_handshaking...: avg=1.48ms   min=0s      med=0s       max=415.42ms p(90)=0s       p(95)=0s      
     http_req_waiting...........: avg=713.13ms min=2.13ms  med=688.44ms max=3.54s    p(90)=791.5ms  p(95)=865.98ms
     http_reqs..................: 41980   689.613763/s
     iteration_duration.........: avg=717.83ms min=2.5ms   med=689.07ms max=4.11s    p(90)=792.8ms  p(95)=872.02ms
     iterations.................: 41979   689.597336/s
     vus........................: 500     min=500      max=500
     vus_max....................: 500     min=500      max=500
```

**With Istio sidecar**

- Allow strategy

```yaml
running (1m00.9s), 000/500 VUs, 42923 complete and 0 interrupted iterations
default ✓ [======================================] 500 VUs  1m0s

     ✓ Successfull calls

     █ setup

     checks.....................: 100.00% ✓ 42923      ✗ 0    
     data_received..............: 55 MB   900 kB/s
     data_sent..................: 3.9 MB  65 kB/s
     http_req_blocked...........: avg=3.74ms   min=199ns   med=415ns    max=628.74ms p(90)=514ns    p(95)=552ns   
     http_req_connecting........: avg=1.28ms   min=0s      med=0s       max=449.14ms p(90)=0s       p(95)=0s      
     http_req_duration..........: avg=698.02ms min=3.02ms  med=688.29ms max=2.41s    p(90)=754.71ms p(95)=782.13ms
     http_req_failed............: 0.00%   ✓ 0          ✗ 42924
     http_req_receiving.........: avg=115.4µs  min=25.35µs med=54.25µs  max=261.26ms p(90)=80.93µs  p(95)=91.81µs 
     http_req_sending...........: avg=154.87µs min=44.04µs med=98.88µs  max=234.2ms  p(90)=128.18µs p(95)=145.93µs
     http_req_tls_handshaking...: avg=2.39ms   min=0s      med=0s       max=565.35ms p(90)=0s       p(95)=0s      
     http_req_waiting...........: avg=697.75ms min=2.87ms  med=688.12ms max=2.41s    p(90)=754.53ms p(95)=781.9ms 
     http_reqs..................: 42924   704.257492/s
     iteration_duration.........: avg=702.08ms min=3.17ms  med=688.46ms max=2.42s    p(90)=755.05ms p(95)=783.05ms
     iterations.................: 42923   704.241085/s
     vus........................: 500     min=500      max=500
     vus_max....................: 500     min=500      max=500
```

- OAuth2

```yaml
running (1m01.1s), 000/500 VUs, 20468 complete and 0 interrupted iterations
default ✓ [======================================] 500 VUs  1m0s

     ✓ Successfull calls

     █ setup

     checks.....................: 100.00% ✓ 20468      ✗ 0    
     data_received..............: 30 MB   494 kB/s
     data_sent..................: 2.1 MB  34 kB/s
     http_req_blocked...........: avg=15.34ms  min=206ns   med=457ns    max=1.52s    p(90)=565ns    p(95)=714ns   
     http_req_connecting........: avg=3.97ms   min=0s      med=0s       max=570.04ms p(90)=0s       p(95)=0s      
     http_req_duration..........: avg=1.45s    min=11.69ms med=1.37s    max=6.46s    p(90)=1.96s    p(95)=2.19s   
     http_req_failed............: 0.00%   ✓ 0          ✗ 20469
     http_req_receiving.........: avg=493.48µs min=22.44µs med=59.89µs  max=866.48ms p(90)=106.98µs p(95)=285.47µs
     http_req_sending...........: avg=1.19ms   min=39.99µs med=104.63µs max=792.81ms p(90)=192.93µs p(95)=500.88µs
     http_req_tls_handshaking...: avg=10.22ms  min=0s      med=0s       max=1.34s    p(90)=0s       p(95)=0s      
     http_req_waiting...........: avg=1.45s    min=11.52ms med=1.37s    max=6.46s    p(90)=1.96s    p(95)=2.18s   
     http_reqs..................: 20469   335.273425/s
     iteration_duration.........: avg=1.47s    min=12.02ms med=1.37s    max=6.46s    p(90)=2.02s    p(95)=2.21s   
     iterations.................: 20468   335.257045/s
     vus........................: 35      min=35       max=500
     vus_max....................: 500     min=500      max=500
```

- Istio JWT

```yaml
running (1m01.0s), 000/500 VUs, 44321 complete and 0 interrupted iterations
default ✓ [======================================] 500 VUs  1m0s

     ✓ Successfull calls

     █ setup

     checks.....................: 100.00% ✓ 44321      ✗ 0    
     data_received..............: 57 MB   932 kB/s
     data_sent..................: 4.5 MB  74 kB/s
     http_req_blocked...........: avg=4.9ms    min=197ns   med=439ns    max=620.97ms p(90)=526ns    p(95)=563ns   
     http_req_connecting........: avg=424.8µs  min=0s      med=0s       max=120.89ms p(90)=0s       p(95)=0s      
     http_req_duration..........: avg=674.94ms min=3.54ms  med=668.22ms max=1.75s    p(90)=725.75ms p(95)=761.64ms
     http_req_failed............: 0.00%   ✓ 0          ✗ 44322
     http_req_receiving.........: avg=139.99µs min=22.78µs med=55.7µs   max=190.09ms p(90)=81.86µs  p(95)=95.82µs 
     http_req_sending...........: avg=133.34µs min=43.03µs med=105.65µs max=150.49ms p(90)=132.11µs p(95)=150.74µs
     http_req_tls_handshaking...: avg=3.58ms   min=0s      med=0s       max=511.21ms p(90)=0s       p(95)=0s      
     http_req_waiting...........: avg=674.67ms min=3.37ms  med=668.03ms max=1.75s    p(90)=725.57ms p(95)=761.38ms
     http_reqs..................: 44322   726.921362/s
     iteration_duration.........: avg=680.23ms min=3.72ms  med=668.78ms max=1.75s    p(90)=728.47ms p(95)=769ms   
     iterations.................: 44321   726.904961/s
     vus........................: 500     min=500      max=500
     vus_max....................: 500     min=500      max=500
```

## Executed on k3d:

- [x] [[istio test] Access between namespaces](https://github.tools.sap/xf-goat/testing/issues/35)
- [x] [[Upgrade test] Istio reconcilation](https://github.tools.sap/xf-goat/testing/issues/29)
- [x] [Uninstall istio test](https://github.tools.sap/xf-goat/testing/issues/13) --> After `kyma undeploy --component istio` the dashboards are still there
- [x] [[Upgrade test] Istio downgrade](https://github.tools.sap/xf-goat/testing/issues/9)
