### ISSUE TITLE
Infrastructure to develop and manage modules

### ISSUE THREAD

**Issue by arturskorupa** [kyma-project/kyma#15425]
## Description

Provide an infrastructure and tools to enable the frontrunner module development and operate it on local clusters. Basic tooling for module conformance tests is introduced. 

Detailed description of particular requirements is in attached issues.

## Acceptance Criteria

- [x] Lifecycle manager is able to install and operate the [frontrunner ](https://github.com/kyma-project/kyma/issues/15427) module locally.
- [x] Guidelines document for developing a module is ready (https://github.com/kyma-project/community/issues/700) [Q4/2022]
- [x] Manifest library
    - [x] is implemented (https://github.com/kyma-project/module-manager/issues/41) [Q3/2022]
    - [x]  and technical documentation is provided (https://github.com/kyma-project/module-manager/issues/143) [Q4/2022]
- [x] Module templates can be created and published with CLI (https://github.com/kyma-project/cli/issues/1301)
- [x] Module can be installed  (https://github.com/kyma-project/cli/issues/1318)  [Q4/2022]
- [x] ~Scope of conformance tests is defined.~ - (descoped, covered by https://github.com/kyma-project/cli/issues/1317)
- [x] ~Tooling for conformance test is available~ (descoped, covered by https://github.com/kyma-project/cli/issues/1317)

**Links**
- [Concept document](https://github.com/kyma-project/community/tree/main/concepts/modularization)
- [Transition plan ](https://github.com/kyma-project/community/blob/main/concepts/modularization/transition.md)
- [Lifecycle manager](https://github.com/kyma-project/lifecycle-manager)
- [Module manager](https://github.com/kyma-project/module-manager)

**Comment by jakobmoellersap** [comment]
- [ ] Second Rount of Load tests Complete

**Comment by tobiscr** [comment]
I'm marking the step "Manifest Library implemented" to be done because the missing piece is not mandatory for other teams and only relevant for operational purposes.

**Comment by tobiscr** [comment]
@clebs : afaik the deploy command is now ready and can be used to install a single Kyma module. The remaining tasks in ticket https://github.com/kyma-project/cli/issues/1318 are required to make it possible to install the full Kyma stack in an automated way into a cluster, right?

**Comment by tobiscr** [comment]
@jakobmoellersap  / @arturskorupa : I will move the part "enabling / disabling" a module to Phase 2b - for enabling other teams to start working with our framework respectively implementing their operators, it is not a required feature actually.

**Comment by jakobmoellersap** [comment]
Why does this need to be challenged? For me it is a crucial part of the Kyma Infrastructure

**Comment by jakobmoellersap** [comment]
Closing as all relevant items for Phase 1 have been completed. Some still need minor refinements and follow-ups (e.g. Documentation Revisits or some smaller follow-ups from Load Tests), but they are not blocking completion of Phase 1
