### ISSUE TITLE
Frontrunner component running on modular Kyma 

### ISSUE THREAD

**Issue by arturskorupa** [kyma-project/kyma#15427]
## Description

Frontrunner module (KEDA) is designed according to modular architecture guidelines and can be operated by the `Lifecycle Manager` running both locally. KEDA is a new component introduced to Kyma.  

Frontrunner module brings pipeline to build and test conformance with the `Lifecycle Manager`. Respective documentation is creates and can be re-used as a template for other modules. 

Detailed description of particular requirements is in attached issues.

## Acceptance Criteria

- [x] KEDA is developed according to the architecture guidelines - https://github.com/kyma-project/kyma/issues/15290
- [x] KEDA module is operated by `Lifecycle Manager`, both installed locally. It is optional module of Kyma, can be disabled/enabled by user (it should trigger installation/uninstallation of module's subcomponents)
- [x] Module has pipeline for building the binary image, assuring all needed quality standards and running conformance tests (leveraging respective tooling described in #15425 - https://github.com/kyma-project/keda-manager/issues/5
- [x] Module is documented and the documentation can be reused by other modules - https://github.com/kyma-project/keda-manager/issues/8

**Links**
- [Concept document](https://github.com/kyma-project/community/tree/main/concepts/modularization)
- [Transition plan ](https://github.com/kyma-project/community/blob/main/concepts/modularization/transition.md)
- [Lifecycle manager](https://github.com/kyma-project/lifecycle-manager)
- [Module manager](https://github.com/kyma-project/module-manager)

**Comment by dekiel** [comment]
We will research on possible solutions to bring workflows based prowjobs to our Prow instance. https://github.com/kyma-project/test-infra/issues/6134

**Comment by kwiatekus** [comment]
We are still missing module template generation 
https://github.com/kyma-project/keda-manager/issues/16

**Comment by kwiatekus** [comment]
Last things to review and accept:
 - finalise the documentation for how to run it locally  - https://github.com/kyma-project/keda-manager/pull/31
 - finalise the CI jobs to automatically generate artefacts that module-manager could pull - https://github.com/kyma-project/keda-manager/issues/16

**Comment by kwiatekus** [comment]
- [x] Keda manager installs KEDA
 - [x] Module manager can install Keda Manager
 - [x] Keda Manager CI jobs produce OCI image and manager image

Module Manifest for Keda can be applied in KCP or locally in the single cluster mode


[template.yaml.txt](https://github.com/kyma-project/kyma/files/9838917/template.yaml.txt)
