### ISSUE TITLE
Module installation with "preview" plan on test environment

### ISSUE THREAD

**Issue by arturskorupa** [kyma-project/kyma#15443]
## Description

Kyma `Lifecycle manager` is integrated with KEB and a preview plan is enabled for use on environments:  stage/dev.

## Acceptance Criteria

- [x] `Lifecycle manager` is integrated with KEB
- [x]  `Lifecycle manager` is deployed to Dev environment (requires https://github.com/kyma-project/lifecycle-manager/issues/43 + [SRE task](https://github.tools.sap/kyma/backlog/issues/2887)) [Q3/2022]
- [x]  `Lifecycle manager` is deployed to Stage environment [Q4/2022]
- [x]  _preview_ plan is available for Dev environment [Q4/2022, PK]
- [x]  _preview_ plan is available for Stage environment [Q4/2022, PK]

**Links**
- [Concept document](https://github.com/kyma-project/community/tree/main/concepts/modularization)
- [Transition plan ](https://github.com/kyma-project/community/blob/main/concepts/modularization/transition.md)
- [Lifecycle manager](https://github.com/kyma-project/lifecycle-manager)
- [Module manager](https://github.com/kyma-project/module-manager)

**Comment by piotrmiskiewicz** [comment]
**Tasks**
- [ ] Define the preview plan. AC: new plan which spins regular AWS. Hint: https://github.com/kyma-project/control-plane/pull/1712/files (most of that changes are not necessary, because we do not change the kyma version)
- [ ] Disabled integration with reconciler for preview plan (all processes)
- [ ] E2E unit tests: 
  - Create an e2e unit test for preview plan which asserts created Kyma resource. It is nice to have an assert with yaml passed as a string.
  - Enhance existing one e2e test with Kyma resource assertion
  - Implement a helper (and use it) to change the `status.state` to given value (simulation of the LM).
  - the unit test must be disabled until the steps are implemented.
- [ ] A step which creates/updates Kyma resource. The component list should be empty
  - Add this step in the provisioning/update/upgradeKyma processes. One implementation for all proccesses. If the upgradeKyma is not refactored, then use an adapter to be able to satisfy special interface.
  - Run the step with the feature flag (to enable/disable Lifecycle Manager integration)
  - Question: what channel should we use? possible values defined in the file: https://github.com/kyma-project/lifecycle-manager/blob/main/operator/api/v1alpha1/kyma_types.go#L148
- [ ] Add a step which checks the status of the Kyma (see: https://github.com/kyma-project/lifecycle-manager/blob/main/operator/api/v1alpha1/kyma_types.go#L123)
  - If the Kyma fails, the write to the log proper info from the status of the Kyma resource
- [ ] A step which deletes Kyma resource (and waits for the deletion as a separate step or the same - this must be defined)
  - question: Can we remove the kubeconfig if the Kyma was not properly deleted?
- [ ] Provide Kubeconfig for LM. Create a step (in the same stage where GetKubconfig is registered) which creates proper secret with the kubeconfig.
  - one implementation for provision/update/upgradeKyma process
  - implement a step, which removes the secret in the deprovisioning process. The step does not fail if the secret does not exists.
  - add proper assertions in e2e unit tests to proove it works correctly (no need to have it in every e2e unit test).
  - the step will be removed when Cluster Operator is ready.
  
**Notes**
If the Lifecycle Manager is not ready on the environment, the step which checks the Kyma `.status.state` does not make sense.
Consider defining labels which will be added to the Kyma (plan id/name, global account id, subaccount id, runtime id, hyperscaler etc.)
Question: is the list of provisioning steps valid for the preview plan? EDP, AvS integrations.
We can remove defining (and reading from config maps) overrides when Reconciler is not used (switch to LM).

**Comment by piotrmiskiewicz** [comment]
Which Id should be used as an identifier for Kyma resource. Currently we have following IDs:
- Instance ID
  - provided by BTP. It is not compliant with k8s naming, we can use it after normalization
- Shoot name
  - for own cluster plan - customer provides it so it is not randomly generated
- Runtime ID
 - created in the Compass system. For own cluster it is generated in KEB. This ID is used as an identifier for reconciler.

**Comment by wozniakjan** [comment]
I saw that in https://github.com/kyma-project/control-plane/pull/2181, you use lower case for `runtimeID` and made https://github.com/kyma-project/control-plane/pull/2216 to match that. That sounds like a good idea to me.

**Comment by piotrmiskiewicz** [comment]
The deprovisioning fails, the issue is created: https://github.com/kyma-project/lifecycle-manager/issues/317

**Comment by jakobmoellersap** [comment]
Issue https://github.com/kyma-project/lifecycle-manager/issues/317 closed and verified as fixed.

**Comment by PK85** [comment]
@jakobmoellersap do we have LF on stage environment?

**Comment by PK85** [comment]
@piotrmiskiewicz Enable preview on stage

**Comment by arturskorupa** [comment]
Preview plan does not work on dev any more (no such plan on the list regardless the region used) @PK85

**Comment by jakobmoellersap** [comment]
Stage deployment is finished.

**Comment by PK85** [comment]
@arturskorupa for now you can call KEB directly on dev and preview plan will work.
