### ISSUE TITLE
Lifecycle manager and Kyma Reconciler working together for regular Kyma plans

### ISSUE THREAD

**Issue by arturskorupa** [kyma-project/kyma#15445]
## Description

Regular Kyma plans can use a dual way of reconciliation - `Kyma Reconciler` and `Lifecycle Manager` for operating kyma components on  environments dev, stage and prod.

Detailed description of particular requirements is in attached issues.

## Acceptance Criteria

- [x] Regular plans use both - old reconciler and lifecycle-manager in parallel (requires https://github.com/kyma-project/lifecycle-manager/issues/43) [Q4/2022]
- [x] All existing Dev clusters are configured for a dual way of reconciliation [Q4/2022]
- [x] All existing Stage clusters are configured for 2b's way of reconciliation [9th May]
- [ ] ~~All existing Prod clusters are configured for 2b's way of reconciliation [Q4/2022 - Q2/2023]~~

**Links**
- [Concept document](https://github.com/kyma-project/community/tree/main/concepts/modularization)
- [Transition plan ](https://github.com/kyma-project/community/blob/main/concepts/modularization/transition.md)
- [Lifecycle manager](https://github.com/kyma-project/lifecycle-manager)
- [Module manager](https://github.com/kyma-project/module-manager)

**Comment by tobiscr** [comment]
Depends on https://github.com/kyma-project/kyma/issues/15443

**Comment by PK85** [comment]
@piotrmiskiewicz @janmedrek @tobiscr  please check if below points are fine for you.

Requirements from the KEB point of view:
- [ ] 1) KEB creates an entry in the Reconciler + creates Kyma resource
- [ ] 2) We need to create Kyma resources for all existing SKR instances. Maybe KEB can create them when all kyma instances are upgraded to the new version
- [ ] 3) When a given component is unregistered from Reconciler and registered into Lifecycle Manager, KEB is not affected. KEB still sees that module in the Reconciler (that migrated module always is READY)

**Comment by wozniakjan** [comment]
thanks for the additional context @PK85, I have tried to implement the requested changes in https://github.com/kyma-project/control-plane/pull/2372. Here is a summary for the followup discussion.

> - [ ] 0) enable that functionality via featureFlag

it looks like that flag already exists and was introduced in https://github.com/kyma-project/control-plane/pull/2181 as `APP_LIFECYCLE_MANAGER_INTEGRATION_DISABLED`. LM integration is currently only enabled in DEV and only for the preview plan. The https://github.com/kyma-project/control-plane/pull/2372 changes the feature flag to turn on/off LM integration for all plans (not only for preview plan) 

> - [ ] 1) KEB creates an entry in the Reconciler + creates Kyma resource

implemented by https://github.com/kyma-project/control-plane/pull/2181, https://github.com/kyma-project/control-plane/pull/2216, and https://github.com/kyma-project/control-plane/pull/2372 for `provisioning` and `upgrade_kyma`, also has cleanup in `deprovisioning`

> - [ ] 2) We need to create Kyma resources for all existing SKR instances. Maybe KEB can create them when all kyma instances are upgraded to the new version

https://github.com/kyma-project/control-plane/pull/2372 implements that as part of `upgrade_kyma` operation processing, single `orchestration` operation for all runtimes should do the trick

> - [ ] 3) When a given component is unregistered from Reconciler and registered into Lifecycle Manager, KEB is not affected. KEB still sees that module in the Reconciler (that migrated module always is READY)

additionally, https://github.com/kyma-project/control-plane/pull/2372 introduces a new feature flag `APP_RECONCILER_INTEGRATION_DISABLED` for reconciler integration after LM is fully ready and KEB can phase out reconciler

**Comment by wozniakjan** [comment]
https://github.com/kyma-project/control-plane/pull/2372 merged so I believe we are currently on track

> - [ ] 2) We need to create Kyma resources for all existing SKR instances. Maybe KEB can create them when all kyma instances are upgraded to the new version

^^ remains open, @PK85 suggested that after enabling KEB/LM integration with `APP_LIFECYCLE_MANAGER_INTEGRATION_DISABLED` in each env, `kyma_upgrade` operation triggered on all SKRs should take care of this.

**Comment by szwedm** [comment]
@pbochynski @janmedrek are we ready to enable that on STAGE env ?

**Comment by pbochynski** [comment]
If you ask me: go for it :)
But I believe it is up to @janmedrek.

**Comment by janmedrek** [comment]
I will align with the team and let you know. For sure we won't be able to include any Watcher implementation, but as far as I recon there is no real blocker for now.

I think we also lack the promotion logic between the environments, we could just use any "stable" version of the Managers but then - we don't have any automated updates there.

**Comment by strekm** [comment]
lifecycle manager available on prod is a dependency for Hydra removal from eventing. see more on https://github.com/kyma-project/eventing-auth-manager/issues/1

**Comment by PK85** [comment]
Kyma resource enabled for regular plans on 16 May
