### ISSUE TITLE
Create a feature flag for the new subscription CRD implementation

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#15518]
**Description**

Since the subscription CRD change is a big one and depends on a lot of other components (like busola), we would like to create a feature flag and keep the code working towards the new CRD version disabled behind this feature flag. 

**Reasons**

This helps us to avoid a long living feature branch and to quickly enable the feature when we need it and are ready to deliver it.

**Tasks**

- [ ] Create a feature flag.
- [ ] Create new pkg version (v2) for reconciler and backend.
- [ ] Make sure none of the new features are enabled and eventing works exactly as before.

**Comment by raypinto** [comment]
PR: https://github.com/kyma-project/kyma/pull/15556
