### ISSUE TITLE
Move Connectivity Proxy Reconciler to the Operator framework

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/kyma#15524]
**Description**

We currently use the old reconciler implementation to deploy the Connectivity Proxy in the SKRs. We would like to have a persistent solution that can reduce the effects of potential failure/removal.

The new Operator approach in Kyma that comes with the modularization approach brings a new set of possibilities that will make the maintenance and deployment much more straightforward.

steps:
- SPIKE Investigate implementing custom operator to replace Connectivity Proxy Reconciler      
- Prepare initial repository for the Operator 
- Define a CRD with Connectivity Proxy parameters 
- Implement custom logic installing Connectivity Proxy chart
- Provide testing pipelines

**Reasons**

We want to deliver a stable solution to our customers.

**Acceptance Criteria**
- [ ] New Operator for Connectivity Proxy implemented
- [ ] Operator is able to work inside the SKR cluster
- [ ] Operator deploys the Connectivity Proxy in the cluster if there is a proper ServiceInstance/ServiceBinding available
- [ ] Operator allows the user to configure their own Connectivity Proxy deployment (various proxy standards, ports, etc)
- [ ] In case of failure, status should be manifested

**Comment by franpog859** [comment]
According to [this concept](https://github.com/kyma-project/community/tree/main/concepts/modularization), we move to the modular structure of the whole Kyma. We should move the Connectivity Proxy module this way

I suggest following artifacts for the Connectivity Proxy module:
- `someinternalgithub/kyma/connectivity-proxy-manager` repository generated from `https://github.com/kyma-project/template-repository`
    - `resources/module/` charts of the module, moved from some internal charts repository
    - `resources/operator/` deployment of the operator
    - `resources/crds/operator/` overrides for the module installation
    - `operator/` the source code of the operator inspired by `https://github.com/kyma-incubator/reconciler/tree/main/pkg/reconciler/instances/connectivityproxy`, importing `kyma-project/module-manager` to do the common tasks like rendering and deploying charts
- operator images
- module images from the Docker Hub registry

**Comment by franpog859** [comment]
The knowledge gathering is done in this document - https://someinternalgithub/framefrog/documentation/blob/master/investigations/modularization/connectivity-proxy-operator.md

**Comment by franpog859** [comment]
Things to do:
- [ ] create an internal repository for the Connectivity Proxy Manager
- [ ] move the existing charts into the internal repository
- [ ] define a CRD for the Connectivity Proxy module
- [ ] implement the custom Reconciler logic in the Operator controller
- [ ] test the behavior of the manager
- [ ] provide Prow pipelines to build and test the operator and the module
- [ ] create a README for the manager and the module
- [ ] adjust the ModuleTemplate logic for the internal charts when it's ready to use

**Comment by akgalwas** [comment]
Closing, as the Connectivity Proxy is being implemented as an external module.
