### ISSUE TITLE
Document recommendations for shared Kyma cluster usage

### ISSUE THREAD

**Issue by varbanv** [kyma-project/kyma#15587]
**Description**

Document guidance on how to share a Kyma cluster between different teams.

**Reasons**

Our users have expressed interest in sharing a single cluster between different teams.
While Kubernetes does not provide the necessary isolation to provide effective separation within the cluster, we should provide guidance on best practices and potential pitfalls when attempting to share a cluster.

**Acceptance Criteria**
- [ ] Document recommended configuration for sharing a cluster.
- [ ] Document limitations to how much isolation between teams is possible.
- [ ] Document example scenarios where sharing a cluster is acceptable.

**Links**
[Initial issue](https://jira.tools.sap/browse/BITFRTECHNOLOGY-1225)
[Additional findings](https://github.com/kyma-project/busola/issues/1832)
[Additional findings](https://github.com/SAP-docs/btp-cloud-platform/issues/103)

---
<details>
    <summary>:warning: Funnel process - do not remove!</summary>
    </br>

Name|Value
:--- | :---
theme | Enterprise-grade
business value | 5
technical value | 0
user value | 5
open-source value | 5
effort | 
requested by | 
</details>

**Comment by a-thaler** [comment]
We published an initial version of a cluster sharing guide at SAP help as this relates much more to an actual productized offering, see https://help.sap.com/docs/btp/best-practices/sharing-clusters-in-kyma?locale=en-US&version=Cloud.
Any feedback is welcome, will close the issue.
