### ISSUE TITLE
Metric to calculate number of incoming total requests to the event publisher proxy

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#15680]
**Description**

At the moment, we have the metric `eventing_epp_requests_total` which calculates the total requests from the EPP to the messaging server as documented [here](https://kyma-project.io/docs/kyma/latest/04-operation-guides/operations/evnt-02-eventing-metrics/). We do not have a metric that calculates the total requests to the EPP (pass and fail). 

**Reasons**

It gives an overview of the number of requests entering the EPP.

**Tasks:**

- [ ] Add a new metric
- [ ] Rename the metric `eventing_epp_requests_total` to mention messaging server
- [ ] Check with SRE if the metric `eventing_epp_requests_total` is actually needed or could be calculated using the metric `nats_epp_event_type_published_total` by dropping the labels
- [ ] Follow naming conventions for the new metric
- [ ] Document the metric

**Comment by k15r** [comment]
those metric already exist
