### ISSUE TITLE
Unit tests for JetStream Backend v2

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#15705]
We only have integration tests for [pkg/backend/jetstreamv2/jetstream.go](https://github.com/kyma-project/kyma/blob/main/components/eventing-controller/pkg/backend/jetstreamv2/jetstream.go). The idea of this ticket is to cover the file with unit tests so that we can replace most of the integration tests.
- [ ] Cover the file with unit tests.
- [ ] Remove obsolete integration tests
- [x] cover the TestJetStreamInitialize_NoStreamExists as a unit test([reference](https://github.com/kyma-project/kyma/issues/15706))
- [x] cover the TestJetStreamInitialize_StreamExists as a unit test([reference](https://github.com/kyma-project/kyma/issues/15706))

**Comment by nachtmaar** [comment]
Here some status update as an open task list:

**Tasks for Initialize()**:
- [ ] Test new cases for ensureStreamExistsAndIsConfiguredCorrectly()
- [ ] Get rid of the configProvider ? 
- [ ] Fix integration tests
- [ ] Check coverage again
- [ ] Test restructuring:
  - [ ] Only write happy path tests as white box tests
  - [ ] Write the non happy paths as black box tests


Tests other methods as well (might be covered by some tests already):
- [ ] *SyncSubscription*(subscription *eventingv1alpha2.Subscription) error
- [ ] *DeleteSubscription*(subscription *eventingv1alpha2.Subscription) error
- [ ] *GetJetStreamSubjects*(source string, subjects []string, typeMatching eventingv1alpha2.TypeMatching) []string
- [ ] *DeleteInvalidConsumers*(subscriptions []eventingv1alpha2.Subscription) error
- [ ] *GetJetStreamContext*() nats.JetStreamContext
