### ISSUE TITLE
Kubernetes upgrade from ver 1.23 to 1.24

### ISSUE THREAD

**Issue by zhoujing2022** [kyma-project/kyma#15732]
**Description**
Currently kyma supports k8s `1.23`. As all dependencies are met we can support the next version `1.24`.

Furthermore the support for next version should be prepared by already having a [post-main-k3d-k8s-preview](https://status.build.kyma-project.io/?type=postsubmit&job=post-main-k3d-k8s-preview) pipeline in place to identify problems fast and start addressing them.

**Tasks**
- [x] [k8s update] @TW Pre-Notification to Customers via [What's New](https://help.sap.com/whats-new/cf0cb2cb149647329b5d02aa96303f56?Component=Kyma%2520Runtime&q=Upcoming%2520upgrade%2520to%2520Kubernetes%25201.23&locale=en-US). This Step must be done 4 weeks before Golive on PRD. (Upgrade-Date on PRD: 05.12.-11.12.2022 )
- [x] [k8s update] @kyma-project/jellyfish Verify k8s `1.24` support on k3d (see https://github.com/kyma-project/cli/issues/1409)
- [x] [k8s update] @zhoujing2022  Ensure no deprecated resources exist which will be no longer support on the new K8s cluster (see https://github.com/kyma-project/test-infra/issues/6109)
- [x] [k8s update] @kyma-project/jellyfish  Default version for Kyma CLI is k8s `1.24` (see https://github.com/kyma-project/cli/issues/1409)
- [x] [k8s update] @neighbors Prow jobs are based on k8s `1.24` (see [neighbours issue](https://github.tools.sap/kyma/backlog/issues/3097))
- [x] [k8s update] @neighbors Already existing release jobs (from last release) should be still using old k8s version. (see [neighbours issue](https://github.tools.sap/kyma/backlog/issues/3097))
- [x] [k8s update] @neighbors kyma-upgrade-gardener-kyma2-minor-versions job should be still using old k8s version. (see [neighbours issue](https://github.tools.sap/kyma/backlog/issues/3097))
- [x] [k8s update] @neighbors [Default version for kubectl is `1.24` (Docu, Prow) (see [neighbours issue](https://github.tools.sap/kyma/backlog/issues/3097))
- [x] [k8s update] @TW document new version and add release notes (https://github.com/kyma-project/kyma/pull/16084)
- [x] [k8s update] @neighbors Setup preview job that will verify if kyma can run with k8s`1.24` (next k8s version), create tickets (and link them) for other teams if the pipeline gets red (see [neighbours issue](https://github.tools.sap/kyma/backlog/issues/3097))

**AC:**
- all pipelines are upgraded to k8s `1.24`
- CLI provisioning is adjusted to new versions
- documentation is updated
- migration guide with potential manual actions is ready
- there is one new k3d based pipeline running on k8s 1.24 (next k8s version)

Previous upgrade: https://github.com/kyma-project/kyma/issues/14760

Depends on https://github.com/kyma-project/test-infra/issues/6109

**Comment by a-thaler** [comment]
PSP problems in 1.25 preview plan will be fixed for the observability components by https://github.com/kyma-project/kyma/pull/15744

**Comment by zhoujing2022** [comment]
Asked Maja to add the upgrade pre-notification into the release note of Rel.2.8

**Comment by tobiscr** [comment]
See [ticket on neighbours](https://github.tools.sap/kyma/backlog/issues/3097) side.

**Comment by zhoujing2022** [comment]
Pre-notification over "what'sNew" is planned:
https://help.sap.com/whats-new/cf0cb2cb149647329b5d02aa96303f56?Environment=Kyma&Valid_as_Of=2022-12-05%253A2022-12-05&locale=en-US

**Comment by strekm** [comment]
PSPs owned by goats components were handled in https://github.com/kyma-project/kyma/issues/15916

**Comment by zhoujing2022** [comment]
@Sawthis 
the ReleaseNote 2.9 already contents this notification about the 1.25 upgrade.
