### ISSUE TITLE
Check if the Interest Retention policy works with the Discard policy and Limits values 

### ISSUE THREAD

**Issue by VladislavPaskar** [kyma-project/kyma#15751]
**Description**

The NATS Docs are now updated and claim that the `Interest` retention policy can work in pair with Discard policy, which comes in play after the MaxBytes/Msg threshold is reached. We need to test if that is right. Changing the code and helm is not the part of this ticket.

**Tasks**
- [x] set the Discard/MaxBytes configuration together with Interest Retention Policy
- [x] check if the after reaching the max conf threshold , the discard policy will work (old/new messages should be discarded)
- [ ] create a follow-up in necessary changes, which need to be done

**Implementation Details**
- we can set the new Discard and Limits values using nats cli
- this can also be set in the code

**Comment by VladislavPaskar** [comment]
# Nats discard/maxbytes + interest

**Configuration**

- RetentionPolicy=Interest // Messages are kept as long as there are Consumers on the stream (matching the message's subject if they are filtered consumers) for which the message has not yet been ACKed.
- DiscardPolicy = NEW // which means the new messages get discarded
- MaxBytes = 5000=5kib // upper bounds for the stream, how big the sum of all the messages can be in bytes
- Sink is in-place, but returns 500

<img width="409" alt="Screenshot 2022-10-27 at 16 13 33" src="https://user-images.githubusercontent.com/15933100/199486604-2ca05246-688a-47e4-a64c-6ff20e4af54e.png">

**Tests**

- Created 1 subscription with one evenType
- published 9 messages
- After the 9th:

<img width="595" alt="Screenshot 2022-10-27 at 16 13 08" src="https://user-images.githubusercontent.com/15933100/199486588-dd78d0b3-ec42-4537-bcdc-7212201a5369.png">


NATS stopped to accept new messages.

EPP logs:

```
{"level":"ERROR","timestamp":"2022-10-27T13:47:36Z","logger":"jetstream-handler","caller":"jetstream/jetstream.go:78","message":"Cannot send event to backend","context":{"backend":"nats","jetstream enabled":true,"error":"nats: maximum bytes exceeded"}}
{"level":"ERROR","timestamp":"2022-10-27T13:47:36Z","caller":"handler/handler.go:154","message":"cannot send to stream: nats: maximum bytes exceeded","context":{}}
```

and returned `500 Internal Server Error`.

Once the sink was made **reachable**, the messages were redelivered right away.

**Conclusion**

So, it means, that the `Discard` policy and `maxBytes`(or other maxValues) **do work** in a bundle with `Interest` ****Retention policy.

**Tasks**(_should be moved to a new issue after review_):

- [ ] define the threshold for maxBytes (in absolute or relative value)
- [ ] set the discard policy new and the maxbytes exceeded error and return the 507 error, maybe trigger an alert
- [ ] catch the maxBytes
- [ ] (optional) reduce the error logs in the epp from  two to one

**Comment by raypinto** [comment]
LGTM

**Comment by VladislavPaskar** [comment]
The tasks will be implemented here https://github.com/kyma-project/kyma/issues/15998
