### ISSUE TITLE
Improve the consumer logic in the v1alpha2 JetStream Backend

### ISSUE THREAD

**Issue by VladislavPaskar** [kyma-project/kyma#15818]
**Description**
We want to improve our NATS consumers/subscription flow in the handlers version 2

**Tasks**
- [ ] improve the consumer/subscription creation code
- [ ] propagate the MaxInFlight from the Subscription CR config to the consumer if it got changed
- [ ] add unit tests(use mocks/stubs)
- [ ] improve the error handling
