### ISSUE TITLE
Replace logging component with a tutorial

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#15827]
**Description**
Following the new [Strategy](https://github.com/kyma-project/community/blob/main/concepts/observability-strategy/strategy.md), we don't want to offer a logging component fullfilling enterprise-grade quality as it would require bigger investment and will be always in conflict with solutions by other providers. Instead a well-done tutorial needs to be provided on how to install it on your own.

Actions:
- [x] Have instructions as alternative (https://github.com/kyma-project/kyma/issues/15828)
- [x] Have a blog post (https://github.com/kyma-project/website/pull/901)
- [x] Have release notes (https://kyma-project.io/blog/2022/11/22/release-notes-29/#logging)
- [x] Add deprecation notes to the component documentation (https://github.com/kyma-project/kyma/issues/15893)
- [x] Refactor integration tests to be independent (https://github.com/kyma-project/kyma/issues/17636)
- [x] Wait a defined amount of time, check usage and remove component (https://github.com/kyma-project/kyma/issues/17637)

**Reasons**
The focus of Kyma is not to provide Loki as an enterprise-grade managed offering as part of the cluster stack

**Attachments**

**Comment by a-thaler** [comment]
All is ready for the removal, now it is time to give users the chance to adopt first

**Comment by a-thaler** [comment]
Removal is planned for 2.16

**Comment by a-thaler** [comment]
Actual removal is part of 2.17
