### ISSUE TITLE
Tidy up Application Connector

### ISSUE THREAD

**Issue by franpog859** [kyma-project/kyma#15824]
**Why**

Application Connector is a module that consists of a couple of components. There were a lot of ideas on how to structure it, a lot of changes, renamings, and so on. It's quite cluttered and has quite a bit of legacy code and configuration. To increase the quality of the module and reduce the maintenance effort, we suggest working on it and cleaning it up

**What**

These are the things that should be done:
- [x]  #13977
- [x] #15915 
- [x] #16492
- [x] #16493
- [x] #15974
- [ ] ~Rename `central-*` components as they are now default (5)~
- [ ] Update the documentation
- [ ] Update on-call / support guides and troubleshooting sections of the docs

**Additional information**

It's a part of [the old EPIC](https://github.com/kyma-project/kyma/issues/12353). I believe it's good to have this part separated. The Kyma project/ funnel process values are just copied from the mentioned issue so please, refer to is or revalue them accordingly

---
<details>
    <summary>:warning: Old funnel process - do not remove!</summary>
    </br>

Name|Value
:--- | :---
theme | Technical Debt
business value | 5
technical value | 10
user value | 2
open-source value | 0
effort | 
requested by | 
</details>

**Comment by Disper** [comment]
Application Connector is being removed, and AC module is replacing it, please see https://github.com/kyma-project/kyma/issues/15826
