### ISSUE TITLE
Implement Application Connector Operator

### ISSUE THREAD

**Issue by franpog859** [kyma-project/kyma#15826]
**Why**

According to [this concept](https://github.com/kyma-project/community/tree/main/concepts/modularization), we move to the modular structure of the whole Kyma. We should move also the Application Connector module this way

**What**

Looking at [the current KEDA workplan](https://github.com/kyma-project/kyma/issues/15290) and the proposed example in the concept I suggest this repository structure and the artifacts as the output of this epic:
- `github.com/kyma-project/application-connector-manager` repository generated from `https://github.com/kyma-project/template-repository`
    - `resources/module/` charts of the module, copied from `kyma/resources/application-connector`
    - `resourecs/operator/` deployment of the operator
    - `resources/crds/module/` CRDs of the module, copied from `kyma/installation/resources/crds/application-connector`
    - `resources/crds/operator/` overrides for the module installation
    - `module/` the source code of the whole module, copied from `kyma/tree/main/components/central-application-connectivity-validator`, `kyma/tree/main/components/central-application-gateway` and `kyma/tree/main/components/application-operator`
    - `operator/` the source code of the operator inspired by the base reconciler, importing `kyma-project/module-manager` to do the common tasks like rendering and deploying charts
- operator images
- module images

**Additional information**

It's a part of [the old EPIC](https://github.com/kyma-project/kyma/issues/12353). I believe it's good to have this part separated

**Comment by akgalwas** [comment]
**What**
We must perform the following steps:
- [ ] #15864
- [ ] Update CRD definition to cover all configuration parameters
- [ ] Reconsider chart structure
  - [ ] What degree of configurability is needed? It seems reasonable to allow to disable Istio
  - [ ] Is there some simplification possible?
- [ ] POC productisation
Keep in mind that Application Connector functionality depends on the Istio module.

**Comment by akgalwas** [comment]
We have three areas to test:
- Operator behaviour
- Application Gateway, Application Validator, and Compass Runtime Agent
- Compass Manager logic

We discussed the topic and agreed to use contract testing approach:
- Application Connector Module Operator will be tested separately with some mocked chart. 
- Application Connector components will be tested separately and most functionality will be reused from [existing tests](https://github.com/akgalwas/kyma/tree/main/tests/components/application-connector) (new pipeline will be needed)

**Comment by akgalwas** [comment]
Application Operator Module CRD must contain the following properties:
- `domainName` to be used in Istio Gateway, and Istio Virtual Service
- secret with TLS certificate to be used by Istio Gateway

Both values are optional so Operator must implement fallbacks:
- if secret is not provided, Certificate CR must be created
- if `domainName` is not provided, Gardener's domain must be used
