### ISSUE TITLE
Replace tracing component with a tutorial

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#15852]
**Description**
Following the new [Strategy](https://github.com/kyma-project/community/blob/main/concepts/observability-strategy/strategy.md), we don't want to offer a trace backend fullfilling enterprise-grade quality as it would require bigger investment and will be always in conflict with solutions by other providers. Instead a well-done tutorial needs to be provided on how to install it on your own.

Preconditions:
- [x] Configurable tracing is available (https://github.com/kyma-project/kyma/issues/11231)

Actions:
- [x] Have instructions as alternative (https://github.com/kyma-project/kyma/issues/16389)
- [x] Have a blog post (https://github.com/kyma-project/website/pull/941)
- [x] Deprecate component with release notes (https://github.com/kyma-project/kyma/issues/16390)
- [x] Wait 3 releases and remove component (with Kyma 2.14) (https://github.com/kyma-project/kyma/issues/16584)

**Reasons**
The focus of Kyma is not to provide Jaeger as an enterprise-grade managed offering as part of the cluster stack

**Attachments**

**Comment by a-thaler** [comment]
Still giving the users time to react to the deprecation, will be finalized with 2.14

**Comment by a-thaler** [comment]
The tracing component got removed with Kyma 2.14 and a tutorial on how to install it manual is provided at: https://github.com/kyma-project/examples/tree/main/jaeger
