### ISSUE TITLE
Kyma Serverless managed by its dedicated operator

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#15856]
**Description**

Implement an operator for serverless so that serverless' lifecycle could be managed by the module manager as proposed with modularisation concept.

**AC**
 -  lifecycle|module manager should install the serverless operator.
 -  serverless operator should install serverless workloads, configuration, ui extensions
 -  serverless module can be enabled/disabled in the target runtime by editing the list of modules in the `Kyma` CR
 -  serverless module can be reconfigured by editing `Serverless` CR
 - serverless workloads lifecycle is fully managed by the manager

**Subtasks**
 - [x] scaffold serverless manager in a dedicated repository under `kyma-project` - https://github.com/kyma-project/kyma/issues/15858
 - [x] implement the manager that installs serverless "as-is"
 - [x] implement CI job that would build the serverless manager image
 - [x] implement CI job that would build the serverless module OCI image
 - [x] generate serverless module template 
 - [x] configure UI extensions for serverless views (list/form/details) that will be applied together with serverless by the operator
 - [x] migrate serverless integration tests to run them on modular kyma 
 - [x] implement installation/uninstallation logic for all installation modes (incl. internal.external docker registry)

**Reasons**

Kyma serverless should become one of kyma's building blocks that can be released independently.
User need to be able to uninstall/uninstall/configure serverless  

**Attachments**

https://github.com/kyma-project/community/tree/main/concepts/operator-reconciliation

**Comment by kwiatekus** [comment]
Missing part:
https://github.com/kyma-project/serverless-manager/issues/117
