### ISSUE TITLE
Support for XFF headers

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#15865]
**Description**

Introduce Istio CRD that enables user to configure number of trusted proxy property of Kyma Istio. Configuring mentioned property will enable forwarding client address to workload. 

ACs:
- [ ] Istio CRD proposal
- [ ] APIRule CRD changes proposal
- [ ] shared library implementation
- [ ] istio reconciler supports Istio CR 
- [ ] CRD added and documented in Kyma
- [ ] tutorial explaining Istio configuration
- [ ] tutorial explaining limit access to workload for specific IPs
- [ ] automated e2e test

**Reasons**

Kyma Istio implementation for managed installation does not allow to configure Istio service mesh in a way that client attributes are forwarded to workflow. To forward client address to workload user would need to configure Istio gateway topology number of trusted proxies property in mesh configuration. 
For managed Kyma installations changes applied directly by users would be brought back to default setting by reconciler. We want to introduce simplified and reliable way of applying changes to Kyma Istio by introducing Istio CR as another layer of abstraction.
By forwarding client address to workloads users can limit access to their workloads based on IP address.

**Attachments**
