### ISSUE TITLE
Fluentbit lifecycle managed by telemetry-operator

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#15955]
**Description**
To align much bettter with the future modularization concept, the telemetry-operator should get responsible to manage the lifecycle of the fluentbit daemonset. With that it will become a self-contained operator which can be tested in isolation.

In order to achieve it the following points needs to be done:
- [x] avoid restarts of fluentbit by versioning the config changes (https://github.com/kyma-project/kyma/issues/15956)
- [x] introduce feature flag and deploy simple setup (https://github.com/kyma-project/kyma/issues/16200)
- [x] add support for deletion (https://github.com/kyma-project/kyma/issues/16257)
- [x] remove dummy pipeline from Fluent Bit configuration (https://github.com/kyma-project/kyma/pull/16573)
- [x] extend it to the full setup (like serviceaccount), test migration (assure that it is working e2e), remove sub-chart and feature flag
(https://github.com/kyma-project/kyma/issues/16570)

**Comment by a-thaler** [comment]
Fluenbit is now fully managed by the telemtry-operator
