### ISSUE TITLE
Unsubscribing NATS subscriptions does not delete consumers

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#15978]
**Description**

When we delete kyma subscriptions or modify kyma subscription filters, the underlying NATS subscriptions are unsubscribed which eventually deletes the consumers. 

But if by any chance the NATS subscriptions becomes invalid, then we create a new NATS subscription and **bind** an existing consumer to this subscription. On deletion of this NATS subscription, it does not delete the underlying consumer since we manually bind the consumer and hence it results in dangling consumers.

**Expected result**

Deletion or modification of existing subscription filters should delete the old consumers.

**Actual result**

Deletion or modification of existing subscription filters does not delete the old consumers and we end up with dangling consumers.

**Steps to reproduce**

- Create a kyma subscription with one filter
- The number of NATS consumers should be one
- Restart the NATS server, make sure the reconnects were exhausted and check if [this line](https://github.com/kyma-project/kyma/blob/5cda76fc199c066e71ac43a4ae7f36e8fcb7263f/components/eventing-controller/pkg/backend/nats/jetstream/jetstream.go#L443) of code was called
- The number of NATS consumers should still be one
- Now modify the filter and change the value
- This should create a new consumer and delete the old one
- But there will be two NATS consumers instead of one.

**Tasks**

- [x] Reproduce the issue
- [ ] Fix the bug and write tests
- [ ] Create another function in the controller that will check all the existing consumers and see if they have a corresponding kyma filter(limited to our working stream). If not, delete it
- [ ] Cherry pick this change to 2.8 release

**Comment by muralov** [comment]
There two cases dangling consumers are produced:
* Change subscription CR filter(s) while EC is down
   `Solution`: delete subscription consumers not associated with any of the filters. Consumer should be invalid as it has no subscription

* Change subscription CR filter(s) while NATS JetStream is down
  `Solution`: compare EC subscriptions cache to actual JetStream subscriptions while reconciliation
