### ISSUE TITLE
(POC) knative serving for API exposure using knative gateway controller

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#1598]
**Description**
**After** https://github.com/kyma-project/kyma/issues/1641

Knative serving https://github.com/knative/serving has the functionality to expose applications using istio gateway(they deploy another gateway controller). It exposes services with the namespace in the domain which will have an impact to kyma for example from handling TLS certificates point of view.
During this POC we should : 

- prepare working model based on knative gateway controller.
 This includes : changing virtualservices in the kyma-system to reference knative gateway. 
- change TLS certificate handling, it should match new domain ie. console.kyma-system.$DOMAIN. 
- describe what's need to be changed in the api-controller if serving is used instead
- all changes should be applied based on feature toggle in the helm chart

**Reasons**
In order to make final decision regarding knative adoption to kyma, we need to investigate what impact will have knative components to the kyma. What needs to be changed in the kyma to have knative integrated.

**To be done**
- [x] Create a proposal about how knative integration will be done, in this proposal describe also an alternative (#1643)

- [x] Present proposal on a WG knative-integration meeting

- [x] Migrate current PoC to master. Must be disabled by default (#1845)

- [x] Document how to install kyma with knative from sources

- [x] All the changes in the Virtual Services, in api-controller etc should be applied only when knative is installed, otherwise, it should work on old configuration (#1845)

**Follow up**
* Use multiple certs dynamically #1784 
* Version knative yamls in Kyma #1785

**Comment by sjanota** [comment]
I was able to route traffic to kyma after disabling knative-shared-gateway. Next step: try to make it work with two gateways.

**Comment by sjanota** [comment]
Kyma can be exposed using knative-serving with both fraweworks working as expected. What needs to be changed:
**kyma-gateway**
 * selector needs to be changed to `knative: ingressgateway` (manual)
 * port names need to be changed as http and https are conflicting wiht knative's. [See more](https://preliminary.istio.io/help/ops/traffic-management/deploy-guidelines/#configuring-multiple-tls-hosts-in-a-gateway)
**knative-shared-gateway**
 * TLS needs to be enabled
**istio-ingressgateway**
 * hostPorts are not set in local environment
 * loadBalancerIP is not set in cluster
**knative-ingressgateway**
 * hostPorts are set in local environment
 * loadBalancerIP is set in cluster
Our integration tests also need to use different ingressgateway FQDN, as some of them have the address hardcoded.

**Comment by sjanota** [comment]
Follow up
1. Use multiple certs dynamically
2. Version knative yamls in Kyma

**Comment by tomekpapiernik** [comment]
Created 2 follow-ups: 
- #1895 
- #1896 

The documentation part should be removed from the checklist of this issue.

**Comment by tomekpapiernik** [comment]
Documentation: #1908
