### ISSUE TITLE
Set Discard policy in combination with MaxBytes stream properties to the stream to avoid full storage in NATS

### ISSUE THREAD

**Issue by VladislavPaskar** [kyma-project/kyma#15998]
**Description**

According to the investigation done in https://github.com/kyma-project/kyma/issues/15751, the Discard policy and `maxBytes` properties work together with the currently used Retention policy, which is `Interest`. We can use the combination of these properties to avoid the full storage issues and possible JetStream outage. 

**Tasks**

EC:
- [x] introduce volume size as env var to the ec deployment
- [x] Define the threshold for `maxBytes` read from env (90% of volume size)
- [x] Set the discard policy `NEW` and the `maxBytes` threshold

EPP:
- [x] Catch the error when the `maxBytes` get exceeded and return the  `507 Insufficient Storage` HTTP status to the sender

** bonus tasks **
- Trigger an alert
- Reduce the error logs in the EPP from  two to one in case of error.

**Comment by k15r** [comment]
2nd pr still need approval
