### ISSUE TITLE
run manual tests after upgrade for istio 1.16.x

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#16230]
**Description**
Verify the correctness of Istio deployment and upgrade in 1.16.x by running manual tests.

**Reasons**

Istio bump in kyma

**Attachments**
https://github.com/kyma-project/kyma/issues/16231

**Tests**

`Kyma CLI version: main-1b22c91`

- [x] [[istio test] Access between namespaces](https://github.tools.sap/xf-goat/testing/issues/35)
- [x] [[Upgrade test] Istio reconcilation](https://github.tools.sap/xf-goat/testing/issues/29)
- [x] [Uninstall istio test](https://github.tools.sap/xf-goat/testing/issues/13) --> after running `kyma undeploy --component istio` the dashboards are still present
- [x] [[Upgrade test] Istio downgrade](https://github.tools.sap/xf-goat/testing/issues/9)
- [x] [[Load test] Istio / ORY scaling + reconciliation](https://github.tools.sap/xf-goat/testing/issues/5)

Running for `ALLOW` - ingress gateway gets scaled up to maximum availability (with 10 Pods):

```k6
running (5m00.0s), 000/100 VUs, 1154007 complete and 0 interrupted iterations
default ✓ [======================================] 100 VUs  5m0s
WARN[0300] The flush operation took higher than the expected set push interval. If you see this message multiple times then the setup or configuration need to be adjusted to achieve a sustainable rate.  output=InfluxDBv1 t=1.440268874s

     ✗ SuccessFull calls
      ↳  99% — ✓ 1153999 / ✗ 8

     checks.....................: 99.99%  ✓ 1153999     ✗ 8
     data_received..............: 122 MB  405 kB/s
     data_sent..................: 42 MB   139 kB/s
     http_req_blocked...........: avg=22.71µs min=159ns   med=412ns   max=407.84ms p(90)=499ns   p(95)=539ns
     http_req_connecting........: avg=1.54µs  min=0s      med=0s      max=59.3ms   p(90)=0s      p(95)=0s
     http_req_duration..........: avg=24.67ms min=1.09ms  med=17.09ms max=1.11s    p(90)=52.81ms p(95)=71.91ms
     http_req_failed............: 0.00%   ✓ 8           ✗ 1153999
     http_req_receiving.........: avg=10.74ms min=11.54µs med=3.34ms  max=756.17ms p(90)=30.38ms p(95)=47.47ms
     http_req_sending...........: avg=1.94ms  min=15.06µs med=77.02µs max=564.71ms p(90)=2.69ms  p(95)=8.47ms
     http_req_tls_handshaking...: avg=14.98µs min=0s      med=0s      max=327.97ms p(90)=0s      p(95)=0s
     http_req_waiting...........: avg=11.97ms min=0s      med=8.44ms  max=336.31ms p(90)=25.98ms p(95)=33.25ms
     http_reqs..................: 1154007 3846.485661/s
     iteration_duration.........: avg=25.87ms min=1.19ms  med=17.98ms max=782.58ms p(90)=55.71ms p(95)=75.53ms
     iterations.................: 1154007 3846.485661/s
     vus........................: 100     min=100       max=100
     vus_max....................: 100     min=100       max=100
```
Running for `OAuth2`: IG got scaled to 7 Pods, Oathkeeper to 10 and Hydra to 5 
```k6
running (5m00.5s), 000/100 VUs, 154214 complete and 0 interrupted iterations
default ✓ [======================================] 100 VUs  5m0s

     ✓ SuccessFull calls

     █ setup

     checks.....................: 100.00% ✓ 154214     ✗ 0
     data_received..............: 18 MB   60 kB/s
     data_sent..................: 38 MB   127 kB/s
     http_req_blocked...........: avg=98.18µs  min=197ns   med=454ns    max=459.33ms p(90)=592ns    p(95)=671ns
     http_req_connecting........: avg=18.96µs  min=0s      med=0s       max=110.7ms  p(90)=0s       p(95)=0s
     http_req_duration..........: avg=192.87ms min=10.53ms med=165.03ms max=3.42s    p(90)=308.87ms p(95)=401.5ms
     http_req_failed............: 0.00%   ✓ 0          ✗ 154215
     http_req_receiving.........: avg=4.87ms   min=15.97µs med=414.01µs max=605.71ms p(90)=12.38ms  p(95)=21.4ms
     http_req_sending...........: avg=2.28ms   min=28.66µs med=127.63µs max=473.43ms p(90)=3.56ms   p(95)=9.17ms
     http_req_tls_handshaking...: avg=46.88µs  min=0s      med=0s       max=392.62ms p(90)=0s       p(95)=0s
     http_req_waiting...........: avg=185.71ms min=0s      med=158.08ms max=3.41s    p(90)=299.16ms p(95)=389.04ms
     http_reqs..................: 154215  513.114027/s
     iteration_duration.........: avg=194.52ms min=10.71ms med=166.76ms max=3.42s    p(90)=310.89ms p(95)=404.29ms
     iterations.................: 154214  513.1107/s
     vus........................: 100     min=100      max=100
     vus_max....................: 100     min=100      max=100
```
