### ISSUE TITLE
Istio 1.16 bump

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#16231]
**Description**

Upgrade Istio to 1.16.x.

AC:

- [x] [provision test clusters](https://github.com/kyma-project/kyma/issues/16157)
- [x] [new image available in Kyma external repository](https://github.com/kyma-project/test-infra/issues/6495)
- [x] [istio component chart updated to version 1.16.x](https://github.com/kyma-project/kyma/issues/16229)
- [x] [istio reconciler uses istioctl 1.16.x to install istio 1.16.x](https://github.com/kyma-incubator/reconciler/issues/1250)
- [x] release notes for kyma 2.10
- [x] [run manual tests](https://github.com/kyma-project/kyma/issues/16230)
- [x] [verify that sidecars are injected during reconciliation](https://github.com/istio/istio/issues/40134)
- [x] Update grafana dashboards and verify that they are working
- [x] verify kiali features (huskies)
- [x] verify trace propagation and trace data transport to jaeger (huskies)
- [x] notify monitoring team to verify that metric cardinality has not increased (Envoy metrics) (huskies)

**Reasons**

For security & support reasons we should be up to date with the latest Istio release.

Attachments

https://istio.io/latest/news/releases/1.16.x/announcing-1.16/
