### ISSUE TITLE
Switch flag to use subscription CRD in v1alpha2 version in prod

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#16251]
**Description**

With this ticket, we move from the old (v1alpha1) version of the Subscription CRD to the new version (v1alpha2). We assume by then that the documentation, the busola extensions and the required pipelines are in place.

**Tasks:**

- [x] Add deprecation warning for v1alpha1 api version of the subscription like [here](https://github.com/kyma-project/api-gateway/blob/dcb931520aae83a681cdca34dcf2da90dccfaaed/api/v1alpha1/apiRule_types.go#L57)
- [x] Switch the flag "ENABLE_NEW_CRD" to true in both EPP and EC
   - [x] Make this env default as `true` in the makefiles
- [x] Run `make copy-crds` to update the crds installed by reconciler
- [ ] ~enable testing v1alpha2 in the fast integration jobs~
   - [ ] ~Make `ENABLE_SUBSCRIPTION_V1_ALPHA2` ENV as `true` in fast-integration test. ([link](https://github.com/kyma-project/kyma/blob/af14bbc41274cfc5b450e9aaf48d8ece306fdae0/tests/fast-integration/eventing-test/utils.js#L24))~
   - [x] Instead, we decided to make the v1alpha2 jobs required, as updating this ENV will make the upgrade job fail.
     - PR: https://github.com/kyma-project/kyma/pull/16916
     - Test-infra PR: https://github.com/kyma-project/test-infra/pull/7058
- [X] Talk to Busola about how to synchronize the release (https://github.com/kyma-project/kyma/issues/16620)

AC:
- verify that the new subscription crd is present in the [installation folder](https://github.com/kyma-project/kyma/tree/main/installation/resources/crds) 
- the pipelines introduced `eventing-v1alpha2` and `eventing-upgrade-v1alpha2` are green
- the updated documentation from [here](https://github.com/kyma-project/kyma/issues/16029) is merged
- the busola UI shows the latest subscription and can be reached from the function (sink)

Follow-Up:
https://github.com/kyma-project/kyma/issues/16310

**Attachments**

**Comment by friedrichwilken** [comment]
https://github.com/kyma-project/kyma/pull/16849

**Comment by friedrichwilken** [comment]
[ ] create a follow-up ticket to remove the feature flag

**Comment by raypinto** [comment]
https://github.com/kyma-project/kyma/issues/16310

**Comment by friedrichwilken** [comment]
@raypinto thanks mate! <3
