### ISSUE TITLE
Modularize Logging component

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#16303]
**Description**
The logging component of the kyma project covering the legacy logging features needs to be transformed into a kyma module. The initial plan and details are outlined in https://github.tools.sap/huskies/knowledge-hub/blob/master/modularization/overview.md. This epic will take the initial plan into reality by managing and tracking the actual action items.

**Actions**
- [ ]  Logging chart managed by new operator
- [ ]  Integrate module-manager lib to have module status
- [ ]  Extract module from kyma repo
- [ ]  Transform integration tests - sources and pipelines
- [ ]  Transform upgrade tests
- [ ]  Transform docu
- [ ]  Implement module publishing pipelines

**Comment by a-thaler** [comment]
Instead of modularizing the component, we will try to remove it from the project on time as part of https://github.com/kyma-project/kyma/issues/15827
