### ISSUE TITLE
Replace monitoring component with a tutorial

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#16306]
**Description**
Following the new [Strategy](https://github.com/kyma-project/community/blob/main/concepts/observability-strategy/strategy.md), we don't want to offer a monitoring component fullfilling enterprise-grade quality as it would require bigger investment and will be always in conflict with solutions by other providers. Instead a well-done tutorial needs to be provided on how to install it on your own.

Actions:
- [x] Have instructions as alternative (https://github.com/kyma-project/kyma/issues/15914)
- [x] Have a blog post (https://kyma-project.io/blog/2022/12/9/monitoring-deprecation/)
- [x] Have release notes: https://kyma-project.io/blog/2023/1/17/release-notes-210/#deprecation-of-monitoring
- [x] Add deprecation to component documentation (https://github.com/kyma-project/kyma/issues/16392)
- [X] Wait a defined amount of time, check usage and remove component (https://github.com/kyma-project/kyma/issues/18258)

**Reasons**
The focus of Kyma is not to provide monitoring as an enterprise-grade managed offering as part of the cluster stack

**Attachments**

**Comment by a-thaler** [comment]
Current plan is to remove the component with Kyma 2.20

**Comment by a-thaler** [comment]
Component is removed with Kyma 2.20
