### ISSUE TITLE
Modularize Telemetry component

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#16301]
**Description**
The telemetry component of the kyma project covering the configurable logging and tracing feature needs to be transformed into a kyma module. This epic will take the initial plan into reality by managing and tracking the actual action items.

**Actions**

- [x] Initial Development
  - [x] Fluentbit managed by operator: https://github.com/kyma-project/kyma/issues/15955
  - [x] Extract modules from kyma repo
    - [x] Setup repo (https://github.com/kyma-project/kyma/issues/16745)
    - [x] Switch to new repo (https://github.com/kyma-project/kyma/issues/16745)
    - [x] Move size-exporter and webhook-cert-init component (https://github.com/kyma-project/kyma/issues/16852)
  - [x] Create/generate kustomize files and have basic deployment test (https://github.com/kyma-project/kyma/issues/16909)
  - [x] Remove production profile https://github.com/kyma-project/kyma/issues/16853
  - [x] Integrate module-manager interface to have module status (https://github.com/kyma-project/telemetry-manager/issues/36)
  - [x] Transform component into a module: https://github.com/kyma-project/telemetry-manager/issues/35
  - [x] Implement module release pipelines (https://github.com/kyma-project/telemetry-manager/issues/113)
- [x] Mandatory items for a rollout with test users
  - [x] Test a migration, assure that all resources are covered (https://github.com/kyma-project/kyma/issues/17375)
    - [x] rename base resources (https://github.com/kyma-project/telemetry-manager/issues/144)
    - [x] webhook handling (https://github.com/kyma-project/kyma/issues/16626)
    - [x] copy missing resources (https://github.com/kyma-project/telemetry-manager/issues/150)
  - [x] Migrate documentation (https://github.com/kyma-project/kyma/issues/17468)
  - [x] Namespace-agnostic (https://github.com/kyma-project/kyma/issues/17195)
  - [x] Migrate priorityClass: https://github.com/kyma-project/kyma/issues/17157
  - [x] Deletion logic: https://github.com/kyma-project/kyma/issues/17162
  - [x] Move the loki CR of logging component as a managed object of the telemetry module (https://github.com/kyma-project/kyma/issues/17549)
- [ ] Mandatory items for a productive usage
  - [x] Link to documentation as part of moduleTemplate
  - [x] Namespace scoped module CRD (https://github.com/kyma-project/telemetry-manager/issues/286)
  - [x] Improved release notes (https://github.com/kyma-project/telemetry-manager/issues/287)
  - [x] Advanced status: https://github.com/kyma-project/kyma/issues/17158
  - [ ] Transform integration tests to be based on kustomize and located inside the repo
    - [x] Document the test strategy (https://github.com/kyma-project/telemetry-manager/pull/175)
    - [x] add basic setup (https://github.com/kyma-project/telemetry-manager/pull/44)
    - [x] add basic tracing e2e test (https://github.com/kyma-project/telemetry-manager/issues/57)
    - [x] add missing trace filtering test (https://github.com/kyma-project/telemetry-manager/issues/410)
    - [ ] add missing secret rotation test (https://github.com/kyma-project/telemetry-manager/issues/411)
    - [x] add basic metrics e2e test (https://github.com/kyma-project/telemetry-manager/issues/72)
    - [x] add basic logging e2e test
      - [x] First POC: https://github.com/kyma-project/telemetry-manager/issues/184
      - [x] basic log scenario (https://github.com/kyma-project/telemetry-manager/issues/237)
    - [x] add missing additional logging tests (https://github.com/kyma-project/kyma/issues/18015)
        - [X] Log Parser (https://github.com/kyma-project/telemetry-manager/issues/285)
        - [X] Input (https://github.com/kyma-project/telemetry-manager/issues/285)
    - [X] add istio dependency test
      - [X] Concept (https://github.com/kyma-project/telemetry-manager/issues/261)
      - [x] access log test (https://github.com/kyma-project/telemetry-manager/issues/288)
    - [x] add upgrade test (https://github.com/kyma-project/telemetry-manager/issues/213, https://github.com/kyma-project/telemetry-manager/issues/236)
- [x] Cleanup
  - [x] Remove component docu from kyma repo docs (https://github.com/kyma-project/kyma/pull/18042)
  - [x] Remove fast-integration tests related to telemetry (https://github.com/kyma-project/kyma/issues/18190)
  - [x] Remove telemetry component + CRDs from kyma repo, remove component from component lists (https://github.com/kyma-project/kyma/issues/18190)

**Comment by a-thaler** [comment]
Module fully available and component is removed from kyma repo
