### ISSUE TITLE
Cleanup after the new subscription CRD is on prod

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#16310]
**Description**

Once we have our new subscription CRD in production, we would need to cleanup our codebase to remove all the old/unused/duplicated lava code.

**Tasks**

- [x] Delete the old code (v1alpha1 controllers and backend) but `retain the API folder` since we still support creation of subscriptions in v1alpha1 version.
- [x] Cleanup the common files (test_helpers, utils etc.)
- [x] Get rid of the flag ENABLE_NEW_CRD and use the subscription CRD by default in the new version.
- [x] https://github.com/kyma-project/kyma/issues/16618

**Comment by mfaizanse** [comment]
- [ ] Cleanup
- [ ] Change variable/dir names to remove `v2`
- [ ] Cleanup EPP
- [ ] Cleanup charts from ENV flag
