### ISSUE TITLE
[Epic] Java Runtime

### ISSUE THREAD

**Issue by dbadura** [kyma-project/kyma#16362]
**Description**
Adding java runtime require more than one issue, so let's group it.

**Minimal Requirements**
- [ ] https://github.com/kyma-project/kyma/issues/15825
- [ ] https://github.com/kyma-project/kyma/issues/15660

**Requirements**
- [ ] documentation 

**Additional**
- [ ] graalvm instead of java virtual machine
 

**Known Bugs**
- [ ]  User cannot use custom dependency in Java Runtime

**Comment by dbadura** [comment]
Duplcate: https://github.com/kyma-project/kyma/issues/14357
