### ISSUE TITLE
This is the Checklist/Template for each OS module

### ISSUE THREAD

**Issue by grego952** [kyma-project/kyma#16421]
**Description**
For the new modularization approach, we need documentation that is common for all the modules, e.g. general description (landing page), getting started, module configuration, etc. 

**AC**
- [ ] Your audience is the end-user so the documentation must be written for them (not for the team that builds this module, or other SAP teams that wish to build a module, not for SRE, etc). Remember about the context. How much user knows by now (probably just high level knowledge about Kyma as a whole and that there are modules).
- [ ] The documentation must be consumable by the kyma-project.io home page (split into several information types/md files)
- [ ] Create a docs folder following the standard structure proposed in -> [this issue](https://github.com/kyma-project/kyma/issues/16775)
- [ ] In each module's documentation include:
  - [ ]  General description of the functionality (~if the module is mandatory, mention it!~)
  - [ ]  Getting Started - instructions on how to use the module. The module docs must mention the prerequisite that the module must be enabled ~(don't explain 'how', just link to the generic document we (will) have on how to enable modules in Kyma (see [Adjust the Get Started docs to modular approach](https://github.com/kyma-project/kyma/issues/16778))~ They must also include instructions on how to install/enable a module.
  - [ ] Module configuration
  - [ ] Instructional documents (currently called "dev tutorials" and "operational guides") - must be isolated, i.e. no dependencies on other tutorials or modules. An example of a happy path for the user.
  - [ ] If needed, troubleshooting
  - [ ] Instructions on how to give feedback
  - [ ] CRD autogenerated documentation (if needed)
  - [ ] Markdown Link Check configuration added

**[Status of each module documentation](https://github.com/kyma-project/kyma/issues/17708)**

**[Related decision record](https://github.tools.sap/kyma/community/issues/180)**

**Comment by mmitoraj** [comment]
Closing as the last module was already released.
