### ISSUE TITLE
Refactor EventMesh reconciler integration tests

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#16431]
In this [ticket](https://github.com/kyma-project/kyma/issues/15925), we migrated some of the EventMesh reconciler integration tests to use table-test structure. We should now migrate all the remaining EventMesh reconciler integration tests to this new format. Reason is that the existing tests are not isolated and they are dependent on each other sequentially.

**Tasks:**
- [ ] Migrate the EventMesh [reconciler integration tests](https://github.com/kyma-project/kyma/blob/main/components/eventing-controller/controllers/subscriptionv2/eventmesh/reconciler_integration_test.go) to new [table-tests structure](https://github.com/kyma-project/kyma/blob/main/components/eventing-controller/controllers/subscriptionv2/eventmesh/test/reconciler_integration_test.go).
    - [ ] The tests should be isolated.
    - [ ] The tests should be able to run parallel (`t.Parallel()`)
