### ISSUE TITLE
Fix Busola extension for v1alpha Subscription

### ISSUE THREAD

**Issue by vpaskar** [kyma-project/kyma#16444]
**Description**

The Busola extension for the v1alpha2 was added [here](https://github.com/kyma-project/kyma/issues/15586), but there are still some enhancements to be done, which are currently not possible due to Busola extensions limitations:
- [x] https://github.com/kyma-project/kyma-dashboard/issues/44 - check that this is working
- [x] https://github.com/kyma-project/kyma-dashboard/issues/49 - fill the TypeMatching with the `standard` type per default - [PR](https://github.com/kyma-project/kyma/pull/16502)
- [ ] https://github.com/kyma-project/kyma-dashboard/issues/51 - combine Service and the sink fields into one
- [x] https://github.com/kyma-project/kyma-dashboard/issues/65

**After the release**
- [x] https://github.com/kyma-project/kyma-dashboard/issues/66

**Comment by valentinvieriu** [comment]
@VladislavPaskar pls check the issues above. Most of them are fixed

**Comment by muralov** [comment]
implement fix suggested here to fix the [issue](https://github.com/kyma-project/kyma-dashboard/issues/51) as there is a solution already

**Comment by friedrichwilken** [comment]
The aforementioned issue ( [https://github.com/kyma-project/kyma-dashboard/issues/51](https://github.com/kyma-project/kyma-dashboard/issues/51) )
