### ISSUE TITLE
Kubernetes upgrade from ver 1.24 to 1.25

### ISSUE THREAD

**Issue by zhoujing2022** [kyma-project/kyma#16568]
**Description**
Currently kyma supports k8s `1.24`. As all dependencies are met we can support the next version `1.25`.

Furthermore the support for next version should be prepared by already having a [post-main-k3d-k8s-preview](https://status.build.kyma-project.io/?type=postsubmit&job=post-main-k3d-k8s-preview) pipeline in place to identify problems fast and start addressing them.

**Tasks**
- [x] [k8s update] @TW Pre-Notification to Customers via [What's New](). This Step must be done 4 weeks before Golive on PRD. (Upgrade-Date on PRD: 08.03.-12.03.2023 )
- [x] [k8s update] @zhoujing2022  Ensure no deprecated resources exist which will be no longer support on the new K8s cluster (see https://github.com/kyma-project/test-infra/issues/6109 https://github.com/kyma-project/test-infra/issues/6519)
- [x] [k8s update] @kyma-project/jellyfish  Default version for Kyma CLI is k8s `1.25` (see https://github.com/kyma-project/cli/issues/1555)
- [x] [k8s update] @neighbors Prow jobs are based on k8s `1.25` (see [neighbours issue](https://github.com/kyma-project/test-infra/issues/6740))
- [x] [k8s update] @neighbors Already existing release jobs (from last release) should be still using old k8s version. (see [neighbours issue](https://github.com/kyma-project/test-infra/issues/6740))
- [x] [k8s update] @neighbors kyma-upgrade-gardener-kyma2-minor-versions job should be still using old k8s version. (see [neighbours issue](https://github.com/kyma-project/test-infra/issues/6740))
- [x] [k8s update] @neighbors [Default version for kubectl is `1.25` (Docu, Prow) (see [neighbours issue](https://github.com/kyma-project/test-infra/issues/6740))
- [x] [k8s update] @TW document new version and add release notes ()
- [x] [k8s update] @neighbors Setup preview job that will verify if kyma can run with k8s`1.26` (next k8s version), create tickets (and link them) for other teams if the pipeline gets red (see [neighbours issue](https://github.com/kyma-project/test-infra/issues/6740))

**AC:**
- all pipelines are upgraded to k8s `1.25`
- CLI provisioning is adjusted to new versions
- documentation is updated
- migration guide with potential manual actions is ready
- there is one new k3d based pipeline running on k8s 1.25 (next k8s version)

Previous upgrade: https://github.com/kyma-project/kyma/issues/15732

Depends on https://github.com/kyma-project/test-infra/issues/6109

**Comment by zhoujing2022** [comment]
Pre-Notification is going out.
