### ISSUE TITLE
Eventing with EventMesh is Broken After v1alpha2 Upgrade

### ISSUE THREAD

**Issue by muralov** [kyma-project/kyma#16599]
**Description**

Eventing with EventMesh is broken after upgrading Kyma to v1alpha2. That is published events are not delivered to a sink.

**Expected result**

events sent with backend Event Mesh should be received as it worked for v1alpha1

**Actual result**

events sent with backend Event Mesh are not being received

**Steps to reproduce**

1. Install Kyma with v1alpha1
2. Create the following subscription and follow the [steps](https://github.tools.sap/skydivingtunas/how-to/blob/master/perform-in-cluster-e2e-test.md) to create a function and test whether they are working:
```
cat << EOF | kubectl apply -f -
apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: test-noapp
  namespace: tunas-testing
spec:
  filter:
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.noapp.order.created.v1
    - eventSource:
        property: source
        type: standard
        value: ""
      eventType:
        property: type
        type: standard
        value: sap.kyma.custom.test-app.order.created.v1
  protocol: ""
  protocolsettings: {}
  sink: http://test.tunas-testing.svc.cluster.local/
EOF
```
4. (Optional) You may switch the backend to Event Mesh and test first.
5. Upgrade Kyma to v1alpha2 with the following command, for example:
```
$ export ENABLE_NEW_CRD_VERSION=true && make copy-crds
$ kyma deploy ... --value eventing.controller.enableNewCRDVersion=true
```
6. If backend is not changed to Event Mesh change to it
7. Send a legacy or CE event from the v1alpha1 [steps](https://github.tools.sap/skydivingtunas/how-to/blob/master/perform-in-cluster-e2e-test.md)

**Troubleshooting**
Some errors from the Eventing Controller log:
```
{"level":"ERROR","timestamp":"2023-01-18T16:55:56Z","logger":"event-mesh-handler","caller":"eventmesh/eventmesh.go:157","message":"Failed to handle create EventMesh subscription","context":{"kind":"Subscription","version":4,"namespace":"tunas-testing","name":"test-noapp","error":"failed to get subscription from EventMesh: create subscription failed: 400; 400 Bad Request;{\"error\":{\"code\":\"INVALID_CE_TYPE\",\"message\":\"DomainNamespace segment of Type attribute does not comply with SAP Event Specification\"}}"}}
{"level":"ERROR","timestamp":"2023-01-18T16:55:56Z","caller":"controller/controller.go:326","message":"Reconciler error","context":{"controller":"eventMesh-subscription-reconciler","object":{"name":"test-noapp","namespace":"tunas-testing"},"namespace":"tunas-testing","name":"test-noapp","reconcileID":"bed10dc4-7836-4885-b4ae-7185663914d5","error":"failed to get subscription from EventMesh: create subscription failed: 400; 400 Bad Request;{\"error\":{\"code\":\"INVALID_CE_TYPE\",\"message\":\"DomainNamespace segment of Type attribute does not comply with SAP Event Specification\"}}"}}
{"level":"ERROR","timestamp":"2023-01-18T16:55:57Z","logger":"event-mesh-handler","caller":"eventmesh/eventmesh.go:157","message":"Failed to handle create EventMesh subscription","context":{"kind":"Subscription","version":4,"namespace":"tunas-testing","name":"test-noapp","error":"failed to get subscription from EventMesh: create subscription failed: 400; 400 Bad Request;{\"error\":{\"code\":\"INVALID_CE_TYPE\",\"message\":\"DomainNamespace segment of Type attribute does not comply with SAP Event Specification\"}}"}}
{"level":"ERROR","timestamp":"2023-01-18T16:55:57Z","caller":"controller/controller.go:326","message":"Reconciler error","context":{"controller":"eventMesh-subscription-reconciler","object":{"name":"test-noapp","namespace":"tunas-testing"},"namespace":"tunas-testing","name":"test-noapp","reconcileID":"71c41249-071d-4869-b853-da3eebd5ee8f","error":"failed to get subscription from EventMesh: create subscription failed: 400; 400 Bad Request;{\"error\":{\"code\":\"INVALID_CE_TYPE\",\"message\":\"DomainNamespace segment of Type attribute does not comply with SAP Event Specification\"}}"}}
{"level":"ERROR","timestamp":"2023-01-18T16:55:58Z","logger":"event-mesh-handler","caller":"eventmesh/eventmesh.go:157","message":"Failed to handle create EventMesh subscription","context":{"kind":"Subscription","version":4,"namespace":"tunas-testing","name":"test-noapp","error":"failed to get subscription from EventMesh: create subscription failed: 400; 400 Bad Request;{\"error\":{\"code\":\"INVALID_CE_TYPE\",\"message\":\"DomainNamespace segment of Type attribute does not comply with SAP Event Specification\"}}"}}
{"level":"ERROR","timestamp":"2023-01-18T16:55:58Z","caller":"controller/controller.go:326","message":"Reconciler error","context":{"controller":"eventMesh-subscription-reconciler","object":{"name":"test-noapp","namespace":"tunas-testing"},"namespace":"tunas-testing","name":"test-noapp","reconcileID":"7c0df978-366d-442a-99f4-a5a69a3a6e34","error":"failed to get subscription from EventMesh: create subscription failed: 400; 400 Bad Request;{\"error\":{\"code\":\"INVALID_CE_TYPE\",\"message\":\"DomainNamespace segment of Type attribute does not comply with SAP Event Specification\"}}"}}
{"level":"ERROR","timestamp":"2023-01-18T16:56:01Z","logger":"event-mesh-handler","caller":"eventmesh/eventmesh.go:157","message":"Failed to handle create EventMesh subscription","context":{"kind":"Subscription","version":4,"namespace":"tunas-testing","name":"test-noapp","error":"failed to get subscription from EventMesh: create subscription failed: 400; 400 Bad Request;{\"error\":{\"code\":\"INVALID_CE_TYPE\",\"message\":\"DomainNamespace segment of Type attribute does not comply with SAP Event Specification\"}}"}}
{"level":"ERROR","timestamp":"2023-01-18T16:56:01Z","caller":"controller/controller.go:326","message":"Reconciler error","context":{"controller":"eventMesh-subscription-reconciler","object":{"name":"test-noapp","namespace":"tunas-testing"},"namespace":"tunas-testing","name":"test-noapp","reconcileID":"5f280e73-8946-4541-84c7-f38a9cb0cec0","error":"failed to get subscription from EventMesh: create subscription failed: 400; 400 Bad Request;{\"error\":{\"code\":\"INVALID_CE_TYPE\",\"message\":\"DomainNamespace segment of Type attribute does not comply with SAP Event Specification\"}}"}}
{"level":"ERROR","timestamp":"2023-01-18T16:56:06Z","logger":"event-mesh-handler","caller":"eventmesh/eventmesh.go:157","message":"Failed to handle create EventMesh subscription","context":{"kind":"Subscription","version":4,"namespace":"tunas-testing","name":"test-noapp","error":"failed to get subscription from EventMesh: create subscription failed: 400; 400 Bad Request;{\"error\":{\"code\":\"INVALID_CE_TYPE\",\"message\":\"DomainNamespace segment of Type attribute does not comply with SAP Event Specification\"}}"}}
{"level":"ERROR","timestamp":"2023-01-18T16:56:06Z","caller":"controller/controller.go:326","message":"Reconciler error","context":{"controller":"eventMesh-subscription-reconciler","object":{"name":"test-noapp","namespace":"tunas-testing"},"namespace":"tunas-testing","name":"test-noapp","reconcileID":"37efc85a-1a10-4927-96ab-ce7925d4dc1b","error":"failed to get subscription from EventMesh: create subscription failed: 400; 400 Bad Request;{\"error\":{\"code\":\"INVALID_CE_TYPE\",\"message\":\"DomainNamespace segment of Type attribute does not comply with SAP Event Specification\"}}"}}
{"level":"ERROR","timestamp":"2023-01-18T16:56:16Z","logger":"event-mesh-handler","caller":"eventmesh/eventmesh.go:157","message":"Failed to handle create EventMesh subscription","context":{"kind":"Subscription","version":4,"namespace":"tunas-testing","name":"test-noapp","error":"failed to get subscription from EventMesh: create subscription failed: 400; 400 Bad Request;{\"error\":{\"code\":\"INVALID_CE_TYPE\",\"message\":\"DomainNamespace segment of Type attribute does not comply with SAP Event Specification\"}}"}}
{"level":"ERROR","timestamp":"2023-01-18T16:56:16Z","caller":"controller/controller.go:326","message":"Reconciler error","context":{"controller":"eventMesh-subscription-reconciler","object":{"name":"test-noapp","namespace":"tunas-testing"},"namespace":"tunas-testing","name":"test-noapp","reconcileID":"41edade6-0c68-4da6-9500-4f56551b253c","error":"failed to get subscription from EventMesh: create subscription failed: 400; 400 Bad Request;{\"error\":{\"code\":\"INVALID_CE_TYPE\",\"message\":\"DomainNamespace segment of Type attribute does not comply with SAP Event Specification\"}}"}}
{"level":"ERROR","timestamp":"2023-01-18T16:56:36Z","logger":"event-mesh-handler","caller":"eventmesh/eventmesh.go:157","message":"Failed to handle create EventMesh subscription","context":{"kind":"Subscription","version":4,"namespace":"tunas-testing","name":"test-noapp","error":"failed to get subscription from EventMesh: create subscription failed: 400; 400 Bad Request;{\"error\":{\"code\":\"INVALID_CE_TYPE\",\"message\":\"DomainNamespace segment of Type attribute does not comply with SAP Event Specification\"}}"}}
{"level":"ERROR","timestamp":"2023-01-18T16:56:36Z","caller":"controller/controller.go:326","message":"Reconciler error","context":{"controller":"eventMesh-subscription-reconciler","object":{"name":"test-noapp","namespace":"tunas-testing"},"namespace":"tunas-testing","name":"test-noapp","reconcileID":"23ad29a6-d52e-415a-b272-7d1018d17028","error":"failed to get subscription from EventMesh: create subscription failed: 400; 400 Bad Request;{\"error\":{\"code\":\"INVALID_CE_TYPE\",\"message\":\"DomainNamespace segment of Type attribute does not comply with SAP Event Specification\"}}"}}
```

**Comment by mfaizanse** [comment]
**Solution:**
In the conversion webhook, cleanup the event types from non-alphanumeric characters as per `v1alpha1` specifications.

**Comment by mfaizanse** [comment]
Also, check about the exceeding the limit of 7 segments in case of eventmesh???

**Comment by mfaizanse** [comment]
**Tasks:**
- [ ] In the conversion webhook from `v1alpha1` to `v1alpha2`, do:
   - [ ] Cleanup the event types from non-alphanumeric characters as per `v1alpha1` specifications.
   - [ ] Merge the segments in event types, if they exceed the limit as done already in `v1alpha1` subscriptions.
