### ISSUE TITLE
Cleanup `source` in Subscription v1alpha2 CR

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#16640]
The `source` field in Subscription v1alpha2 CRD is referred to as a URI Ref, instead of a string in CloudEvents SDK, meaning that not all the characters are allowed in the source field. 

If you try to set the source with not-allowed characters in CloudEvent object, then it will not update the source and also it will not return any error. 

In case of JetStream, we need to clean the `source` as per URI path allowed characters specifications.
In case of EventMesh, we are already doing intense cleanup, so no need to update here.

**Tasks:**
- [ ] Clean the `source` as per URI path allowed characters specifications in JetStream in Eventing controller.
- [ ] Update the cleanup reference in EPP.
- [ ] Add a test case for it in EC and EPP.

**Comment by k15r** [comment]
https://github.com/cloudevents/spec/blob/main/cloudevents/spec.md#source-1

**Comment by raypinto** [comment]
From our discussion we will:

- [ ] Not set source for the cloud event (since its not required)
- [ ] Validate the cloud event after setting all the fields
- [ ] In the EC, use the Cloud event validator in the validation webhook
