### ISSUE TITLE
Release management: additional open points

### ISSUE THREAD

**Issue by zhoujing2022** [kyma-project/kyma#16658]
- [ ] Communication Strategy: Kyma need a central platform for the different communications to customer. A Draft: https://wiki.one.int.sap/wiki/display/kyma/Communication+approach
- [x] Automation breaking change process. current process: https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=3185391214
- [x] How to work with standard delivery tasks in Sirius: the idea is, that all release master only need work with a MD-Template instead of working with Sirius directly. Draft: https://wiki.one.int.sap/wiki/display/kyma/Delivery+checklist+for+release+master+and+product+owner
- [x] How to delivery ReleaseNote of the different modules. Can we combine it with ChangeLogs? Is there a way to automate this process?
- [ ] Which regular meetings will be necessary for Release Manager.
- [ ] Evaluation of the initial Keda release. Improvement review.
