### ISSUE TITLE
Refactor Eventing fast-integration tests to get rid of last order function

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#16840]
The eventing fast-integration tests currently deploying alot of extra resources which are not even used in the actual tests anymore e.g. commerce-mock app etc. Also, the tests are using the last-order function which is used by other component tests and its complex to debug. It would be better to get rid of the last-order function and replace it will a simple function for now, which we can later also deploy as a individual pod instead of a kyma function.

**Tasks:**
- [x] Get rid of the last-order function for event delivery and tracing tests.
   - [x] Covered in PR: https://github.com/kyma-project/kyma/pull/16832
- [x] Refactor the monitoring tests to use new event delivery tests.
   - [x] Covered in PR: https://github.com/kyma-project/kyma/pull/16861
- [x] Get rid of the last-order function in JetStream at-least once delivery check test. (i.e. `testJetStreamAtLeastOnceDelivery()`)
   - [x] `testJetStreamAtLeastOnceDelivery()` tests are removed by PR: https://github.com/kyma-project/kyma/pull/16896
- [x] Add tests for `exact` type matching in eventing-sink flow.
   - [x] Covered by: https://github.com/kyma-project/kyma/pull/16921
- [x] Update `streamNotRecreted` and `consumerNotRecreated` tests to not depend on lastorder function.
   - [x] Covered in PR: https://github.com/kyma-project/kyma/pull/16942
- [x] Add a documentation for eventing-sink function. (how to use it)
   - [x] PR: https://github.com/kyma-project/kyma/pull/16946
- [x] Cherry-pick some changes to release-2.11 branch.
   - [x] PR: https://github.com/kyma-project/kyma/pull/16930
- [x] Remove the old eventing tests suit along with last-order function deployment.
   - [x] PR: https://github.com/kyma-project/kyma/pull/17052
   - [x] Cherry-pick PR to release branch: https://github.com/kyma-project/kyma/pull/17105

**Comment by mfaizanse** [comment]
Blocked until new release with v1alpha2 enabled is created. Then we can cleanup all the last-order based tests.
