### ISSUE TITLE
Verify subscription v1alpha2 (as is on main) works with Busola.

### ISSUE THREAD

**Issue by friedrichwilken** [kyma-project/kyma#16984]
**Pre-requisite:**
- [x] PR: https://github.com/kyma-project/kyma-dashboard/pull/155
- [x] New Busola version is released including this PR.

**Tasks:**
- [x] Verify subscription v1alpha2 (as is on `main`) works with Busola.
  - Open Issues related to busola: 
  - [x] BLOCKED: https://github.com/kyma-project/kyma/issues/16929
  - [x] BLOCKED https://github.com/kyma-project/kyma/pull/16922
  - [x] https://github.com/kyma-project/kyma/issues/16501
  - [x] BLOCKED https://github.com/kyma-project/kyma/issues/16620

**Comment by friedrichwilken** [comment]
Check if there is new version of Busola and, if so, verify that this works now.

**Comment by friedrichwilken** [comment]
Is this related? https://github.com/kyma-project/kyma/pull/17612

**Comment by grischperl** [comment]
Creating a subscription (type matching standard and exact and using multiple types) with the Busola UI creates the expected subscription with the version `v1alpha2`
