### ISSUE TITLE
Istio 1.17 bump

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#16993]
**Description**

Upgrade Istio to 1.17.x.

AC:

- [x] [provision test clusters](https://github.com/kyma-project/kyma/issues/16812)
- [x] new image available in Kyma external repository
- [x] [istio component chart updated to version 1.17.x](https://github.com/kyma-project/kyma/issues/16994)
- [x] [istio reconciler uses istioctl 1.17.x to install istio 1.17.x](https://github.com/kyma-incubator/reconciler/issues/1309)
- [x] [bump Istio in Istio module](https://github.com/kyma-project/istio/issues/105)
- [x] release notes for kyma 2.13
- [x] [run manual tests](https://github.com/kyma-project/kyma/issues/16995)
- [x] Update grafana dashboards and verify that they are working
- [x] verify kiali features (huskies)
- [x] verify trace propagation and trace data transport to jaeger (huskies)
- [x] notify monitoring team to verify that metric cardinality has not increased (Envoy metrics) (huskies)

**Reasons**

For security & support reasons we should be up to date with the latest Istio release.

Attachments

https://istio.io/latest/news/releases/1.17.x/announcing-1.17/
https://github.com/kyma-project/test-infra/blob/main/development/image-syncer/external-images.yaml
