### ISSUE TITLE
run manual tests after upgrade for istio 1.17.x

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#16995]
**Description**
Verify the correctness of Istio deployment and upgrade in 1.17.1 by running manual tests.

**Reasons**

Istio bump in kyma

**Attachments**
https://github.com/kyma-project/kyma/issues/16993

**Tests**

- [x] [Access between namespaces manual test](https://github.tools.sap/xf-goat/testing/issues/35) --> @barchw
- [x] [Istio reconcilation](https://github.tools.sap/xf-goat/testing/issues/29) --> @barchw
- [x] [Uninstall istio test](https://github.tools.sap/xf-goat/testing/issues/13) --> @barchw
~~- [ ] Istio downgrade~~ - Not applicable
- [x] Performance test - running https requests against httpbin:
  * No sidecar ![Image](https://user-images.githubusercontent.com/103247439/225327496-f42d719d-da20-47cf-974c-fef660cfbd7e.png)
  * With sidecar ![Image](https://user-images.githubusercontent.com/103247439/225327725-93a5b581-ed72-4a6b-9776-eb63c23c03a4.png)

  * [Grafana Snapshot - Requests without sidecar](https://snapshots.raintank.io/dashboard/snapshot/Z5Q6zAk5DmFZr9wAG4km4BwMUlMP53tD)
  * [Grafana Snapshot - Requests with sidecar](https://snapshots.raintank.io/dashboard/snapshot/34KjZsVBaFmVnb70sthMV0HxVzkFEbm0)
