### ISSUE TITLE
Kubernetes upgrade from ver 1.25 to 1.26

### ISSUE THREAD

**Issue by zhoujing2022** [kyma-project/kyma#17018]
**Description**
Currently kyma supports k8s `1.25`. As all dependencies are met we can support the next version `1.26`.

SRE k8s upgrade plan: https://wiki.one.int.sap/wiki/display/kyma/Kubernetes+releases

Furthermore the support for next version should be prepared by already having a [post-main-k3d-k8s-preview](https://status.build.kyma-project.io/?type=postsubmit&job=post-main-k3d-k8s-preview) pipeline in place to identify problems fast and start addressing them.

**Tasks**
- [x] [k8s update] @TW Pre-Notification to Customers via [What's New](). This Step must be done 4 weeks before Golive on PRD. (Upgrade-Date on PRD: 12.08.-13.08.2023 )
- [x] ask every team about the impact from [Kubernetes Removals, Deprecations, and Major Changes in 1.26](https://kubernetes.io/blog/2022/11/18/upcoming-changes-in-kubernetes-1-26/) and link every relevant changes in this ticket.
- [x] [k8s update] @zhoujing2022  Ensure no deprecated resources exist which will be no longer support on the new K8s cluster (https://github.tools.sap/kyma/backlog/issues/4096)
- [x] [k8s update] @kyma-project/jellyfish  Default version for Kyma CLI is k8s `1.26` ( https://github.com/kyma-project/cli/issues/1689)
- [x] [k8s update] @neighbors Prow jobs are based on k8s `1.26` (see [neighbours issue](https://github.com/kyma-project/test-infra/issues/7190))
- [x] [k8s update] @neighbors Already existing release jobs (from last release) should be still using old k8s version. (see [neighbours issue](https://github.com/kyma-project/test-infra/issues/7190))
- [x] [k8s update] @neighbors kyma-upgrade-gardener-kyma2-minor-versions job should be still using old k8s version. (see [neighbours issue](https://github.com/kyma-project/test-infra/issues/7190))
- [x] [k8s update] @neighbors [Default version for kubectl is `1.26` (Docu, Prow) (see [neighbours issue](https://github.com/kyma-project/test-infra/issues/7190))
- [x] [k8s update] @TW document new version and add release notes (https://github.com/kyma-project/kyma/pull/)
- [x] [k8s update] @neighbors Setup preview job that will verify if kyma can run with k8s`1.27` (next k8s version), create tickets (and link them) for other teams if the pipeline gets red (see [neighbours issue](https://github.com/kyma-project/test-infra/issues/7190))
- [x] @huskies update kube-state-metrics (https://github.com/kyma-project/kyma/pull/17058)

**AC:**
- all pipelines are upgraded to k8s `1.26`
- CLI provisioning is adjusted to new versions
- documentation is updated
- migration guide with potential manual actions is ready
- there is a new k3d based pipeline running on k8s 1.27  for preview purposes

The list of pre-tasks:
(POs analyze  [Kubernetes Removals, Deprecations, and Major Changes in 1.26](https://kubernetes.io/blog/2022/11/18/upcoming-changes-in-kubernetes-1-26/) and create/add the issues below. These Issues must be released before 30.07.2023 on PRD.)
No Update from the teams.
|Teams|Issues|
| ---- | ---- | 
|None | |

Previous upgrade: https://github.com/kyma-project/kyma/issues/16568

Depends on https://github.com/kyma-project/test-infra/issues/6109

**Comment by janmedrek** [comment]
As for the CLI, the following ticket needs to be resolved: https://github.com/kyma-project/cli/issues/1609
This is on top of our backlog list.

**Comment by zhoujing2022** [comment]
Upgrade timeline: # 3687

**Comment by zhoujing2022** [comment]
@janmedrek As I mentioned in the chat, pls create the ticket for task 4 above, and link it here. Thank you

**Comment by zhoujing2022** [comment]
@Sawthis: Besides the tasks 3 and 4, you can already mark the remaining tasks for Neighbors as "Done", right?

**Comment by Sawthis** [comment]
@zhoujing2022 yes, marked as done.
