### ISSUE TITLE
[Telemetry] Support for multiple trace and metric pipelines

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#17223]
**Description**
Using the new gateways for traces and metrics as integration layer, a typical use case is to start filtering and dispatching data to multiple outputs, like a local in-cluster solution for ephemeral and short-term storage keeping all data and a long-term outer-cluster storage for specific data.
At the moment the gateways are supporting a single output only as we decided to start simple with the first version. Any other number then 1 will change the technical design quite a lot, also a typical max amount is around 2-3 instances. So we should increase the limit to have the technical design ready for the future and cover more use case.

**Actions**
- [x] switch ownerReference mechanism (https://github.com/kyma-project/kyma/issues/17232)
- [x] Understand the resource consumptions profile for a pipeline (https://github.com/kyma-project/kyma/issues/17233)
- [x] adjust config generation to be sourced by multiple pipelines (https://github.com/kyma-project/kyma/issues/17234)
- [x] adjust approach to decline pipelines when reaching specific amount (https://github.com/kyma-project/telemetry-manager/pull/126)
- [x] propose and verify new scalability profile (https://github.com/kyma-project/kyma/issues/17377)
- [ ] Enable pipeline usage metrics (https://github.com/kyma-project/kyma/issues/17002)
- [x] Adjust otel-collector grafana dashboards to have metrics per instance visualized (https://github.com/kyma-project/kyma/issues/17377)
- [x] Activate support for multiple pipeline with adjusted resource consumption profile (https://github.com/kyma-project/kyma/issues/17377)
- [x] Activate multiple replicas for trace collector to cover HA (https://github.com/kyma-project/kyma/issues/17377)

**Criteria**
- I can have more then one Metric and Trace pipeline
- Limitation docu is verified
- Two pipelines are using individual pipelines in the otel-config, Using same receivers but own processors and outputs
- It is assured that blocking of one pipeline (unavailable backend) will not harm the other pipeline
