### ISSUE TITLE
[Telemetry] Testing Strategy for telemetry manager

### ISSUE THREAD

**Issue by ameteiko** [kyma-project/kyma#17221]
# Kyma Telemetry Testing Strategy

## Codestyle

<details>
  <summary> Codestyle linters</summary>
  
  ### Linters
  * Declaration order `decorder`, `grouper`
  * Naming `errname`, `forbidigo`, `goprintffuncname`, `musttag`, `varnamelen`, `tagliatelle`, `nosprintfhostport`
  * Error handling `errorlint`, `goerr113`
  * Global variables `gochecknoglobals`
  * Magic numbers `goconst`, `gomnd`
  * Spelling and leftovers `godot`, `godox`
  * Empty lines and whitespaces `gofumpt`, `gosimple`, `lll `, `whitespace`, `wsl`
  * Returns `nakedret`, `nilerr`, `nilnil`, `nlreturn`
  * Other `nestif`, `noctx`, `prealloc`, `tenv`, `thelper`, `durationcheck`, `gocritic`

  ### Action items:
  - [ ] Configure the linters
  - [ ] Brainstorm code-style implications
  - [ ] Document code-style agreements
  - [ ] Fix codestyle problems

</details>

<details>
  <summary>Code semantics and dependencies</summary>
  
  ### Linters
  * interfaces `ireturn`, `interfacebloat`
  * shadowing,  assignment and type errors `predeclared`, `reassign`, `unconvert`
  * testing improvements `testpackage`, `paralleltest`, `tparallel`, `thelper`
  * naming `varnamelen`
  * errors wrapping `wrapcheck`
  * context misuse `containedctx`, `contextcheck`
  * dependencies management `depguard`, `gomodguard`, `importas`

  ### Action items:
  - [ ] Configure the linters
  - [ ] Brainstorm code-style implications
  - [ ] Document code-style agreements
  - [ ] Fix codestyle problems

</details>

<details>
  <summary> Code complexity linters</summary>
  
  ### Linters
  * `cyclop`
  * `funlen`
  * `gocognit`
  * `maintidx`

  ### Action items:
  - [ ] Configure the linters
  - [ ] Brainstorm code complexity expectations
  - [ ] Document agreements from brainstorming
  - [ ] Refactor the codebase to confirm the reached agreements

</details>

## Code review
... Coming soon

## Testing

- [ ] Collect and visualise code-coverage metrics

## CI/CD

- [ ] Move code linting to the GitHub action
- [ ] _[SPIKE]_ Research possibilities to preserve linting and code-coverage metrics to fail the CI stages in cases of metric degradation and not on a specific threshold value.

**Comment by a-thaler** [comment]
Not all aspects are covered but we decided to not process them as one epical goal but try to process on them step-by-step as part of the continuous improvments
