### ISSUE TITLE
Use `Patch` request to update EventMesh subscriptions Webhook Auth in Eventing controller

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#17370]
**Context:**
Currently, whenever we have to update the eventMesh subscriptions, we delete and re-create the subscription on EventMesh server. Idea: we can use the `PATCH` request to update instead of deleting and re-creating!!!

**Description**
In order to update the client credentials used by event mesh we need to implement a PATCH request as documented here:
[https://api.sap.com/api/SAPEventMeshDefaultCredentialsAPIs/resource/Webhook_Credentials_Management](https://api.sap.com/api/SAPEventMeshDefaultEventingAPIs/path/patch_events_subscriptions__subscriptionName_)

**Tasks:**
- [x] Update EventMesh mock to support `PATCH` requests.
- [x] use the PATCH request to update instead of deleting and re-creating eventMesh subscriptions.
- [x] Add integrations tests to verify.
- [x] Decide if a test is needed at fast-integration level (added https://github.com/kyma-project/kyma/issues/17797).

**Acceptance**
- [x] We can update EventMesh subscription without deleting it.
- [x] existing webhooks can be updated to use a new set of credentials

**Comment by mfaizanse** [comment]
Blocked!

We are using `POST /events/subscriptions` API and we want to provide the name of `webhook-credentials` which we created using [these APIs](https://api.sap.com/api/SAPEventMeshDefaultCredentialsAPIs/resource/), is it supported?

**Comment by mfaizanse** [comment]
Unblocked!

- Here is the documentation for currently used API: `POST /events/subscriptions`

**Comment by mfaizanse** [comment]
Use [these](https://api.sap.com/api/SAPEventMeshDefaultEventingAPIs/resource/Webhook_Subscriptions_to_Cloud_Events) APIs to:
1. Pause the EventMesh subscription.
2. Update the Auth credentials.
3. Unpause the EventMesh subscription.

**Comment by marcobebway** [comment]
Blocked because the patch request gives the following error:

```json
{
    "error": {
        "code": "INTERNAL_SERVER_ERROR",
        "message": "Error occurred in the system"
    }
}
```

**Comment by k15r** [comment]
To unblock this ticket, during implementation and test fall back to using a MOCK

**Comment by marcobebway** [comment]
Moving to blocked because the PATCH request is returning 5xx.

**Comment by marcobebway** [comment]
Moving to blocked because the PATCH request is caching the secret and is not sensitive to changes.
