### ISSUE TITLE
Update the APIRule and webhook configs for EventMesh to allow validating the presented token.

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#17371]
**Description**

Use the credentials based on IAS, if corresponding secret exists in the cluster.

**Tasks:**

   - [x] Use the credentials from new secret in Webhook configs provided to EventMesh Subscriptions. (`eventing-webhook-auth` in `kyma-system`) 
   - [x] Create/Update the APIRule with correct `accessStrategies`. More info [here](https://github.com/kyma-project/kyma/issues/16803#issuecomment-1429666182).
   - NOTE: There is a [POC PR](https://github.com/kyma-project/kyma/pull/17075) for reference.

**Acceptance**
- [x] APIRules can be created / updated to use credentials based on IAS.
- [x] EventMesh subscription Webhook configs can be created to use credentials based on IAS.
- [ ] EventMesh subscription Webhook configs can be updated to use credentials based on IAS. [[Blocked](https://github.com/kyma-project/kyma/issues/17370#issuecomment-1570257070)]

**Comment by mfaizanse** [comment]
Read the secret name from env.

**Comment by muralov** [comment]
eventing-webhook-auth secret content can be seen [here](https://github.com/kyma-project/eventing-auth-manager#eventing-webhook-auth-secret)

**Comment by k15r** [comment]
Switch behaviour based on the newly introduced feature switch

**Comment by friedrichwilken** [comment]
What is IAS? Can you provide a link?
Where can I find the "new secret in Webhook configs"? How can I access it?
Where can I find the API-Rule that is supposed to be updated?
What is the "presented token"?

**Comment by friedrichwilken** [comment]
IAS - [Identity Authentication Service](https://help.sap.com/docs/identity-authentication?locale=en-US) by SAP.
The aforementioned secret is the [`eventing-webhook-auth`](https://github.com/kyma-project/kyma/issues/17490).

**Comment by friedrichwilken** [comment]
IAS - [Identity Authentication Service](https://help.sap.com/docs/identity-authentication?locale=en-US) by SAP
The aforementioned secret is the [`eventing-webhook-auth`](https://github.com/kyma-project/kyma/issues/17490)
