### ISSUE TITLE
Watch for new secret in eventing controller backend reconciler

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#17490]
Description:

With the new `eventing-auth-manager` we get a new secret called 
`eventing-webhook-auth` in the `kyma-system` namespace. This new secret needs to be used by the eventing controller and will be sent to EventMesh for it to use for authentication in the webhook against the exposed `sink`. Watch for the secret and trigger a flow to update the webhook client credentials on eventmesh.

Acceptance:
- [x] Enable the new secret using a feature flag (#17598)
- [x] Watch for changes of the secret `eventing-webhook-auth` in `kyma-system` (#17598)
- [x] Pause all webhooks on eventmesh
- [x] #17370 (for now as EventMesh PATCH is broken, use a MOCK)
- [x] #17371
- [x] Unpause the webhooks
- [x] Obey DOD
