### ISSUE TITLE
Istio 1.18 bump

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#17644]
**Description**

Upgrade Istio to 1.18.x.

AC:

- [ ] [provision test clusters](https://github.com/kyma-project/kyma/issues/17641)
- [ ] [new image available in Kyma external repository](https://github.com/kyma-project/test-infra/issues/7861)
- [ ] [istio component chart updated to version 1.18.x](https://github.com/kyma-project/kyma/issues/17642)
- [ ] [istio reconciler uses istioctl 1.18.x to install istio 1.18.x](https://github.com/kyma-incubator/reconciler/issues/1358)
- [ ] [bump Istio in Istio module](https://github.com/kyma-project/istio/issues/175)
- [ ] release notes for kyma
- [ ] [run manual tests](https://github.com/kyma-project/kyma/issues/17643)
- [ ] Update grafana dashboards and verify that they are working
- [x] verify kiali features (huskies)
- [x] verify trace propagation and trace data transport to jaeger (huskies)
- [x] notify monitoring team to verify that metric cardinality has not increased (Envoy metrics) (huskies)

**Reasons**

For security & support reasons we should be up to date with the latest Istio release.

Attachments

https://istio.io/latest/news/releases/1.18.x/announcing-1.18/
