### ISSUE TITLE
The pre-main-kyma-gardener-gcp-eventing-upgrade job is flaky

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/kyma#17655]
**Description**

The [pre-main-kyma-gardener-gcp-eventing-upgrade](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-kyma-gardener-gcp-eventing-upgrade) job is flaky.

**Hint:** Used this [flag](https://github.com/kyma-project/kyma/blob/1e576b8cca1cf04fb7c8f0c8aa57aa207e692d6f/tests/fast-integration/eventing-test/utils.js#L44) to identify.

**Tasks**
For the upgrade-job:
- [x] Disable tracing tests, (also disable any preparation step for it).
- [x] Disable Monitoring/Dashboards, (also disable any preparation step for it).
- [x] Disable eventing backend switching (EventMesh & NATS), (also disable any preparation step for it).

> **Note:** We keep them enabled in `pre-main-kyma-gardener-gcp-eventing`.

**Acceptance criteria**
- [ ] ~~The job is fixed and stable.~~
- [x] The job is **somewhat** fixed and **more** stable.

Here is a follow-up ticket: https://github.com/kyma-project/kyma/issues/17854

**Comment by mfaizanse** [comment]
Test PRs:
- https://github.com/kyma-project/kyma/pull/17686
- https://github.com/kyma-project/test-infra/pull/7902

**Comment by mfaizanse** [comment]
![image](https://github.com/kyma-project/kyma/assets/9897945/59f2a814-c73e-460f-b956-1e035067065c)

**Comment by mfaizanse** [comment]
PRs:
- https://github.com/kyma-project/kyma/pull/17726
- https://github.com/kyma-project/kyma/pull/17772

**Comment by mfaizanse** [comment]
Todo: Open a follow up ticket for tracing.

**Comment by mfaizanse** [comment]
If this job is still flaky after some time, we can think about making it non-required.

**Comment by mfaizanse** [comment]
```
Eventing tests preparation
       Should deploy jaeger:
     Error: Waiting for deployment tracing-jaeger timeout (90000 ms)
      at Timeout._onTimeout (utils/index.js:345:20)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

---

```
Eventing tests
       with BEB backend
         Cloud Events [binary] with v1alpha1 subscription should be delivered to eventing-sink :
     Error: Fetching published event responded with error: AssertionError: expected false to equal true
      at convertAxiosError (utils/index.js:114:12)
```

```
 1) Eventing tests
       "before all" hook: Create an ApiRule for NATS in "Eventing tests":
     Error: Wait for VirtualService eventing-nats-apirule timeout (30000 ms)
      at Timeout._onTimeout (utils/index.js:345:20)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

```
Deployed Components: 11/12
Could not deploy the following components:
- eventing
Error: kyma deployment failed
```

**Comment by mfaizanse** [comment]
For upgrade job:
  - [ ] Disable tracing tests, and also disable any preparation step for tracing tests.
  - [ ] Disable Monitoring/Dashboards.
  - [ ] Disable eventing backend switching (EventMesh & NATS)

**Comment by mfaizanse** [comment]
[Description](https://github.com/kyma-project/kyma/issues/17655#issue-1754674488) updated!
