### ISSUE TITLE
Application Connector module development on a "preview" plan with delivery process E2E

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/kyma#17992]
## Description

Application Connector module is done according to the concept of modularisation with the whole delivery process (pipelines, module template, tests) implemented end to end. 

It is running with the "preview" plan on Dev and Stage, operated by the `Lifecycle Manager` running there as a central service.

Detailed description of particular requirements is in attached issues.

## Acceptance Criteria

- [x] Application Connector module is developed according to the architecture guidelines
   - [x] design and discuss configurability and dependencies of modular Application Connector
   - [x] scaffold Application Connector manager in a dedicated repository under `kyma-project`
   - [x] Module has pipeline for building the binary image, assuring all needed quality standards 

- [ ] Application Connector module is operated by `Lifecycle Manager`, both installed locally. It is optional module of Kyma, can be disabled/enabled by user (it should trigger installation/uninstallation of module's subcomponents)

- [ ] Application Connector module is operated by `Lifecycle Manager` running as a central service (dev/stage/prod, introduced in kyma-project/kyma#15443). It is optional module of Kyma, can be disabled/enabled by user (it should trigger installation/uninstallation of module's subcomponents)

- [ ] Semi-automatic _Module submission process_ (PR with respective `ModuleTemplate` that will be used to deliver `application-connector-manager` to selected release channel is created manually) - https://github.com/kyma-project/keda-manager/issues/58

- [ ] `application-connector-module` renders its UI according to the available feature set (e.g. UI for configuration for  missing module dependencies is not rendered) - https://github.com/kyma-project/keda-manager/issues/36

- Core module tests implemented according to [test strategy](https://github.tools.sap/pandas/testing-strategy/tree/master/modularisation/governance/operational_test_management):
  - [ ] Conformance tests (run against `application-connector-module` and `ModuleTemplate` that is going to be published) - https://github.com/kyma-project/keda-manager/issues/83
  - [ ] Integration test (including the deletion without orphan resources check) - https://github.com/kyma-project/keda-manager/issues/74
  - [ ] Application Connector module's readme describes how CI/CD jobs fulfill test strategy - https://github.com/kyma-project/keda-manager/issues/105

**Links**
- [Concept document](https://github.com/kyma-project/community/tree/main/concepts/modularization)
- [Transition plan ](https://github.com/kyma-project/community/blob/main/concepts/modularization/transition.md)
- [Lifecycle manager](https://github.com/kyma-project/lifecycle-manager)
- [Module manager](https://github.com/kyma-project/module-manager)
- https://github.com/kyma-project/kyma/issues/15856

**Comment by tobiscr** [comment]
Closing as completed. Any new development happens as part of the Application Connector Module.
