### ISSUE TITLE
Rename Remote Environment to Application

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/kyma#1811]
Remote Environment CRD should be renamed to Application; this requires changes in following components:
- Metadata Service
- Connector Service Tests
- Proxy Service
- Remote Environment Controller
- Remote Environment Broker (TODO: create a ticket)
- UI API Layer (TODO: create a ticket)
- Console (TODO: create a ticket)
- Lambda UI 

Following components should be renamed:
- Remote Environment Broker
- Remote Environment Controller

**Please, mind that the documentation may need to be changed.**

Also, the client responsible for handling those CRDs should be moved from REB to the Controller.
Documentation for all components must be updated.

**Goal**
The goal of that Epic is to rename Remove Environment to the new name `Application.`

**Comment by Disper** [comment]
Tickets created as requested for:
- [x] Metadata Service
- [x] Proxy Service
- [x] Remote Environment Controller 
- [x] Remote Environment Broker
- [ ] UI API Layer 
- [ ] Console 
- [ ] Lambda UI
