### ISSUE TITLE
Istio 1.19 bump

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#18129]
**Description**

Upgrade Istio to 1.19.x.

AC:

- [x] [provision test clusters](https://github.com/kyma-project/kyma/issues/18124)
- [x] [new image available in Kyma external repository](https://github.com/kyma-project/test-infra/issues/8860)
- [x] [bump Istio in Istio module](https://github.com/kyma-project/istio/issues/241)
- [x] [istio component chart updated to Istio 1.1](https://github.com/kyma-project/kyma/issues/18130)
- [x] release notes for kyma
- [x] [run manual tests](https://github.com/kyma-project/kyma/issues/18131)
- [x] Update grafana dashboards and verify that they are working
- [x] verify trace propagation and trace data transport to jaeger (huskies)
- [x] notify monitoring team to verify that metric cardinality has not increased (Envoy metrics) (huskies)

**Reasons**

For security & support reasons we should be up to date with the latest Istio release.

Attachments

https://istio.io/latest/news/releases/1.19.x/announcing-1.19/
