### ISSUE TITLE
Add the ability to force the location of the Seed to be in the same region as Kyma cluster [EPIC]

### ISSUE THREAD

**Issue by TorstenD-SAP** [kyma-project/kyma#18182]
**Description**

The user who creates a Kyma cluster in the BTP cockpit should be able to enforce the location of the Control Plane to be in the same region as the Hyperscaler account where the Worker Nodes of the cluster are deployed. If it is not possible to have the Control Plane in the same region, the user should see an error message allowing him to proceed without this enforcement. In all cases it has to be transparent to the customer in which region the Control Plane is hosted.

**Reasons**

The region of the Control Plane is automatically chosen by Gardener (https://gardener.cloud/docs/gardener/concepts/scheduler/). Because of this the Control Plane could sometimes be deployed in a different region than the worker nodes, among others because Gardener doesn't have Seed clusters in all the regions Kyma can be deployed. This can lead to a violation of the law because the Control Plane could be in another legal area than the Worker Nodes and the customer is storing personal data (e. g. names, email addresses) on the Control Plane. We also have customers which are very sensitive regarding the regions where sensitive data is stored.

**AC** (Added by PK)
- [x] Phase 1: do the full investigation where we need to put implementation efforts, areas: (Gophers estimation: Size/M)
  - [x] 1.1) Check exactly what gardener can do about it
  - [x] 1.2) BTP Cockpit. New input parameter/s in KEB schema for plans: 
    - aws, 
    - azure,
    - gcp,
    - azure_lite,
    - sap-converged-cloud 
  - [x] 1.3) KEB implementation and contract with KIM
    - [x] KEB
    - [x] KIM: https://github.com/kyma-project/infrastructure-manager/issues/241, 
- [x] Phase 2: Feature delivery
  - [x] 2.1) KEB implementation + feature flag for dev, stage, prod: https://github.com/kyma-project/kyma-environment-broker/pull/781, https://github.com/kyma-project/kyma-environment-broker/pull/804, https://github.com/kyma-project/kyma-environment-broker/pull/796
    - [x] 2.1.1) KIM Variant
    - [x] 2.1.2) KIM config map with information for KEB: https://github.com/kyma-project/infrastructure-manager/issues/629
    - [x] 2.1.3) If Seed not exists in the region of the shoot, then inform user about regions where seed clusters exists
      - [x] 2.1.3.1) We need mechanism to easily validate that and return to user useful information. For example if KIM will create a config map for all plans with seeds regions, than KEB do not need to crate Runtime CR at all
    - [x] 2.1.4) For local KEB tests, add testing config map to the k3d installation (https://github.com/kyma-project/kyma-environment-broker/issues/2066) @szwedm)
    - [x] 2.1.5) Filter out regions that KEB is not supporting. Take into account that some BTP regions like cf-eu11 has only one hyperscaler region etc. (https://github.com/kyma-project/kyma-environment-broker/issues/2067 @szwedm)
  - [x] 2.2) Set KEB feature flag on DEV to true and write new SKR e2e integration test
  - [x] 2.3) Register new schema on CIS - DEV
  - [x] 2.4) Register new schema on CIS - STAGE
  - [x] 2.5) Register new schema on CIS - PROD
  - [x] 2.6) Update [Provisioning and Updating Parameters in the Kyma Environment](https://help.sap.com/docs/btp/sap-business-technology-platform/provisioning-and-update-parameters-in-kyma-environment?&version=Cloud) and [Available Plans in the Kyma Environment](https://help.sap.com/docs/btp/sap-business-technology-platform/available-plans-in-kyma-environment?&version=Cloud)
  - [x] 2.7) RN 
  - [x] 2.8) Rename input parameter from "shootAndSeedSameRegion" to something more general and not related to Gardener e.g. "colocateControlPlane"
    - [x] 2.8.1) and description to something like "Enforce to run the Kubernetes control plane in the same region as the the cluster nodes", check with TW
    - [x] 2.8.2) test new changes and update ERS on all envs 
    - [x] 2.8.3) check if we need to adjust documentation and RNs
  - [ ] ~~2.9) Synchronise timeouts between KIM and KEB~~

Status:

Blockers:
- ~https://github.com/kyma-project/infrastructure-manager/issues/629~
- https://github.tools.sap/kyma/backlog/issues/7373, Update 7.07.2025: still some issue, one region was removed by frogs but cluster creation works in that region

**Comment by TorstenD-SAP** [comment]
A label `seed.gardener.cloud/region` was added to each Gardener seed. This label can be used to restrict the seeds allowed for a shoot cluster by using the `spec.seedSelector` in the [shoot spec](https://github.com/gardener/gardener/blob/v1.84.1/example/90-shoot.yaml#L365-L368).

**Comment by tobiscr** [comment]
We agreed with @kyma-project/gopher to offer this feature under following constraints:

* We know that not all regions have yet their own seed, thats why we will show in the UI already a link to the documentation that this feature is not in all regions supported and can lead to failed Kyma clusters (because Gardener rejected the cluster creation)
* KIM and KEB **will not check up-front** if a seed exists in the requested regions and follow a "trail and error" approach: if Gardener could create the cluster all is fine otherwise the customer get's an error replied.

**Comment by ralikio** [comment]
I have tested `seedSelector` field mentioned in https://github.com/kyma-project/kyma/issues/18182#issuecomment-1888624492. @PK85 suggested that for our test scenario we should select a shoot region that does not contain any seeds in it - `ap-northeast-1`. Just by creating a shoot with default configuration it got assigned a `aws-ha-us2` region. Creation of another shoot with `seedCluster` set to `ap-northeast-1` resulted in the following status:

```
*Status*
Create Pending

*Last Message*
Failed to schedule Shoot: none out of the ... seeds has the matching labels required by seed selector of 'Shoot' (selector: 'seed.gardener.cloud/region=ap-northeast-1')
```

`Status: Create Pending` seems counterintuitive to @kyma-project/gopher and @kyma-project/framefrog and will be consulted with Gardener Team.

**Comment by ralikio** [comment]
Initial PR with KEB changes: https://github.com/kyma-project/kyma-environment-broker/pull/781

**Comment by ralikio** [comment]
Proposed request sent to Provisioner's graphql API with new field *shootAndSeedSameRegion*: 

```
{
	runtimeInput: {
		...	
	},
	clusterConfig:{
		gardenerConfig: {
			...	
			shootAndSeedSameRegion: false (default) | true,
		},
		...
	},
}
```

**Comment by ralikio** [comment]
Schema generated out of https://github.com/kyma-project/kyma-environment-broker/pull/781: https://gist.github.com/ralikio/32138d957c9886a9e182494f39e6078d

**Comment by tobiscr** [comment]
JFYI - added a draft PR for Gardener to extract the Seed determining logic into separate struct to make it reusable for other  apps over their API:

https://github.com/gardener/gardener/pull/9843

**Comment by ralikio** [comment]
Rendering of schema changes:

![Image](https://github.com/kyma-project/kyma/assets/74771103/577b0883-ea5d-49b6-9c15-eb91cfa49604)

**Comment by ralikio** [comment]
Tests for seed selection process when provisioning shoots in high availability configuration (documented in https://github.com/kyma-project/kyma/issues/18182#issuecomment-2133446254) assumed that seeds that contained ha in their name (e.g. aws-ha-eu3) are specially designed to serve HA configuration. This is incorrect. Seeds with such names are just results of old naming conventions. All seeds with at least three zones are able to handle ha control plane deployments. Additionally, there is also visible property that restricts number of seeds available for scheduling. At time of writing the comment all of seeds were deployed across three zones.

**Comment by ralikio** [comment]
As of today we have implemented KEB part for Provisioner. @kyma-project/gopher are waiting for KIM implementation.

**Comment by tobiscr** [comment]
Appendix - some more background information related to this issue:

[Customer reported bug](https://github.tools.sap/kyma/backlog/issues/4091)
[Slack Thread on #kyma-team](https://sap-btp.slack.com/archives/C01LGCBS196/p1690270149409429)
[Slack Thread on #sap-tech-gardener-live](https://sap-btp.slack.com/archives/CBVQLMS6N/p1690262113697149)

**Comment by tobiscr** [comment]
@kyma-project/gopher : enabling "seed in region as shoot"-flag is only supported for new clusters - customers cannot enable it after the cluster exist - is this correct?

**Comment by tobiscr** [comment]
Feedback from @PK85  (vis Slack):

```
Yes, only for new ones, cause as I remember seed cannot be updated
Maybe your team can double check that
```

> @kyma-project/gopher : enabling "seed in region as shoot"-flag is only supported for new clusters - customers cannot enable it after the cluster exist - is this correct?

**Comment by szwedm** [comment]
# State as of 2.04.25

The feature has been implemented in KEB and KIM. 
KEB has the `enableShootAndSeedSameRegion` feature flag which enables `shootAndSeedSameRegion` provisioning parameter to enforce the same region for Seed and Shoot:
https://github.com/kyma-project/kyma-environment-broker/blob/1c4e5f1ebc9d99686f85841e99be9acc26748cd2/resources/keb/values.yaml#L160
https://github.com/ralikio/kyma-environment-broker/blob/234234bb323da7bea59294b3cc438e84109c4135/internal/dto.go#L192

Example of provisioning parameters for KEB to enforce the same `us-east-1` region for Seed and Shoot:
```json
"region":"us-east-1",
"shootAndSeedSameRegion": true
```

The `shootAndSeedSameRegion` parameter is reflected in the Runtime CR manifest in `.spec.shoot.enforceSeedLocation` field. When the `enforceSeedLocation` field is set to `true`, KIM adds `seedSelector` in the Shoot CR to find the appropriate Seed. For example:
```yaml
spec:
  seedSelector:
    matchLabels:
      seed.gardener.cloud/region: us-east-1
```
should match a Seed with `seed.gardener.cloud/region: us-east-1` label in the metadata. 

If the Seed exists, then Gardener creates the Shoot and sets a appropriate value in the Shoot's spec in `seedName` field. If the Seed does not exist, then KIM returns an error indicating the unavailability of the Seed in the given region. Error example:
```
Cannot find available seed for the region eu-west-2. The followig regions have seeds ready: [eu-west-1 us-east-1].
```

It looks like we don't have a list with regions which support the same location for Seed and Shoot. User has to send a provisioning request to find out whether the Seed and Shoot can be in the same region. Additionally, the error returned by KIM in a case when there is no Seed in the requested region includes the suggested regions taken directly from Gardener. This could be misleading as not every region from Gardener is supported in Kyma, for example `eu-west-1` is not supported https://help.sap.com/docs/btp/sap-business-technology-platform/regions-for-kyma-environment?locale=en-US#cluster-regions

**Comment by tobiscr** [comment]
@szwedm  / @PK85 : we are going to support a validation mechansim which can reject RuntimeCRs if a shoot and seed have to be in same region - but no seed could be found in this region.

Please see https://github.com/kyma-project/infrastructure-manager/issues/807

**Comment by szwedm** [comment]
# @kyma-project/gopher and @kyma-project/framefrog sync meeting notes 7.04.25
* We agreed to use a common ConfigMap for KEB and KIM. The ConfigMap should contain supported regions for the instance creation. 
* KIM will have a validation webhook to reject Runtime CRs containing unsupported region. This should ensure fail-fast mechanism. We need a well defined response payload, which should contain an understandable message to the user.

**Comment by PK85** [comment]
Blocked by: https://github.com/kyma-project/infrastructure-manager/issues/629

**Comment by szwedm** [comment]
Unblocked, I'm implementing the validation and fail-fast in the broker.

**Comment by szwedm** [comment]
**Seeds regions**
from the configmap provided by Framefrog's component

DEV
```
data:
  aws: |-
    seedRegions:
    - eu-west-1
    - eu-central-1
    - us-east-1
  azure: |-
    seedRegions:
    - westeurope
    - northeurope
    - westus2
    - eastus
    - eastus2
  gcp: |-
    seedRegions:
    - europe-west1
    - us-central1
  openstack: |-
    seedRegions:
    - eu-de-1
```

STAGE
```
data:
  aws: |-
    seedRegions:
    - ap-southeast-1
    - ap-southeast-2
    - ap-northeast-2
    - eu-central-1
    - eu-north-1
    - eu-west-1
    - eu-south-1
    - us-east-1
    - us-west-2
  azure: |-
    seedRegions:
    - australiaeast
    - westeurope
    - switzerlandnorth
    - westus2
    - eastus
  gcp: |-
    seedRegions:
    - asia-south1
    - europe-west3
    - europe-west1
    - me-central2
    - us-central1
  openstack: |-
    seedRegions:
    - eu-de-1
    - na-us-1
```

**Comment by koala7659** [comment]
ConfigMap from PROD: 

```
apiVersion: v1
data:
  aws: |-
    seedRegions:
    - ap-southeast-1
    - ap-southeast-2
    - ap-northeast-2
    - eu-central-1
    - eu-north-1
    - eu-west-1
    - eu-south-1
    - us-east-1
    - us-west-2
  azure: |-
    seedRegions:
    - australiaeast
    - westeurope
    - switzerlandnorth
    - westus2
    - eastus
  gcp: |-
    seedRegions:
    - asia-south1
    - europe-west3
    - europe-west1
    - me-central2
    - us-central1
  openstack: |-
    seedRegions:
    - eu-de-1
    - na-us-1
kind: ConfigMap
```

**Comment by jaroslaw-pieszka** [comment]
Unblocked by https://github.tools.sap/kyma/backlog/issues/7373

**Comment by PK85** [comment]
I left a comment: https://github.tools.sap/kyma/backlog/issues/7373#issuecomment-13342421 
We wait for frogs answer.

**Comment by tobiscr** [comment]
Investigation of ME cluster: the ME-clusters include a taint. That's why they were not added to configmap.

**Comment by szwedm** [comment]
> * 2.8) Rename input parameter from "shootAndSeedSameRegion" to something more general and not related to Gardener e.g. "colocateControlPlane"

I like the parameter name change from `shootAndSeedSameRegion` to `colocateControlPlane`. The new name is concise and hides unnecessary terms like `seed` and `shoot`. My other proposal is `enforceControlPlaneRegion`.
