### ISSUE TITLE
Enable VPC peering for Kyma clusters

### ISSUE THREAD

**Issue by varbanv** [kyma-project/kyma#18197]
## Description
Provide a way for end users to establish secure internal connectivity to other networks on the same hyperscaler via VPC peering.

### Problem
Currently, Kyma is a layer on top of Kubernetes and as such provides a very limited set of infrastructure configuration options at provisioning time. 
However, customers looking to adopt Kyma that already use existing hyperscaler offerings already take advantage of more advanced networking capabilities in order to establish secure internal connectivity to other workloads. 
Without such connectivity in Kyma, customers would require a much higher effort and increased risk tolerance in order to migrate or extend their existing workloads on Kyma.

### Benefits
**For customers:**
- greater flexibility around infrastructure requirements 
- ability to meet requirements in order to move workloads to Kyma
- reduced time to market for new development that requires secure and fast connectivity to existing workloads

**For us:**
 - increase adoption
 - mitigate the abandoned BYOC approach
 
### Potential problems
 - centralized network configuration management could complicate the implementation
 
## Acceptance criteria

- [ ]  Users can enable/disable VPC peering via Kyma Dashboard and command line
- [ ] Kyma will provide a mechanism for end users to access relevant information related to the VPC peering configuration
- [ ] The use of VPC peering will not require users to have direct access to the Kyma managed hyperscaler accounts
- [ ] Kyma will provide a reasonable solution for end users to monitor the state of the VPC peering setup

**Comment by pbochynski** [comment]
The prototype has been started. Two repositories are created in kyma-project:
- https://github.com/kyma-project/cloud-resources-control-plane - the control plane part
- https://github.com/kyma-project/cloud-resources-manager - runtime operator

**Comment by ngrkajac** [comment]
For the sake of simplicity, we have moved all code to one repo. You can find all the code in the cloud-resources-manager repo now. 

https://github.com/kyma-project/cloud-resources-manager - control plane, runtime operator

**Comment by ngrkajac** [comment]
**Status update** 

VPC Peering is under development. 

We have a working MVP for VPC Peering on GCP. It's a happy path, but the "create" VPC Peering flow is working. We will finish VPC Peering creation for Azure soon, with AWS right after. 

More info will arrive soon.

**Comment by ngrkajac** [comment]
Status update: Development is done (mostly); we are in communication with the SRE team to add proper principals for every Cloud Provider.

**Comment by ngrkajac** [comment]
Dev is done, currently, this is being tested, and in a few days will be pushed to the stage.

**Comment by zhoujing2022** [comment]
Hello @ngrkajac The planned Due-day was end of September. Is there any new update. Thx a lot.

**Comment by ngrkajac** [comment]
VPC Peering features are already developed, deployed, and enabled for some customers.

The feature will soon be enabled on the Prod landscape within the official release.

**Comment by ngrkajac** [comment]
VPC Peering should be enabled globally (GA) on Monday, December 2nd.
