### ISSUE TITLE
Force delete option for kyma modules

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#18318]
**Description**
Implement a force delete module functionality in Kyma tools (CLI and dashboard). As a prerequisite module templates need to be extended with the list of resources (CRDs) that are managed by the module. The force delete feature will delete all instances (CRs) managed by the module in the first step, and then the module will be deleted.
The list of CRDs can be extracted from the manifest file or added explicitly the module metadata.
Subtasks:
- [x] https://github.com/kyma-project/lifecycle-manager/issues/963
- [x] https://github.com/kyma-project/cli/issues/1812
- [ ] https://github.com/kyma-project/busola/issues/2613

When the feature is ready we need to ensure that all the modules properly register their CRDs in the submission pipeline.

**Reasons**
Many users reported that deleting Kyma modules is a tedious tasks. Due to the [blocking strategy](https://github.com/kyma-project/community/issues/765) in Kyma modules cannot be deleted until the last resource using the module is gone. Users have to find and delete all the dependent resources on their own. They expect that Kyma tools (dashboard and CLI) can do it for them.
