### ISSUE TITLE
Community modules in managed and non-managed environment

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#18450]
## Description
Provide a way to install community modules using the Kyma Dashboard that is consistent with adding fully managed modules. UI should be simple and guide the user to use the best available option:
- add managed modules with Kyma CR modification (use Kyma Lifecycle Manager for installation and auto-update)
- install community modules directly in the cluster
- install regular (manageable) modules directly in the non-managed cluster

Other options should be also available, but in advanced mode (installing manageable module without KLM - opt-out from full support)

### Reasons
Kyma comes with a set of Kubernetes building blocks (called modules). Modules are independent: can be added and removed in the runtime, and have an independent release cycle. Each module provides and a manager (Kubernetes operator) and a default configuration (custom resource). Some modules are available in the managed SAP Kyma Runtime with full support (SLA, automatic upgrades). Other modules (community modules) are offered only with community support (no SLA, manual upgrades, possible breaking changes). In the managed clusters the Kyma Lifecycle Manager (KLM) is responsible for installation and automatic upgrades of supported modules. KLM is running centrally in the Kyma Control Plane and is configured with Kyma custom resource in the namespace kyma-system located in the managed cluster. Users who want to use some managed modules have to add their names to the Kyma CR spec. The community modules cannot be managed by the KLM and should be installed with the desired version using kubectl with the provided Kubernetes manifests (manager deployment and default configuration). 
The situation gets more complicated when users want to install the "manageable" modules in their own (not managed) cluster (like k3s) or if they want to opt-out from full management in the managed cluster (install module manager with kubectl without using KLM).

Having a list of available modules with clear indicators if the module is/can be fully managed or not, and a consistent convenient installation process is a must-have.

## Acceptance Criteria
- [x] https://github.com/kyma-project/lifecycle-manager/issues/1472
  - The current approach with ModuleTemplate CRD should be revisited, as a set of new requirements applies
  - This will provide a baseline for the implementation of the following ACs
- [x] https://github.com/kyma-project/lifecycle-manager/issues/1211
  - Blocking deletion mode supported by the KLM (deletion hangs until all the domain CRs are gone from the cluster)
  - Ignore deletion supported by the KLM (which translates to "unmanaging" modules in the context of this Epic)
- [x] https://github.com/kyma-project/lifecycle-manager/issues/1471
  - Module state needs to be separated into two different entities
  - Manifest state will reflect the overall health of module deployment
  - Module state will represent whether the user-made configuration was applied correctly and the module is serving its purpose
- [x] Busola's UI is adapted to the new API
  - [x] https://github.com/kyma-project/busola/issues/3447
  - [ ] https://github.com/kyma-project/busola/issues/3593
  - It should be transparent in which state the modules are, this applies both for Manifest and Module states
- [x] https://github.com/kyma-project/cli/issues/2460
- [x] https://github.com/kyma-project/lifecycle-manager/issues/1556 (after Busola is migrated)
- [x] [Modulectl is used in the submission pipeline](https://github.com/kyma-project/test-infra/issues/12655)
  - It should produce a list of modules that Busola can consume and display to the user

### Installation
Manageable modules should be installed with KLM if Kyma CR is available (managed cluster). The direct installation (without KLM) should be possible for manageable modules but should be harder to find and guarded by warnings. It should not be possible to install the module directly if it is already a managed module. UPDATE: see clarification in https://github.com/kyma-project/kyma/issues/18450#issuecomment-3108312710.
In the open source scenario (not managed cluster) all modules should be installed directly with the provided Kubernetes manifests. 

_Note: direct installation and deletion are idempotent actions - and can be repeated several times without side effects. It should be possible to trigger installation or deletion several times (finish an interrupted/incomplete action by applying/deleting again, or upgrade the module manager by applying a new version)_

### Upgrade
For managed modules, it happens automatically. For not managed modules user has to apply the module manifest again. Default module configuration (default CR) should not be applied for updates. The module operator in the new version should handle previously created configurations. 
For both cases (managed and manual) it is essential to check what is the current version of the module manager (operator) installed in the cluster. UI should compare the desired version with the version that is deployed in the cluster. If the version does not match it is the indicator that should be visible to the user. It means that for managed components KLM hasn't finished the upgrade yet, for not managed modules it should encourage the user to perform the upgrade (press the apply button).

### Deletion
Module manager should not be undeployed before any managed resource (including module configuration) still exists. Otherwise, there is a good chance that the orphan resources will stay in the cluster forever. Therefore each module should declare the list of managed resources (group, version, kind) and the user should actively delete those resources before the module is finally deleted (manager undeployed). This step should be executed regardless if the module is managed by KLM or installed manually. 

_Warning: when you delete the managed module configuration before the module is removed from Kyma CR spec, the KLM can try to recreate it and the module installation starts again. In that case, module configuration should be removed by KLM or the `customResourcePolicy` should be changed to Ignore (from the default CreateAndDelete)_

```mermaid
flowchart TD
    N([Start: Choose Module to Delete]) --> MO{"Do managed 
    resources exist?"}
    MO -->|No| O{"Is the Module 
    Managed?"}
    MO -->|Yes| DMO{Continue?}
    DMO -->|Yes| DM[Delete managed resources]
    DMO -->|No| E
    DM --> MO
    O -->|Yes| P["Delete via KLM
                  Remove module 
                  from Kyma CR"]
    O -->|No| T["Direct Deletion 
    of module manager 
    Kubernetes resources"]
    P --> E([End])
    T --> E
```

Managed modules should be deleted by KLM and the deletion process should be triggered by removing module entry from Kyma CR spec.
Not-managed modules should be removed directly by deleting Kubernetes resources included in the module manager manifest.

### Status handling
With automatic and manual lifecycle management it is not so easy to determine if the module is installed and what is the status. Here are some rules that can be applied to determine module status and possible actions:
- module is managed and enabled if it exists in spec.modules in default Kyma CR in kyma-system namespace
- module is enabled if default CR exists and does not have deletion timestamp
- module is in the deleting state when default CR has a deletion timestamp
- module is removed if there is no entry in Kyma CR and default CR does not exist
- module is Ready if default CR is applied and has proper status (usually status.state=Ready, but can be different) and the manager is deployed in the version defined in the desired release channel

## Diagram
```mermaid
flowchart TB
    A[Start: Choose Module to Install] --> B{Is the Cluster Managed?}
    B -->|Yes| C[Use Kyma Lifecycle Manager]
    B -->|No| D{Is the Module Manageable?}
    C --> E[Modify Kyma CR for Installation]
    E --> F[Automatic Updates via KLM]
    D -->|Yes| G[Install Manageable Module Directly]
    D -->|No| H[Install Community Module with kubectl]
    G --> I[Option: With KLM for Support]
    G --> J[Option: Without KLM - Opt-out from Full Support]
    H --> K[Manual Upgrades, Possible Breaking Changes]
    I --> L[Managed with SLA, Automatic Upgrades]
    J --> M[Warning: Limited Support]
```

```mermaid
flowchart TB
    U[Start: Check Module Status] --> V{Is Module in Kyma CR?}
    V -->|Yes| W[Managed and Enabled]
    V -->|No| X{Does Default CR Exist?}
    X -->|Yes| Y[Check if CR has Deletion Timestamp]
    Y -->|No Timestamp| Z[Module is Enabled]
    Y -->|Has Timestamp| AA[Module is Deleting]
    X -->|No| AB[Module is Removed]
    W --> AC[Ready if CR Applied and Manager at Desired Version]
    Z --> AC
    AA --> AC
```

## Attachments
- PoC with manual installation of [community modules](https://github.com/kyma-project/community-modules)

**Comment by valentinvieriu** [comment]
From UI Perspective - we decided to refactor our UI to match the PRoposed Designs using the Existing implementation with KYMA CR (https://github.com/kyma-project/busola/issues/2624 ) 

Once the new modules catalog will be ready, we will switch to the new API. We are waiting for the feedback when the new JSON based API will be ready and we can switch from reading Module Templates to display Module Metadata.

**Comment by tobiscr** [comment]
@tehret77  - JFYI, this feature will make the management of Kyma communicate modules more convenient in the future.

**Comment by varbanv** [comment]
Due date shifted to reflect additional work that is needed for UI/CLI, etc.

**Comment by janmedrek** [comment]
The proposal for all the module catalogue changes is almost finalized here: https://github.com/kyma-project/lifecycle-manager/issues/1681

Right now, we are waiting for input from the Busola and CLI teams to shape the decision and proceed with the implementation tweaks.

After that, it is all about adapting the UI and pipelines to match the picture and we are good-to-go with releasing the Community Modules as a whole.

**Comment by janmedrek** [comment]
We would also need some documentation for the community-contributed modules, such as what metadata to provide and where it should be placed.

Also, a modulectl command for creating a module template would be welcome.

**Comment by janmedrek** [comment]
Extended with the documentation issue: https://github.com/kyma-project/lifecycle-manager/issues/1812

**Comment by janmedrek** [comment]
Update:
- Deletion Modes and status separation is finished and supported by Busola
- We are working on changes to the API to support multiple versions and some additional info fields for Busola to display
- As soon as we have working components we will present a playground to the Hasselhoff team
- After the contract is finalized we can start working on the build pipelines (and most likely migrate them to the modulectl)

**Comment by janmedrek** [comment]
Hopefully, a final update before the work is completed.

Right now, we are working on the following topics:
- **planned** Busola support for Community Modules - to be completed in Q2
- **in progress** - Use of modulectl tool in the Submission Pipeline - this is required to push out all the necessary API changes (required by the Community Modules story) to our environments

As soon as those two are ready we can start the Module migration and enable the feature in the landscapes.

**Comment by kwiatekus** [comment]
@kyma-project/jellyfish 
Is it possible to use modulectl already to create a community version of our modules?
We would like to release docker registry as community module
https://github.com/kyma-project/docker-registry/issues/369

**Comment by c-pius** [comment]
@mrCherry97 one question came up... Does a ModuleTemplate of a community module need to be in kyma-system namespace to be detected by Busola, or do you scan all ModuleTemplates in all namespaces?

CC: @pPrecel

**Comment by pPrecel** [comment]
@c-pius We plan to release all of our open-source modules as Kyma modules (where modules are accessible from channels) and at the same time as community modules to support clusters without a centralized installation manager (KLM). From this perspective, it would be much easier for us to work on the module-config only, to generate both ModuleTemplates - internal and open-source ones.

I would expect some additional `modulectl create` configuration generating ModuleTemplate for the community modules use case. Without pushing artifacts to the registry, but with additional label `"operator.kyma-project.io/community-module": "true"`. Even if this additional configuration will be inside the module-config, and even if we will have two module-config files for both configurations. 

Of course, we can work directly on ModuleTemplate, but for us, it may cause more mistakes and problems working on two separate resources (ModuleTemplate directly and module-config) to release one resource for two markets.

**Comment by c-pius** [comment]
That's interesting. I was under the assumption that Kyma modules can also be installed manually in the same way as community modules. That's why modulectl also puts the `rawManifest` resource into the MT automatically: https://github.tools.sap/kyma/kyma-modules/blob/main/docker-registry/moduletemplate-docker-registry-0.7.0.yaml#L154-L156 and the manager section should be there for Kyma modules so that CLI/Busola can detect if the module is installed, even if not listed in Kyma CR `spec.modules` https://github.tools.sap/kyma/kyma-modules/blob/main/docker-registry/moduletemplate-docker-registry-0.7.0.yaml#L32-L36

So in my understanding, there would be no need for a separate ModuleTemplate to have the "community flavor" of the module.

@kyma-project/hasselhoff has it been considered for Busola that a Kyma module may be installed manually given the ModuleTemplate KLM synced to the SKR?

**Comment by mrCherry97** [comment]
As far as I remember, no. Installing a managed module involves checking ModuleTemplates and MR for available channels/versions and putting them into the KymaCR. But @akucharska, please confirm if I'm correct

**Comment by pPrecel** [comment]
> And would need to know from [@pPrecel](https://github.com/pPrecel) / [@kwiatekus](https://github.com/kwiatekus) if there are any arguments pro/con for re-using the existing ModuleTemplate instead of creating a separate community-flavored one.

@c-pius  I think there are two pros of having a community module version of each (our) modules:

* CLI may install our modules out of a managed cluster (for example, on k3d.
* We could release new, even non-feature-full, as a community module, test it, maybe even give such functionality to specific clients, and then decide about the module's future. We have such a situation right now with the Registry Proxy module.

**Comment by c-pius** [comment]
> - the same ModuleTemplate resource shall be used both for a managed and community installation 
>   - [ ] Action Item: figure out what to do with the .metadata.namespace: kcp-system in the originally created ModuleTemplate

The generated ModuleTemplate may continue to be put in the `kyma/kyma-modules` repository by the submission pipeline. From there, the module team may copy it to make it externally available for community installation. E.g., it can be added as an artifact to the module version release.

Question is what to do about `kcp-system` namespace? In the managed offering, we need to continue to put it into KCP in `kcp-system` namespace. Currently, the generated ModuleTemplate typically has `kcp-system` namespace specified (is configurable via `module-config.yaml` but defaults to `kcp-system`). 

Proposal would be that we generate the ModuleTemplate WITHOUT namespace (change default in modulectl to no namespace). For applying it to KCP, we change the kustomizations in `kyma/kyma-modules/tree/main/kustomizations` to use `kcp-system` namespace via the [kustomize directive](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/namespace/).

Module teams then make the ModuleTemplate available as is. When the customer applies it to the unmanaged cluster, they need to consciously choose where it should land, or it lands in default namespace. This way, also the module team doesn't need to make assumptions where it should go on the unmanaged cluster.

The alternative would be to keep `kcp-system` namespace on the generated ModuleTemplate. But then it would require manual change or removal by the module team when they copy it to the location where it is made available exernally.

**Comment by c-pius** [comment]
> 5. module template docker-registry-0.8.0 landed in my cluster, and overwrote the module template community version; something that we expect to happen...

To clarify, the synced MT has the `managed-by=kyma` label, correct?

My understanding was that CLI/Busola can check all ModuleTemplates (regardless the `managed-by=kyma` label) and use the `.manager` section to determine if it is installed. Only then the `managed-by=kyma` is used to distinguish the kind of installation as:

```
- NO `managed-by=kyma` label present => Community Installation
- `managed-by=kyma` label present => further distinguish in:
  -  KymaCR `.spec.modules[<name>].managed` true => Managed Installation
    - KymaCR `.status.modules.state` shows Ready/Porcessing/Deleting/...
  -  KymaCR `.spec.modules[<name>].managed` false => Unmanaged Installation
    - KymaCR `.status.modules.state` shows Unmaged
  -  KymaCR `.spec.modules[<name>]` Missing  => Unmanaged Installation
    - KymaCR `.status.modules.state` is missing for this module
```

**Comment by kwiatekus** [comment]
> To clarify, the synced MT has the managed-by=kyma label, correct?
Yes

We will adjust the logic to cover the case.
I wonder if we should additionally guide the user into making the module managed once we detect that it's manager is installed, module template contains `managed-by: kyma` label, but the module is not present in Kyma CR

**Comment by kwiatekus** [comment]
> According to the scenario above, the installation would "automatically" move from the community section to the "normal" section but indicating Unmanaged state I assume

We can make it like this. 

> Is it important to distinguish the case between Community Installation and Unmanaged Installation in the UI/CLI?

From user perspective it can be the same.. however moving on to the "Managed" state would need different actions in both cases. For community installations, the module would need to be added to Kyma CR, for unmanaged  modules its just the flag that needs to be changed in the Kyma CR spec for the particular module

**Comment by kwiatekus** [comment]
> I am wondering if it is possible to rely on patching that will either insert the whole entry, or just flick the flag

We will give it a try. Thank you

**Comment by janmedrek** [comment]
Implementation part in our backend and Busola was done, right now we are missing the documentation for the general use of Community Modules.

We are currently discussing the documentation structure and contents. After we are done with the docs and CLI, this ticket can be closed.

**Comment by kwiatekus** [comment]
> Cluster admin should be able to do anything. Anyway, the policy can be disabled by admin

..temporarily.. This policy is reconciled by the Runtime Monitoring Operator

**Comment by ebensom** [comment]
I will discuss how to handle the community modules scenario within the SRE team.

**Comment by ebensom** [comment]
> For UI/CLI we can also decide to not install community modules in kyma-system (at least in managed clusters). But this makes things more complex.

Just to understand correctly, what complexity would it bring to not allow deploying community modules in kyma-system namespace on SKRs?

**Comment by atisap** [comment]
Hello, 
Disabling or broadly weakening these [admission policies](https://github.tools.sap/kyma/runtime-monitoring-operator/blob/main/docs/contributor/resources/02-rma.md#validating-admission-policies) would allow accidental or scripted removal of critical resources (namespaces kube-system, kyma-system, istio-system or their core workloads). That creates real outage risk regardless of whether the customer initiated the action. 
Users mapped to `system:masters` are already allowed to delete kyma-system workloads ([explicit in the policy expression](https://github.tools.sap/kyma/runtime-monitoring-operator/blob/main/resources/rma/templates/policy/kyma-system-protection.tpl#L18)).

**Comment by kwiatekus** [comment]
> Just to understand correctly, what complexity would it bring to not allow deploying community modules in kyma-system namespace on SKRs?

From the point of view of the maintainer of the docker-registry module (which is currently available as managed module via experimental channel and also as community module) keeping the same resource manifest for both installation models (same target namespace) is simply convenient

@pbochynski what else do you have in mind ?

**Comment by kwiatekus** [comment]
we can install registry-proxy in its own namespace.. just like ztis module [was advised to do](https://github.tools.sap/kyma/warden/issues/46#issuecomment-14841589)
https://github.com/kyma-project/registry-proxy/pull/36

**Comment by mrCherry97** [comment]
Do we need to disable the `kyma-system` namespace in the dropdown `Add Source YAML` for the Community Modules ModuleTemplates also? 

<img width="1732" height="243" alt="Image" src="https://github.com/user-attachments/assets/b757baf1-bf5d-4fb7-a2f1-d901e4a7d5e1" />

@pbochynski @janmedrek 

As far as I remember kyma-cli plan to block it or they made it @kwiatekus
