### ISSUE TITLE
Setup pipelines for EPP

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#18477]
## Description

Create a new version of EPP from its own repository (kyma-project/eventing-publisher-proxy)

## Acceptance

- [x] setup pipeline for
  - [x] lint ([eventing-publisher-proxy/#21](https://github.com/kyma-project/eventing-publisher-proxy/pull/21))
  - [x] unit test
  - [x] build ([test-infra/#9542](https://github.com/kyma-project/test-infra/pull/9542)) ([test-infra/#9589](https://github.com/kyma-project/test-infra/pull/9589))
    - In the image build job for release, sign the image.
  - [x] release ([eventing-publisher-proxy/#32](https://github.com/kyma-project/eventing-publisher-proxy/pull/32)), ([test-infra/#9608](https://github.com/kyma-project/test-infra/pull/9608))
    - follow the same pattern as eventing-manger / nats-manager
  - [x] e2e test NATS Backend ([eventing-publisher-proxy/#30](https://github.com/kyma-project/eventing-publisher-proxy/pull/30))
  - [ ] ~~#18508~~

- [ ] chores: 
  - [x] cleanup old outdated pipelines ([test-infra/#9554](https://github.com/kyma-project/test-infra/pull/9554))
  - [x] update documentation ([eventing-publisher-proxy/#33](https://github.com/kyma-project/eventing-publisher-proxy/pull/33))
  - [x] release a new version of EPP
  - [ ] bump used image of EPP in eventing-manager to new release
  - [x] remove EPP code from kyma-project/kyma ([kyma/#18510](https://github.com/kyma-project/kyma/pull/18510))
