### ISSUE TITLE
Support migration of "old style" Kyma component to Connectivity Proxy module [EPIC]

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma#18523]

**Comment by akgalwas** [comment]
Here is the list of functionalities that are required for the module to fully integrate with Kyma: 
- [ ] Creating TLS certificate for business tunnel. External business tunnel URL must be built in the same form as the old Connectivity Proxy Reconciler does (cp.<cluster domain>) to avoid breaking existing installations
- [ ] The UI exposes only the CRD properties that the user can modify (e.g. everything under `spec.deployment` key).
- [ ] Integration with the BTP Operator.
- [ ] For existing installations the module must be able to take over existing Service Mappings

Additional requirements:
- [ ] The operator should make sure that Istio CRDs such as `VirtualService` are available. If Istio is not available meaningful status should be set in the CR.
- [ ] The operator should make sure that BTP related CRDs are available (`serviceinstance.services.cloud.sap.com`, and `servicebinding.services.cloud.sap.com`). If BTP Operator is not available meaningful status should be set in the CR.

**Comment by zhoujing2022** [comment]
- UI is under tests.
- Monitoring for metrics will be done before Golive.
