### ISSUE TITLE
Open internal docker registry for customers

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#18555]
**Description**
Provide a way to use in-cluster docker registry for hosting customer's images. 
As the registry is accessible with the node-port it should be possible to push the images from the developer's machine or from CI/CD agent using port forwarding. Provide a command in the kyma CLI to push images.

**AC**
 - [x] The registry backend could be also replaced with durable highly available storage
    - [x] https://github.com/kyma-project/docker-registry/issues/51
    - [x] https://github.com/kyma-project/docker-registry/issues/25 
 - [x] https://github.com/kyma-project/docker-registry/issues/38
 - [x] https://github.com/kyma-project/docker-registry/issues/82

**Reasons**
Pushing images directly to the in-cluster registry simplifies the development, testing and even production releases. 
Users should be able to easily deploy their code and run their tests without the need for additional BTP or hyperscaler services.
Currently a problem arises when users want to deploy their code to the cluster, due to the fact that there is no SAP registry available. Unlike with CF where a cf push does all the work necessary to deploy the code.

**Related Issues**
[Enable Registry Cache Extension](https://github.com/kyma-project/infrastructure-manager/issues/135)

**Comment by kwiatekus** [comment]
Allow serverless module users to configure custom HA store as serverless docker registry backend.
 - [ ] Users should be able to configure s3 secret via serverless CR
 - [ ] Users should be able to define Azure blob storage via serverless CR
 - [ ] User Should be able to use secret references for storage configuration fields (`valueFrom` k8s convention, `EnvVarSource` go type)
 - [ ] Provide necessary configuration for UI components in kyma dashboard
 - [ ] Add necessary documentation about this configuration possibility

**Comment by kwiatekus** [comment]
@pbochynski we see more and more reasons to extract docker registry into separate module. Any objections?

**Comment by pbochynski** [comment]
> @pbochynski we see more and more reasons to extract docker registry into separate module. Any objections?

The only problem I see is that the serverless module will not work out of the box. You would introduce the dependency to registry module or to external registry. But maybe it is another reason to consider changing serverless module in the way that it doesn't have to build a container. Just load function code from CR and cache dependencies on persistent volume.
What do you think?

**Comment by kwiatekus** [comment]
@pbochynski 
Thanks. That would mean that serverless runs pre-built containers as function runtimes with code dependencies mounted. dependencies resolving would need to be moved from built time into runtime ( start time ). There is a consequence in function scaling scenario: i.e when a new replica starts it would need to resolve dependencies ( i.e npm install ) into a mounted volume. In theory, replicas could have different versions of dependencies. But if we consider serverless being dev module only that should be ok.

**Comment by kwiatekus** [comment]
Separate reconciler for docker registry has already a first working version developed in the dedicated repository
https://github.com/kyma-project/docker-registry

The team is also looking into using the latest version of distribution (a.k.a registry) from cncf -> https://github.com/kyma-project/serverless/issues/858

**Comment by pPrecel** [comment]
> > @pbochynski we see more and more reasons to extract docker registry into separate module. Any objections?
> 
> The only problem I see is that the serverless module will not work out of the box. You would introduce the dependency to registry module or to external registry. But maybe it is another reason to consider changing serverless module in the way that it doesn't have to build a container. Just load function code from CR and cache dependencies on persistent volume. What do you think?

I think, in this case, it would be nice to have one PVC for all functions, not to reserve space for every function. The problem is that almost all types of PVC are namespace-scoped so it would be impossible to use simple PVC. The only solution I see right now is to use [nfs](https://kubernetes.io/docs/concepts/storage/volumes/#nfs) (network-file-system) that allows to share volume between namespaces. It's something to investigate

**Comment by kwiatekus** [comment]
We have a separete docker registry operator.
Following recent feedback we will look into allowing using the module via docker CLI
https://github.com/kyma-project/docker-registry/issues/38

**Comment by kwiatekus** [comment]
Currently working on exposing docker regisrty via https ( https://github.com/kyma-project/docker-registry/issues/37) and configuring s3-compliant backend for storage (https://github.com/kyma-project/docker-registry/issues/25)

ETA On track

**Comment by kwiatekus** [comment]
We work on allowing setting up AWS or Azure storage for docker registry.
Next will be allowing GCS buckets & allowing configuring BTP secret as a Object Storage.
We are finalising exposing docker registry via https.

ETA on track

**Comment by kwiatekus** [comment]
Status update 15.07.2024
 - we are close to finish exposing docker registry via https (and thus enabling it to be used by docker CLI)
 - we enriched the documentation with use case description and hints about what target environments is docker-registry module suitable for
 - docker-registry (main) supports GCS as a storage backend

Next plans:
 - support BTP Object store as a backend
 - new 0.1.0 release and promotion to experimental channel

**Comment by kwiatekus** [comment]
Status update 29.07.2024

 - @kyma-project/otters completed the task to enable bto object store as a backend and allowing to use docker registry via docker CLI
 - we are now focusing on:
   - enabling NFS storage as a storage backend for docker-registry
   - hardening our CI/CD workflows on GH actions
   - publishing docker-registry to DEV and EXPERIMENTAL channels

**Comment by kwiatekus** [comment]
Status update 26.08.2024

@kyma-project/otters are working on feature completeness:
 - [x] UI configuration for kyma dashboard 
 - [x] NFS storage
 - [ ] (currently in progress) enabling custom gateway for external access (https://github.com/kyma-project/docker-registry/issues/106)
 
Additionally, from the DoD we are working on
 - [x] docker registry availability in DEV channel
 - [ ] E2E integration test of docker registry on SAP BTP (https://github.com/kyma-project/docker-registry/issues/127)
 - [ ]  docker registry availability in EXPERIMENTAL channel  

We estimate we need extra week to finish
New forecast: 06.09.2024

**Comment by kwiatekus** [comment]
Status update 09.09.2024

 - automated [e2e test](https://github.com/kyma-project/docker-registry/pull/160) for docker registry (using extracted tf [module](https://github.com/Cortey/terraform-module)) in review

**Comment by kwiatekus** [comment]
The docker registry is available for internal customers on canary landscape (via `experimental` channel ).

[What's new announcement](https://help.sap.com/whats-new/f0d108472a9347d99053658d05ae23e2?Valid_as_Of=2024-10-02:2024-10-02&locale=en-US&state=DRAFT&Environment=Kyma)
[Internal docs](https://help.sap.com/docs/btp/sap-business-technology-platform-internal/docker-registry-module?locale=en-US&state=DRAFT&version=Internal)
