### ISSUE TITLE
Support for multiple Kyma control planes [EPIC]

### ISSUE THREAD

**Issue by varbanv** [kyma-project/kyma#18626]
**Description**

Kyma control plane should support multiple connected and disconnected instances across different regions/hyperscalers/data centers.

**Reasons**

This would allow us to:

- improve resiliency
- reduce latency to managed clusters on different continents
- deliver service in air-gaped environments
- deliver service in locations with special data handling requirements

**Acceptance criteria**

- [ ] the full control plane can be released and delivered via a standard delivery channel
- [ ] control plane installation/upgrade/configuration is fully automated
- [ ] control plane maintenance, troubleshooting and second day operations is documented
- [ ] control plane can be deployed to a predefined set of hyperscalers and SAP DC

**Attachments**

- [Concept (internal issue)](https://github.tools.sap/kyma/backlog/issues/5419)

**Comment by janmedrek** [comment]
Moved to the [internal issue](https://github.tools.sap/kyma/backlog/issues/6316).
