### ISSUE TITLE
Kubernetes upgrade from ver 1.28 to 1.29

### ISSUE THREAD

**Issue by zhoujing2022** [kyma-project/kyma#18669]
**Description**
Currently kyma supports k8s `1.28`. As all dependencies are met we can support the next version `1.29`.

SRE k8s upgrade plan: https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=3011925416

Furthermore the support for next version should be prepared by already having a [post-main-k3d-k8s-preview](https://status.build.kyma-project.io/?type=postsubmit&job=post-main-k3d-k8s-preview) pipeline in place to identify problems fast and start addressing them.

**Tasks**
- [x] [k8s update] @TW Pre-Notification to Customers via [What's New](https://help.sap.com/whats-new/cf0cb2cb149647329b5d02aa96303f56?Component=Kyma%20Runtime&locale=en-US&Valid_as_Of=2024-08-09%3A2024-08-11). This Step must be done 4 weeks before Golive on PRD. (Before 14.July.2024)
- [x] [k8s update] @zhoujing2022  Ensure no deprecated resources exist which will be no longer support on the new K8s cluster
- [x] [k8s update] @neighbors Prow jobs are based on k8s `1.29` (see [neighbours issue](https://github.com/kyma-project/test-infra/issues/10579))
- [x] [k8s update] @neighbors Already existing release jobs (from last release) should be still using old k8s version. (see [neighbours issue](https://github.com/kyma-project/test-infra/issues/10579))
- [x] [k8s update] @neighbors Default version for kubectl is `1.29` (Docu, Prow) (see [neighbours issue](https://github.com/kyma-project/test-infra/issues/10579))
- [x] [k8s update] @TW document new version and add release notes ()

**AC:**
- all pipelines are upgraded to k8s `1.29`
- documentation is updated
- migration guide with potential manual actions is ready
- there is a new k3d based pipeline running on k8s 1.30 for preview purposes

The list of pre-tasks:
(POs analyze  "Kubernetes Removals, Deprecations, and Major Changes in 1.29" - and create/add the issues below. These Issues must be released before 13.July.2024 on PRD.)
No Update from the teams.

|Teams|Issues|
| ---- | ---- | 

Previous upgrade: https://github.com/kyma-project/kyma/issues/18558

Depends on https://github.com/kyma-project/test-infra/issues/6109

**Comment by zhoujing2022** [comment]
We don't need this ticket in the future. I will add the action item in the upgrade timeline.
