### ISSUE TITLE
Configurable multiple node pools [EPIC]

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#18709]
**Description**
Kyma clusters should support multiple machine types simultaneously. For example GPU and ARM nodes, network, memory and CPU optimized nodes, etc.

Acceptance criteria:
- [x] [KIM supports multiple node pools](https://github.com/kyma-project/infrastructure-manager/issues/46). Each pool has machine type, autoscaler (min/max), and HA related settings (zones or HA on/off)
- [x] KEB supports multiple node pools with the input parameters that can match KIM settings.
- [x] new settings (input parameters for KEB) should be backward compatible
- [x] ~metering is adjusted to different node types with a multiplying factor that reflects price differences (e.g. GPU has factor 2.0)~ -> descoping as it's addressed in https://github.com/kyma-project/kyma/issues/18195
- [x] ~image builder can produce multi architecture images (amd64 and arm64) https://github.com/kyma-project/test-infra/issues/12583~. -> moved to https://github.com/kyma-project/kyma/issues/18195

**Reasons**
Our customers demand ARM and GPU nodes in Kyma clusters to run their workload on the architecture supporting their use cases. Examples:
- running applications that require GPU like [NVIDIA Omniverse](https://www.nvidia.com/en-us/omniverse/)

**Related issues**
- https://github.com/kyma-project/infrastructure-manager/issues/46
- #18195 
- https://github.com/kyma-project/infrastructure-manager/issues/364
- https://github.com/kyma-project/kyma-environment-broker/issues/952
- https://github.com/kyma-project/test-infra/issues/12583
- #18770

**Comment by tobiscr** [comment]
Feedback from stakeholders:

@ebensom : 
from operational side, we should not expose all worker-pool configurations of the Shoot spec (e.g. each worker can have different linux-image versions which can lead to security implications).

@varbanv  :
* Customers want to be able to configure different worker pools with different configurations (e.g. arch, sizes, gpu etc.) 
*Conclusion:*
    1. expose everything(?) in regards to machine types (not needed from day 1 - we can add machine types when customer requests them)
    2. deal properly with billing (costs perspectives are very different between machine types and change frequently)
* Workload has to run on particular worker pool (e.g. for cost saving purposes)
*Conclusion:*
    1. worker pool affinity required
    2. Kyma runs always in its own worker-pool (only limited configurable by customers) to separate Kyma workloads from customers
    3. customers can add additional worker pools which can be (fully) configured by them
    4. we accept the risk that it's not guaranteed that a machine type is in each region available (depends on hyperscaler)
    5. it's acceptable to make the worker-pool configurable outside of BTP cockpit (e.g. via kubectl calls - technical feasibility has to be clarified)
    6. we have to deal with issues reported by Gardener properly and expect failure cases (e.g. machine type not supported in particular region) which have to be reported to customers
    7. We start with a predefined list of machine types and we extend it when a need becomes visible

**Comment by tobiscr** [comment]
**Next steps / Action items:**

@PK85  + @ebensom : decide on the configruation options we are exposing for customers and track it in this issue

**Comment by marco-porru** [comment]
In general, I see a bigger demand for GPUs explicitly requested by different teams, some about AI, others for ML algorithms. The scope, in any case, is always to have dedicated nodes to run specific tasks.

Reasonable also to include m6g and m6in (or the current available generation) for SAP for Me
One note on g5 and r7i this is required for SAP Intelligent Product Recommendation

**Comment by PK85** [comment]
@tobiscr 
1) @PK85 + @ebensom : decide on the configruation options we are exposing for customers and track it in this issue

We will go simple on KEB side. We will keep those parameters on root for system node pool:
```
"autoScalerMax": ...
"autoScalerMin": ..
"machineType": ..
```
NOTE: this is always HA min 3 nodes. We need to decide how to name that worker node pool, probably we use some name right now.


and new array or worker nodes for customer usage:
```
ArrayOf [
"autoScalerMax": ...
"autoScalerMin": ..
"machineType": ..
]
```

**Comment by ChristophRothmeier** [comment]
Hello,
my name is Christoph, i am project manager for Ingentis and we are using kyma running on SAP BTP. (currently running 10 clusters in 4 different landscapes).
We are also looking forward to having different node pools in kyma, with the following use case:

We have some workloads, that require a very high amount of memory in a single operation. The requirements can go up to 128 GB of RAM. Of course we do not want to run all nodes of our cluster with 128 GB machines, cause this would be very expensive. The operations itself can not be optmized with low effort (We are generating large export files for power point and PDF and the third party libraries we are using for this, do not support streamed or chunked exports, they require to hold all in memory).

So for us it would be important to have system node pool with small machines (like 16 GB or 32 GB) and than an additional node pool for the heavy workloads (like 128 GB machines). It would be important for us to be able to scale down the additional node pool to zero, cause we only need the expensive machines in case there are heavy workloads. So in the moment a user queues in a heavy workload, we would spawn a pod on the additional node pool, the node pool should scale up, executes the workload (which typically needs some hours) and then scale down to zero, after the workloads are done.

We do not require to have new machine types, like GPU or ARM machines.

I hope this is a state we can reach at some point. As I understand, it's currently planned to release additional node pools with HA , so they have to have at least 3 nodes permanently, without the option to scale to zero?

Kind regards,
Christoph

**Comment by tobiscr** [comment]
Hi @ChristophRothmeier , thanks for your request. 

The multiple worker pool feature is currently in implementation and will be rolled out till end of this year. The list of supported machine types is at the beginning not extended and includes the same machine types as we offer when creating a new Kyma runtime via BTP cockpit. But support for additional machine types is already agreed and will be added soon after the worker pool feature is productive.

For go-live, we will also offer only worker pools with HA support (means, 3 nodes are the minimum). Scaling to 0 nodes is with a HA-supporting worker pool not possible but can be achieved by dropping the worker pool and re-creating it afterwards.

We are already in discussions to allow non-HA supporting worker pools with < 3 nodes. Such pools would also allow a scaling to 0 nodes.

**Comment by ChristophRothmeier** [comment]
Hi Tobias,

thanks for the response.
for us it would be huge, to have the ability to scale down additional worker pools to zero with non-HA support. Could you send an update in this issue as soon your discussions about this topic have progressed and it is clear if and when it will be implemented?

Thanks
Christoph

**Comment by ChristophRothmeier** [comment]
Hi @tobiscr 
Beeing able to scale additional worker nodes to minimum of 1, would already be a huge benefit compared to beeing forced into HA with minimum 3 nodes.

For example, we are currently running 64 GB nodes in some locations, cause some single heavy workloads need that much of RAM. With additional worker nodes beeing able to be scaled to 1, we could downsize the main machines to 16 GB, with an additional worker pool with 1x 64 GB machine (scaling up to more dynamically on more workload).
So we could reduce from 192 GB in total down to 112 GB in total with 3 x 16 GB and 1 x 64 GB. That would already save us a lot of resources, and would be a huge benefit for us.

**Comment by tobiscr** [comment]
@ChristophRothmeier : please excuse the delayed reply. I also want to apologise that customised worker pools are still not consumable on production. We are currently integrating and testing the new feature on our development landscapes.

For reducing costs / adjust sizes of worker pools, we agreed on following approach:

* Kyma runtimes which have HA support (this is the default case for productive clusters) will provide an option to disable the HA mode. Such worker-pools require just 1 worker node.
* It will be possible, to change a worker-pool from non-HA to HA mode , which requires to have permanently at least 3 worker nodes. It will not be possible to disable the HA mode afterwards (it would require to re-create the worker-pool with non-HA mode).

There is a risk that the first released version of the worker-pools is not including the non-HA configuration option, but this feature is on top of our backlog and will be delivered next.

**Comment by ingentismg** [comment]
Hi @tobiscr,

I am part of Christoph's team and currently evaluating the worker node pool, that was released a few days ago.
In a related GitHub issue we found that we could schedule pods for the worker node pool using a _nodeSelector_ and the node label _worker.gardener.cloud/pool_ with the pool name.

Something I am currently unsure of, is how to best prevent other workloads from deploying in the pool.
Would it be possible to extend the pool configuration with custom node taints? This would probably be the easiest way for the end user, not sure if this would work with the required Kyma components that have to deploy in the pool as well.

The only other alternatives I can think of:
Use a _nodeSelector_ for the main pool, but there is no officially documented name for it. Is it **always** in any landscape, for any provider guaranteed to be _cpu-worker-0_?
Otherwise we would have to use an anti-affinity for the additional worker node pool. But that would also mean extending the configuration if we ever add new pools.


Thanks and best regards,
Marcus

**Comment by tobiscr** [comment]
Hi @ingentismg,

thanks for reaching out! As indicator for the default worker-pools, I can confirm that the usage of the label `worker.gardener.cloud/pool: cpu-worker-0` is the best option. This label is used in all Kyma runtimes and indicates the default worker pool (this pool always exists and cannot be removed) . There are no plans to rename it.

Regarding the options to assign workloads, you already mentioned them, just for completeness:

* You can define the preferred worker-pools (using [nodeSelector](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector) or [node affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity))
* Or define the worker-pools which should be avoided (using a negated node affinity or anti affinity)
* To enforce workloads to run only on defined worker pools, using a `nodeSelector` or `requiredDuringSchedulingIgnoredDuringExecution` are a good option. If no matching node can be found, the pods won't be scheduled.

Many thanks for the hint of the missing documentation of assigning workloads to worker pools. We will extend it accordingly.

If you are looking for more information, we can also setup a short call to clarify further details.

Best regards, Tobias

**Comment by ingentismg** [comment]
Thanks for the confirmation on the default pool name @tobiscr!
We will proceed to implement a nodeSelector targeting `cpu-worker-0` for anything that should not run in another pool.

**Comment by tobiscr** [comment]
Hi @ingentismg , UR welcome. We discussed today the current situation in our team an we agreed to introduce a dedicated label for the Kyma worker pool and customer owned worker pools.

This will decouple the affinity-rules from the worker-pool names.

https://github.com/kyma-project/infrastructure-manager/issues/706

**Comment by tobiscr** [comment]
> Thanks for the confirmation on the default pool name [@tobiscr](https://github.com/tobiscr)! We will proceed to implement a nodeSelector targeting `cpu-worker-0` for anything that should not run in another pool.

Many thanks. For now, please use the worker-pool name (`cpu-worker-0`)  as differentiator between yotr worker pools an the Kyma worker pool. This name won't change soon. For the longterm, switching to the label described in https://github.com/kyma-project/infrastructure-manager/issues/706 could be beneficial.

**Comment by ingentismg** [comment]
> Many thanks. For now, please use the worker-pool name (`cpu-worker-0`) as differentiator between your worker pools an the Kyma worker pool. This name won't change soon. For the longterm, switching to the label described in [kyma-project/infrastructure-manager#706](https://github.com/kyma-project/infrastructure-manager/issues/706) could be beneficial. This feature is added to our backlog and will be groomed soon.

Well, that already solved my follow up question. Thanks for the additional clarification!
I will watch the mentioned issue and (potential) SAP what's new announcements for when this is ready and we can switch.

Thanks again!

**Comment by tobiscr** [comment]
Update documentation to cover node affinity / antiAffinity for assigning workload to worker-pools: https://github.com/kyma-project/infrastructure-manager/issues/709

Closing this EPIC as rollout is completed. Enhancement and follow-up actions are managed in separate issues.
