### ISSUE TITLE
Monitoring - Documentation improvements

### ISSUE THREAD

**Issue by bszwarc** [kyma-project/kyma#2680]
**Description**

The goal of this task is to have a set of well-documented topics related to observability area. This includes:
- Monitoring documentation

We would have two sets of documents: for end users and developers. 

## User documentation

User documentation: (currently: https://kyma-project.io/docs/components/monitoring) 
- [x]  Add a topic under Kyma to describe observability in general. Add a diagram, overview and links to observability topics.
- [x] Extend the existing monitoring documentation. Use case:
The user wants to collect specific metrics, create a dashboard to monitor them and create alerts and notifications based on metrics. 
Topics:
   - [x]  Improve Architecture /Overview (component description) Add a short topic describing the flow.
   - [x]  How to expose metrics (tutorial)
   - [x]  How to expose custom metrics (tutorial)
   - [x]  How to configure Prometheus to poll metrics (tutorial)
   - [x]  How to create and configure a Grafana dashboard (tutorial)
   - [x]  What is Alertmanager and how to configure alert rules in Alertmanager (tutorial)
   - [x]  How to define the channels for sending alert notifications (tutorial)

   
  

Stretch goal - developer documentation (see also: https://github.com/kyma-project/kyma/issues/1879)
Have developer guidelines addressing monitoring:
- [x] How to add a dashboard

------
This should be done as part of the metrics documentation: 
- [ ] List of standard and custom metrics for each component type

**Reasons**
- Observability topics covered in the documentation
- Well-written tutorials provide the end-users with necessary configuration details
- Developer guidelines allow devs to define their own dashboards, use and expose custom metrics 

**Additional information**
Kube-prometheus: https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus
Prometheus Operator: https://github.com/kyma-project/kyma/tree/master/resources/prometheus-operator
Grafana: https://github.com/kyma-project/kyma/tree/master/resources/monitoring/charts/grafana
Alertmanager: https://github.com/kyma-project/kyma/tree/master/resources/monitoring/charts/alertmanager
Alert rules: https://github.com/kyma-project/kyma/tree/master/resources/monitoring/charts/alert-rules
List of component types: https://github.com/kyma-project/kyma/tree/master/components

**Comment by bszwarc** [comment]
Also include docu changes from: https://github.com/kyma-project/console/issues/343

**Comment by bszwarc** [comment]
It's done, closing the ticket.
