### ISSUE TITLE
Octopus in Kyma testing.sh - new test runner

### ISSUE THREAD

**Issue by sjanota** [kyma-project/kyma#2946]
**Description**
Running tests via helm is painful as it does not allow a number of features which help with development. Some of missing features are:
 - running specific tests only
 - running them specific number of times

Because of that there is ongoing effort to implement new test runner for Kyma tests. The project is called [Octopus](https://github.com/kyma-incubator/octopus) and is still in incubator phase. In our acceptance tests we should add support for running tests using Octopus. Both definitions (helm and octopus may exist in the same time). 

**Reasons**
1. `helm test` with `testing.sh` script is not exactly developer-friendly. We can do better with Octopus.
2. To find out how Octopus could evolve to be most valuable we need to have real test scenarios. Thanks to that we will be able to compare it with current approach and see what to do next.  

**ToDo**
- [ ] add octopus into Kyma installer
- [ ] modify testing.sh to use octopus
- [ ] find a place where to put CR TestSuite
- [ ] rewrite one helm test pod into octopus CR
- [ ] create a branch with changes (check PR GKE-integration)
- [ ] use some cluster with stability checker
- [ ] rewrite all helm pod tests and do a cleanup
- [ ] if everything works as expected create a follow up ticket to release that feature

**Comment by PK85** [comment]
ToDo:
- add octopus into Kyma installer
- modify testing.sh to use octopus
- find a place where to trigger
- rewrite one helm test pod into octopus CR
- rewrite all other pod tests and do a cleanup
-
