### ISSUE TITLE
Kyma-CLI as default way of local installation

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#3005]
# Motivation
With [Kyma-CLI](https://github.com/kyma-incubator/kyma-cli) developers will have a convenient way to manage a Kyma installation, supporting multiple operating systems in a tested and maintainable way.
In order to leverage all the advantages, we need to stop developing the existing scripts and motivate people to use the CLI.

# Goal
Deprecate all scripts for local Kyma installation and use Kyma-CLI instead

# Details
Relates to https://github.com/kyma-project/kyma/issues/3997

The recommended way of installing kyma local is to use the [run.sh](https://github.com/kyma-project/kyma/blob/master/installation/cmd/run.sh) script. That script should be deprecated with a big fat deprecation message pointing to the new approach and specifying a specific release as end of life.
Same should be applied to all sub-sequent scripts which are used only in the context of local installation.

On the other hand, the CLI needs to be introduced to the documentation. So proper requirements need to be specified in all guides, same as for kubectl. Then the existing guides need to be adjusted to use the CLI instead of the scripts.

# Action Items
- [x] Rewrite guides for local installation to use CLI instead of script
  - [x] local installation from release (https://github.com/kyma-project/kyma/issues/4047)
  - [x] local installation from source (https://github.com/kyma-project/kyma/issues/4047)
  - [x] re-install local kyma (https://github.com/kyma-project/kyma/issues/4047)
  - [x] search once more for occurences and fix them (https://github.com/kyma-project/kyma/issues/4047)
  - [x] assure that we reflected latest changes on installation simplifications (https://github.com/kyma-project/cli/issues/87)
- [ ] Deprecate scripts and replace usage
  - [x] Add deprecation message to the relevant scripts (https://github.com/kyma-project/kyma/issues/4047)
  - [ ] adjust prow integration test to use CLI binary (https://github.com/kyma-project/kyma/issues/4048)

**Comment by Morriz** [comment]
Wouldn't it be great if the kyma-cli would be generated somehow? So it would always work out of the box with the release that shipped it?

**Comment by Morriz** [comment]
If I look at gcloud and other mature packages I think that is what they do too.

**Comment by a-thaler** [comment]
Nice idea, we will keep it in mind. In general we need to avoid as much as possible logic in the CLI to keep it decoupled and lightweight. Will take a deeper look into gcloud for that.

For now, our main goal is to replace any script in the kyma-project by the CLI to have it more maintainable, portable and testable and more convenient to use.
