### ISSUE TITLE
Align with Open standards for Kyma eventing interfaces

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#3849]
## CloudEvents
Kyma eventing interfaces were designed with a pre-release version of [CloudEvents Specification](https://github.com/cloudevents/spec). Over a period of time this specification has evolved and we should have the Kyma eventing interfaces aligned with the latest stable specifications of CloudEvents.

Supporting CloudEvents specification would imply:
- [ ] One should be able to use a CloudEvents based SDK to send events to Kyma
- [ ] One should be able to send an event over HTTP that conforms to CloudEvents specification. For this we need to support both:
  - [ ] Structured mode
  - [ ] Binary mode
- [ ] One should be able to use a CloudEvents based SDK to consume an event

**Comment by pbochynski** [comment]
@Abd4llA @abbi-gaurav Can we close this epic?

**Comment by anishj0shi** [comment]
event-mesh is completely compliant to cloudevent v1.0. and all the events received on */events* endpoint can be eithe encoded with structured or binary encoding as they are based on cloud-event sdk receiver.
