### ISSUE TITLE
Kyma-CLI as part of the Kyma family

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#3997]
# Motivation
With [Kyma-CLI](https://github.com/kyma-incubator/kyma-cli) developers will have a convenient way to manage a Kyma installation, supporting multiple operating system in a tested and maintainable way.
In order to leverage all the advantages of the existing CLI we need to integrate it to the official Kyma project.

# Goal
Integrate Kyma-CLI to the kyma-project organization and integrate it to the release process

# Details
In order to use it as the default tool for installation (https://github.com/kyma-project/kyma/issues/3005), it should be an official tool for kyma. Otherwise users will be irritated.

So it needs to be moved from a technical perspective, it needs to be integrated into the community process and it needs to be integrated to the release process.

# Action Items
- [ ] Implement last pieces in CLI which are provided by local installation scripts
  - [x] Specify custom admin password (https://github.com/kyma-incubator/kyma-cli/issues/36)
  - [x] Support of custom installer CR (https://github.com/kyma-incubator/kyma-cli/issues/40)
  - [x] Support of knative mode (https://github.com/kyma-incubator/kyma-cli/issues/38)
  - [x] Support for minikube restart (https://github.com/kyma-incubator/kyma-cli/issues/47)
  - [x] Support of latest minikube version (https://github.com/kyma-project/cli/issues/76)
  - [x] review of CLI command structure and options incl. help text (https://github.com/kyma-incubator/kyma-cli/issues/39)
  - [x] security issues (https://github.com/kyma-project/cli/issues/71, https://github.com/kyma-project/cli/issues/69, https://github.com/kyma-project/cli/issues/68)
  - [x] quality issues (https://github.com/kyma-project/cli/issues/80)
- [ ] make it part of the family
  - [x] move git repo to kyma-project organization (https://github.com/kyma-project/kyma/issues/4044)
  - [x] have all opens source/community requirements fullfilled, see [template](https://github.com/kyma-project/community/tree/master/guidelines/internal-guidelines/repository-template) (https://github.com/kyma-project/kyma/issues/4044)
  - [x] have release requirements fullfilles (threat modelling, license scan, security scan) (https://github.com/kyma-project/kyma/issues/4046)
  - [x] have automated release process in place (https://github.com/kyma-project/kyma/issues/4045)
  - [x] Have it integrated to the kyma release process from an organization perspective (https://github.com/kyma-project/kyma/issues/4045)
  - [ ] Have it installable via official homebrew tap (https://github.com/kyma-project/kyma/issues/4037)
