### ISSUE TITLE
Connector Service integrated with Compass

### ISSUE THREAD

**Issue by crabtree** [kyma-project/kyma#4723]
Connector Service component integrated with Compass
- provide support for GraphQL API
- connector when pairing with application expose URL for application, where all Runtime specific information like EventService URL is provided

**What should be done:**
- [x] Connector implementation
   - [x] implementation
   - [ ] integration tests
   - [ ] chart
- [x] Gateway proxy implementation
- [ ] Runtime Agent side implementation 
   - [ ] implementation
   - [ ] tests
   - [ ] config map job
