### ISSUE TITLE
Create a Function controller module in Kyma

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#4803]
**Description**

Create an experimental optional module for Kyma function controller and move the code of https://github.com/kyma-incubator/runtime into Kyma as a component. 

**Tasks**

- [x] Migrate controller from incubator into components repo (kyma/components)
- [x] Implement Prow Job to create Controller Image (test-infra)
- [x] Create an Installer Module for Function Controller (kyma/resources) (Handled here: https://github.com/kyma-project/kyma/pull/4924)
- [-] Acceptance  testing (kyma/test)(Not possible in the current scope. Handled via: https://github.com/kyma-project/kyma/issues/5147)

**Comment by bszwarc** [comment]
Documentation for the module? We have some here:
- https://github.com/kyma-project/kyma/tree/master/components/knative-function-controller

but if we want/need to have some on the website we need to do it properly.
