### ISSUE TITLE
Kyma bundles repository for helm broker

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#592]
Helm broker by default will point to new bundle repository.

Business requirements:
- new repo in kyma-incubator, or kyma with structure:
   - all bundles
   - local services only (e.g. Azure Broker, GCP Broker etc) right now only redis (default bundle repo for Kyma)
   - showcases (e.g. order-service, ec-lambda)
- integration with already configured travisCI or prow
- PR bot checking bundles compliance
  - if bundle contains some not needed files print error with files that causing problem
- solution for testing bundles with real kyma installation (SPIKE)
- failed bundle should not crash whole helm-broker catalog
- update kyma helm broker to use new repository
- remove kyma local provisioning
- update all related documentation (all occurrences of **ybundle, yBundle** to **bundle**)
- create follow up ticket to toads, to remove functionality from installer about sh calls

Technical requirements:
- [x] new bundles repo with integrated travis CI
- [x] PR bot checking bundles compliance https://github.com/kyma-project/bundles/pull/9
- [x] Adjust helm broker checker: if bundle contains some not needed files print error with files that causing problem https://github.com/kyma-project/kyma/pull/1210
- [ ] failed boundles should not crash whole helm-broker catalog, change yBundles to bundles in the helm broker docs, add a section about configuring helm broker repo URL in the docs #1180 
- [x] update helm broker to use new repo, remove embedded reposerver with all related docs #1010 
- [x] create follow up ticket about cleaning up installer (remove provisioning embedded reposerver) #1181 
- [ ] add tutorial about creating a bundles fork https://github.com/kyma-project/bundles/pull/8
- [x] bundles repo documentation

**Comment by Tomasz-Smelcerz-SAP** [comment]
Please remember to remove "helm-broker-repo/install.sh" and "provision-bundles.sh" scripts from Kyma since it is the only Kyma component that requires bash invocation and there's substantial amount of legacy code in Installer just to handle this case.

**Comment by PK85** [comment]
Hello @Tomasz-Smelcerz-SAP, 

we will grab that issue at the beginning fo the MS10.

 Cheers, PK

**Comment by piotrmiskiewicz** [comment]
What should be done:
- [x] Create and initialize bundles repository with configured Travis CI. 
- [ ] Add sources of targz tool and make builds in CI
- [ ] PR bot checking bundles compliance
- [ ] Configure Kyma to use the stable repository and remove helm-broker-repo (image and scripts).
- [ ] make helm-broker resync more user friendly. Currently we have to edit config map, delete the helm-broker pod then trigger resync service-catalog. It must be simplified
- [ ] update all related documentation
