### ISSUE TITLE
Integrate new monitoring chart with all modules

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#6124]
**Description**
This is the follow-up of https://github.com/kyma-project/kyma/issues/4520

After we have the basic monitoring chart working assuring all general topics, like upgradability and documentation, now it is time to verify that all former customizations are working and that all modules are using proper structure and naming

- [x] Adjust the documentation with updated configuration data and merge the configuration into one document as there is only one values.yaml now
- [x] Check that istio telemetry data is available
- [x] Assure all dashboards are still working as before
- [x] Check that all dashboards are bundled along with the related module with consistent naming. Assure that all dashboards are bundled in its own resource -> check if https://github.com/kyma-project/kyma/issues/5830 can be closed
- [x] Assure all alert-rules are working as before
- [x] Check that all alert-rules are bundled along with the related module with consistent naming.
- [x] Assure that all ServiceMonitor targets are working as before
- [x] Check that all serviceMonitors are bundled along with the related module with consistent naming.
- [x] Check if the dashboards are bundled and working which are mentioned here: https://github.com/kyma-project/kyma/issues/3512
- [x] Assure all exporters are minimal the same as before
- [x] Check if https://github.com/kyma-project/kyma/issues/1794 can be closed or refine if not (nothing changed for this issue)
- [x] Check if https://github.com/kyma-project/kyma/issues/4214 can be closed. If not, check that it is solvable and refine the ticket (nothing changed for this issue)
- [x] Check if https://github.com/kyma-project/kyma/issues/5654 can be closed, otherwise re-fine
- [x] Default "kubernetes pod" grafana dashboard does not work for prometheus volume as the relevant metric gets returned by two different endpoints (kubelet and monitoring-kubelet)
- [x] Assure that prometheus pod is not crashing for 7 days in operation
- [x] Re-enable prometheus and grafana backup tests and make sure they pass
- [x] Re-enable monitoring integration test and make sure it passes
- [x] Adjust monitoring example

**Reasons**
The monitoring functionality must work the same as before, using a consistent approach

**Comment by suleymanakbas91** [comment]
Some things not to miss:
- Replace the usage of [this file](https://github.com/kyma-project/kyma/blob/1c4c7390617114ea7b28bcfe5664691e4a6d2384/resources/monitoring/charts/alertmanager/templates/alertmanager.config.yaml) and the config values of `global.alertTools.credentials.slack.apiurl` and `global.alertTools.credentials.slack.channel`. These are used in test-infra!
- Create values.schema.json for the new charts

**Comment by suleymanakbas91** [comment]
I added customization comments to a couple of files that I could find: https://github.com/kyma-project/kyma/pull/6176/commits/35819d6f5fafcf518ad31ef620a7f4abd24d3ece
We should ideally have this comment everywhere we have customizations so that when we want to upgrade, it will be easy to know what we changed.
Also, we should document this in the readme..

**Comment by suleymanakbas91** [comment]
I changed the coredns service ports to make it work on GKE: https://github.com/kyma-project/kyma/pull/6176/commits/b68958968bec87bc00bc02e20b8a51151835dd87 
This makes the solution gke-dependent. We should look for a better way.

**Comment by suleymanakbas91** [comment]
Loki and Helm Broker targets are down. 
There are some changes related to metrics scraping in Loki. Updating the Loki chart to the latest may solve this problem: https://github.com/grafana/loki/tree/master/production/helm/loki/templates

**Comment by a-thaler** [comment]
I covered documentation leftovers in 
Documentation follow-up is here: https://github.com/kyma-project/kyma/issues/6674
