### ISSUE TITLE
Integrate Rafter and remove Asset Store and Headless CMS

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#6239]
**Description**

- `Change installation`: 
  - remove old `assetstore` and `cms` charts and replace with rafter chart
  - figure out where to place CRDs
- `console-backend-service`
  - add new or modify existing query that instead of docstopics reads assetgroups
- `application-connector`
  - contribute to application connector so it doesn't create docstopic but assetgroups
  - probably integration with upload service will also require update
  - compas runtime agent contribution
- `helm-broker`
  - contribute to the broker to make sure it creates assetgroups and not docstopics. 
  - talk to owners to make a release once change is in the master
- `console`
  - service catalog views and docs ui should fetch documentation and specifications from a new query
- `website`
  - searching for new `rafter` apiGroup in `content-loader-tool` and change to assetgroups
- modify existing or create missing backup tests and upgrade test 
- create very simple integration test that just creates an assetgroup, to make sure integration of rafter works fine
- have migration jobs of existing resources to the new ones
- Release notes with clear description of what we are doing
- `MinIO Gateway` - we use asset-store-overrides to switch to MinIO Gateway mode (4 tutorials) so we must adjust Secret and ConfigMap to work with rafter-overrides.
- `Custom metrics & dashboards` - check and adjust Asset Store and Headless CMS custom metrics & Garafana dashboards.

Stretch:
- instead of using default bucket for AssetGroups consider introduction of mutation webhook that basing on a label we agree on, will mutate created AssetGroup by adding a custom bucket we created for Kyma use case - topic for discussion

**Reasons**

Asset Store and Headless CMS got integrated into single standalone project called Rafter. Now Kyma need to migrate to use Rafter

**Human resources**
- [x] `installation` - @magicmatatjahu
- [x] `console-backend-service` - @magicmatatjahu
- [x] `application-registry` - @m00g3n
- [x] `compass-runtime-agent` - @m00g3n
- [x] `helm-broker` - @pPrecel
- [x] `console` - @magicmatatjahu 
- [x] `website` - @magicmatatjahu 
- [x] `integration-test` - @aerfio 
- [x] `backup-test` - @michal-hudy 
- [x] `upgrade-test` - @magicmatatjahu 
- [x] `migration-job` - @magicmatatjahu 
- [x] `MinIO Gateway (overrides)` - ___
- [x] `Custom metrics & dashboards` - @pPrecel
- [x] `docs` - @mmitoraj & @kazydek
- [x] `release notes` - @mmitoraj & @kazydek

**Comment by magicmatatjahu** [comment]
For `integration`, `upgrade`, `backup` and acceptance in `console-backend-service` we should create something like a `testingUtils` package for creating resources, deleting, waiting for Ready status etc. We have a duplicated code for that in mentioned tests, so separate package in `rafter` project would be the best option for tests.

**Comment by derberg** [comment]
@kazydek @mmitoraj my input for release notes:

```
## Asset Store aka Rafter

Last 2 months we focused on refactoring Asset Store and Headless CMS components. Our goal was to:
- Optimize those component for resources consumption 
- Move those components to separate repository as they do not depend on Kyma. As a result we wanted to have an independent project with its own release cycles and opened for wider community.

During refactoring we noticed that after few months of development and changes in Headless CMS (that was built on top of Asset Store) it is generic enough so that it can become a part of Asset Store. We renamed DocsTopic CR to AssetGroup. As a result we got a single controller manager instead of two we had in the past. The final result is that we merged those 2 components in one under new name [Rafter](https://github.com/kyma-project/rafter/).

Thanks to the fact that we use [MinIO](https://min.io/) as a backend for Rafter, we get a S3-like files/assets store, all managed with [CRDs](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/).

This release introduces Rafter in Kyma. For more details read [the docs](https://kyma-project.io/docs/components/rafter/). To make sure the switch is seamless we prepared an automated migration for your convinience. For more details see the [Migrations and upgrades](#migrations-and-upgrades) section.

## Migrations and upgrades

As mentioned in section [Asset Store aka Rafter](#asset-store-aka-rafter), old components are replaced with new. The most visible change is that DocsTopic and ClusterDocsTopic [CRDs](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/) are removed and replaced with AssetGroup and ClusterAssetGroup [CRDs](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/). When migrating from Kyma 1.8.0 to 1.9.0 we will automatically:
- Duplicate all old resources in new component, under new name and apigroups
- Duplicate all the files from system buckets (used by Upload service) in new Minio instance to assure any recovery of Assets created by Application Registry
- After successful migration the Asset Store and Headless CMS components will be removed.

Because of necessary data duplication and also the need of runing all components during upgrade, make sure your cluster has needed resources. The migration scripts are available [here](TODO link to location of migration scripts once they are merged)
```

What do you think?

**Comment by mmitoraj** [comment]
Looks gOOOd :)
