### ISSUE TITLE
Remove testing.sh script

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#6387]
**Description**
testing.sh script will be removed from Kyma. Instead, there will be a solution based on the Kyma CLI.

So instead you should call something like:
```
kyma test run --watch
kyma test logs
```

## TODO
- [x] Add watch option for `kyma test run` command (https://github.com/kyma-project/cli/pull/296)
- [x] Add functionality for fetching logs from test suite (https://github.com/kyma-project/cli/pull/297)
- [x] remove the injectTestingAddons from test scripts (https://github.com/kyma-project/kyma/issues/6253)
- [x] remove the dex static user selective testing from test scripts (https://github.com/kyma-project/kyma/issues/825)
- [x] have latest stable binary available for CI Jobs (https://github.com/kyma-project/cli/issues/294)
- [x] update the prow testing script to use the latest stable binary (https://github.com/kyma-project/cli/issues/294)
- [x] update the release process of Kyma to include the information about switching the latest stable binary (https://github.com/kyma-project/cli/issues/294)
- [x] Adjust kyma documentation (https://github.com/kyma-project/kyma/issues/8190)
- [x] mark [testing.sh](https://github.com/kyma-project/kyma/blob/master/installation/scripts/testing.sh) script as deprecated
- [ ] imform clients and and help them with migration
- [ ] assure that all prow jobs are either using the kyma-testing.sh script or adjust them to the CLI as well (https://github.com/kyma-project/kyma/issues/5182) (https://github.com/kyma-project/kyma/issues/5182)
- [ ] assure stability-checker is using CLI
- [ ] decide what to do with the [e2e-testing.sh](https://github.com/kyma-project/kyma/blob/master/installation/scripts/e2e-testing.sh)
- [ ] remove testing.sh from Kyma

**Reasons**
We want to get rid of all scripts in the kyma /installation folder as they are not portable, testable and hard to maintain. Instead the functionality should be covered by the Kyma CLI

**Comment by a-thaler** [comment]
Will be finsished in overall kyma 2 cleanup
