### ISSUE TITLE
Knative Kafka Channel integration

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#6757]
**Description**
Integrate and add support for [Knative Kafka channel](https://github.com/kyma-incubator/knative-kafka). This means we need
- [ ] Kafka channel chart
- [ ] CI job for Azure
- [ ] Kyma tests running on the Azure CI job
