### ISSUE TITLE
Runtime Agent synchronizes API-Packages

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/kyma#7040]
**Description**

To go along with the API-Packages functionality we need a way to synchronize them with the state present in Compass Director. Runtime Agent is responsible for fetching their definitions from MPS and applying them onto the cluster.

The handling of API-Packages is out of Agent's scope though - this will be done by brokers and/or catalog.

**Acceptance Criteria**
- API-Packages synchronization available in Runtime Agent
- API-Packages list is fetched from Compass Director
- Application CR is properly built from the definition (resulting in one service class per package)

**Subtasks**
- [ ] Compass Runtime Agent handles API-Packages (feature flag) - @akgalwas 
- [x] Fix problem with application CR - @akgalwas 
- [ ] Compass Runtime Agent acceptance tests updated (feature flag)

**Comment by akgalwas** [comment]
The mapping in Application CRD will be as follows:
- API package->service
- API in a package->entry in a service

API specifications handling needs to be changed as well. Specs for one package will be included in one Cluster Asset Group.
