### ISSUE TITLE
Application Gateway - refactoring of proxy approach

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/kyma#7042]
**Description**

The current state of Application Gateway is not ideal - it is deployed in a system namespace, scaling is problematic and resource usage (Kubernetes services, pod's memory, and CPU) can be improved. With a few changes, we can achieve a state in which the workflow is simple, easy to understand for both users and developers and not depending on the resources contained in a single namespace.

The idea is to create a generic solution that would not strongly rely on Application CR. Information such as auth method or credentials to use, headers, query parameters or target URL can be passed along the call, ideally in path (so that internal Kyma URL that is called defines the way the call is proxied). This can be implemented in many ways, the proposed solution is to use path segments for each piece of information, or by pointing Application Gateway to corresponding binding / configmap.

With this approach, a single Gateway can handle many applications and services, there is an additional security measure that needs to be taken into consideration - we need a way to confirm that a request originating from given lambda or service has the privilege to call target URL.

**Acceptance Criteria**
- Application Gateway no longer uses Access Services
- Auth method, credentials and other required information are not tied to the Application entry, those should be passed with the call (multiple possible approaches, should be discussed and aligned with other components)
- Host verification implemented (check whether specific origin has the access to the target)
- Documentation, tutorials and links updated

**Subtasks**
- [x] Proxy refactoring - @Szymongib 
- [x] Gateway tests refactoring - @Szymongib 
- [x] Use the feature flag
- [x] Documentation updated
