### ISSUE TITLE
Application Gateway - deployment in customer's namespaces

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/kyma#7043]
**Description**

In order to preserve resources, we would like to deploy Application Gateway only when it is required. There is no point in maintaining a deployment in central namespace while no calls are made.

The goal of this task is to have a solution that deploys Application Gateway only when there is a case that requires it in a given namespace. Moreso - with the new proxy approach it should be deployed once per namespace, not per Application.

**Acceptance Criteria**
- Application Gateway is deployed within customer's namespaces
- Application Gateway is only deployed in namespaces containing active Service Binding Usages

**Subtasks**
- [x] ServiceInstance based controller - @Maladie 
- [x] Gateway deployment - @Maladie 
- [x] Add feature toggle - @Maladie 
- [x] Application Operator tests refactoring - @Maladie 
- [x] Documentation updated - @majakurcius 

Descoped: 
- [ ] Application Operator refactoring cleanup - @Maladie 
- [ ] Migration guide created
