### ISSUE TITLE
Improve the flow of how Function Controller creates resources

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#7359]
**Description**

Resources management in Function Controller definitely needs some ❤️ . There are multiple problems like the creation of `TaskRun` together with `KService`, not triggering the build when the runtime is changed, missing reasons for statuses, etc.

To improve the UX we needs to improve a bunch of issues.

Proposed flow:

**New Function**
1. Status: Building
    1. TaskRun is created
    2. Docker Image has a unique tag
    3. If not finished with success then status error is set with proper reason
2. Status: Deploying
   1. KService is created
   2. If KService is not ready with failed status then an error is set with proper reason
3. Status: Running
When KService is ready 😄 

**Update Function**
If something was changed that impact the docker image (source code, dependencies, runtime, etc.):
1. Old TaskRun is removed
2. New TaskRun is created
3. Docker Image has a new unique tag
4. KService is created (if not exits)/updated

If change is related only to KService:
1. KService is updated

In both cases, proper error status should be set in case of failure and Function shouldn't be served, because currently they are not versioned.

Name of the `TaskRun` shouldn't be based on Function SHA

>**HINT**: To generate unique names of TaskRuns, the `metadata.generateName` can be used (https://kubernetes.io/docs/reference/using-api/api-concepts/#generated-values)

>**HINT**: For detection, if something related to Docker Image has been changed SHA can be used that can be stored in annotation or status.

>**HINT**: For searching of previous `TaskRuns` labels can be used

**Reasons**

Improve UX and lambdas creation stability

**Attachments**

https://kubernetes.io/docs/reference/using-api/api-concepts/#generated-values

- [x] Fix problems with cache - @m00g3n 
- [x] Finish Code review adjustments - @aerfio, @magicmatatjahu, @pPrecel 
- [x] Fix issue with CI (connection refused) - @magicmatatjahu 
- [x] check if it will be installed with new charts - @m00g3n 
- [x] Has to be tested with Acceptance Criteria in mind - @aerfio 
- [x] Updating resources - @aerfio  / @pPrecel

**Comment by michal-hudy** [comment]
@magicmatatjahu suggested:
> Stretch:
Rename functionContentType field from CR to contentType and function field from CR to source

**Comment by m00g3n** [comment]
As we agreed offline:
- failed lambda builds should not remove previous lambda runtimes (if existed)
- there will be only one available runtime

**Comment by michal-hudy** [comment]
TODO:
 - Update documentation
 - Integration tests
 - Update CBS ans UI to align with Function CR
