### ISSUE TITLE
Remove event bus docu 

### ISSUE THREAD

**Issue by bszwarc** [kyma-project/kyma#7499]
Starting from 1.11 Event Bus is no longer in use, due to the migration to Knative Eventing Mesh.
Documentation for Event bus should be removed:
**TODO**

- [ ] Move this document to new Eventing docu: 

     * https://kyma-project.io/docs/master/components/event-bus/#details-knative-eventing-mesh-alpha-channel- 
       implementations

- [ ]  Remove Event Bus, move any valid information to new doc set 

- [ ] Deprecate resources for Event Bus on github??
