### ISSUE TITLE
Add tests in Application Broker domain with API Packages On

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#7660]
**Description**

This epic gathers all work related to test refactor in  Application Broker domain after switching to API Packages:

- [ ] Change the [E2E application broker test](https://github.com/kyma-project/kyma/blob/master/tests/service-catalog/test/servicecatalog_test.go#L194) With API Package because we are not able to create the Application via CR. It is only possible to do that with compass. 

- [ ] Change the [E2E test for service binding usage prefixing](https://github.com/kyma-project/kyma/blob/master/tests/service-catalog/test/binding_usage_test.go). Currently, they are based on Application Broker which is totally unrelated to tests example and also cause a problem with API Package because we are not able to create the Application via CR. It is only possible to do that with compass. 

- [ ] Refactor upgrade tests to cover the App Broker flow after switching to API Packages (can be done in 1.13 release as in 1.12 those test will be disabled because of the manual upgrade scenario)

**Comment by PK85** [comment]
We have complicated situation now, with two solutions about application APIs enablement and new unified one is approaching us (external AppBroker). That's a reason I'm closing it.
