### ISSUE TITLE
Alternative backup-restore strategy

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#7858]
**Description**

_Motivation_
Using velero as backup/restore tool for the full kyma stack brings quite some challenges. Seeing Kyma as an application running on top of kubernetes, Kyma is a very complex application requiring an intensive resource ordering, exclusion of resources and CRD handling in the restore phase and the result are not really convincing yet. The automated backup job is failing regular resulting in undeterministic problems.
 It turns out that for the kyma stack itself probably a more simple and limited strategy should be used while velero should be still recommended for applications running on top of kyma.

_Approach_
Velero is mainly used for cluster migrations or partial recovery of applications. So create a new cluster with kyma installed and migrate/restore your application on top. Here, we should provide a documentation how to use velero, but a kyma restore itself will not be supported, saving a lot of investment (think of the velero plugins we wrote and the complex resource order definition).

Additionally, we need to survive problems on an existing cluster, so assuring that a restore of the master node etcd will be survived and that disc loss can be survived by storing as less as possible durable data on persistent volumes and having a snapshoting strategy in place.

Saying that we should define a new backup strategy for kyma itself based on recovery on the current cluster plus having a recommendation of velero as application backup strategy on top for being able to restore on other clusters.

To have that new strategy we mainly need to cover these points:
- [x] Assure that a master node etcd restore will result in an functional kyma stack
- [x] Assure that a disk loss for logging and monitoring can be survived accepting data loss but assuring operational continuity
- [ ] ~~Have an automated test which deletes all kyma disks in order to simulate a disaster and let kyma survive it~~
- [x] Have a new document describing a backup/restore procedure for kyma volumes based on https://kubernetes.io/docs/concepts/storage/volume-snapshots/, enabling that feature on the different providers upfront
- [x] Assure that customers have all privileges for the recommended approach
- [x] Remove backup chart from kyma
- [x] Remove backup job
- [x] Have manual backup guide based on velero (without restore)

**Reasons**

The current approach results in s flaky restore procedure with unstable results and a quite complex restore phase. Furthermore, service accounts of the cloud provider are required in the backup phase. With that the approach is hard to be used and usage of velero should be turned into a recommendation for application backup, but for the kyma stack itself a more reliable and simpler solution is required.

**Attachments**

**Comment by a-thaler** [comment]
Old strategy removed, docu for new strategy in place and verified
