### ISSUE TITLE
Find a way to get logs for gardener based clusters in CI/CD flow

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#8783]
**Description**

Kyma has several integration jobs such as:
-  kyma-integration-gardener-gcp
-  kyma-integration-gardener-aws
- kyma-integration-gardener-azure
- kyma-aks-nightly
- kyma-gke-weekly
- pre-master-kyma-gke-integration

to name a few. While there are logging solutions for aks and gke (StackDriver) clusters, there seems to be no solution for Gardener clusters (only logging for the control plane)

**AC**
- Provide a way to get logs of gardener clusters (still accessible after cluster deletion for some time)

**Possible Solution**

Create a prow job artifact containing the logs of all pods as well the k8s resources.

The following command can be used to dump these information (for each namespace).

```
$ kubectl cluster-info dump --namespace "${namespace}" --output-directory "${output_directory}"
```

Open question: should the artifacts be available for everyone or only kyma developers? Cluster dump could contain secrets.

**Reasons**

- Gardener based integration jobs are hard to debug when they fail. The reason is that there is no known way for me how to get the logs of the pods.

**Attachments**

**Subtasks:**
- [x] Create Installation overrides for fluent bit configuration
- [x] Provision kyma-cli to pick up the fluent bit configuration via installation overrides.
- [x] Inject StackDriver's Service Principle via Secret.
- [x] Modify Existing Prow jobs to use the above logging mechanism.
- [x] Validate presence of Gardener Logs in Stackdriver
- [ ] Update Documentation for accessing Gardener Logs ( wiki will be updated after PR is merged and changes are effective, otherwise it might be confusing)

**Comment by nachtmaar** [comment]
The current idea is to forward logs using fluent-bit to Stackdriver using the [stackdriver output plugin](https://docs.fluentbit.io/manual/pipeline/outputs/stackdriver).
Here is the summary of the current status:

We tried to use the newly introduced `k8s_container` resource type which brings advanced filtering capabilities on stackdriver side compared to global resource

However we did run into issues:
- the `resource.(namespace_name|pod_name|container_name)` field was set to the first value specified by `local_resource_id`. In most of the cases, this is not the indented namespace_name/pod_name/container_name.
- With the following patch on fluent-bit it works, however we are not unsure whether we just might be using it wrongly:
```diff
diff --git a/plugins/out_stackdriver/stackdriver.c b/plugins/out_stackdriver/stackdriver.c
index 4a9b5003..030bd93a 100644
--- a/plugins/out_stackdriver/stackdriver.c
+++ b/plugins/out_stackdriver/stackdriver.c
@@ -413,6 +413,7 @@ static int process_local_resource_id(const void *data, size_t bytes,
             }
 
             /* iterate through the list */
+           unsigned int i=0;
             mk_list_foreach_safe(head, tmp, list) {
                 ptr = mk_list_entry(head, struct local_resource_id_list, _head);
                 if (first) {
@@ -426,15 +427,16 @@ static int process_local_resource_id(const void *data, size_t bytes,
                 }
 
                 /* Follow the order of fields in local_resource_id */
-                if (!ctx->namespace_name) {
+                if (i==0) {
                     ctx->namespace_name = flb_sds_create(ptr->val);
-                }
-                else if (!ctx->pod_name) {
+                } 
+               else if (i==1) {
                     ctx->pod_name = flb_sds_create(ptr->val);
-                }
-                else if (!ctx->container_name) {
+                } 
+               else if (i==2) {
                     ctx->container_name = flb_sds_create(ptr->val);
-                }
+                } 
+               i++;
             }
 
             if (!ctx->namespace_name || !ctx->pod_name || !ctx->container_name) {
```
- There is a [promising PR](https://github.com/fluent/fluent-bit/pull/2346) for the stackdriver plugin which will automatically set `local_resource_id` based on the tag name. If it is merged, there is not need for lua anymore.

However, since there are problems with using resource `gke_container` atm, we will implement the support for `global` resource until then and leave it as a future improvement.
