### ISSUE TITLE
Namespace isolation and simplification of application connectivity

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#9127]
**Description**
The connector service and application registry API creates cluster-wide objects (Application CR). The Application Connector and Application Registry API should contain a namespace in the basepath and should create namespaced custom resources in Kubernetes. The scope of this task includes also substantial refactoring of the components including consolidation and reduction of abstractions used in the entire connectivity area. As a result, a simpler flow can be achieved.
The requirements:
- API should be backward compatible (adding a namespace to the basepath doesn't break the compatibility)
- Registered events are immediately available in the namespace (no additional step required to create service instance)
- Registered APIs credentials can be bound to any workflow directly or through Application Gateway URL (no additional step required to create service instance)

**Acceptance criteria**
- [ ] service catalog is not required to use the application in the Kyma runtime
- [ ] application mapping created in the namespace enabled event triggers in that namespace without creating service instances.
- [ ] you can create event triggers without registering event spec (free text input in the UI)
- [ ] application mapping is enough to configure access to the application in the namespace
- [ ] there is a simple, declarative way and to bind workload with application API (if you create binding it should contain only predictable names for references, e.g. application name not generated secret name). 

**Reasons**
With global resources, it is not possible to properly separate different developers/teams. Namespaced API and custom resources will solve the problem. The development experience can be improved by reducing the number of operations required to pair the application with the namespace in the Kyma runtime.
Currently, you need several steps to call application API from your workload and enable event triggers:
- create application
- create application mapping
- connect application, 
- register apis and events
- wait for service classes to be created in the mapped namespace, find the proper service class names (not predictable)
- create service instances for service classes found in previous step
- create service bindings
- create service binding usage for your workload 
- create a trigger for your workload

The number of steps is overwhelming and users cannot create all kubernetes resources in front (as a part of their application deployment). It should be possible to work in the Kubernetes way - declarative approach.

**Comment by janmedrek** [comment]
Application Gateway utilizing Kyma Bindings: https://github.com/kyma-project/kyma/issues/10325

**Comment by janmedrek** [comment]
Closing as a "duplicate" of: https://github.com/kyma-project/kyma/issues/11044
