### ISSUE TITLE
Adapt components to 'allowPrivilegedContainers: false' policy

### ISSUE THREAD

**Issue by rafalpotempa** [kyma-project/kyma#9531]
**Description**

Kyma Runtime is going to be provisioned with [PodSecuritPolicy Kubernetes Admission Plugin](https://kubernetes.io/docs/concepts/policy/pod-security-policy/) enabled, without allowance of PrivilegedContainers (`allowPrivilegedContainers: false`) ([source](https://github.com/kyma-project/control-plane/issues/120)) so they cannot run in `root` mode.

**Implications**

We need to adjust nearly all components to be able to be created correctly during installation in order to setup a SKR with `allowPrivilegedContainers: false`.
We need to run manual tests of all components on that SKR.

All area that during investigation proven to encounter `missing 'runAsRoot'` error has to be adjusted in one of following ways:
- `Containers` belonging to component affected by this change now don't need to `RunAsRoot`
- `ClusterRole` / `Role` connected with component now uses custom `PodSecurityPolicy`
- existing `PodSecuirtyPolicies` related to component now allow `Pods` to `RunAsRoot`
- `ClusterRole` / `Role` connected with component  now uses `kyma.privileged` `PodSecurityPolicy` (not implemented)
- `deployment.container.securityContext.runAsUser` may be used to force the user used inside the pod

**Progress**

- [x] api-gateway https://github.com/kyma-project/kyma/issues/9535
- [x] apiserver-proxy https://github.com/kyma-project/kyma/issues/9536
- [x] application-connector https://github.com/kyma-project/kyma/issues/9537
- [x] cluster-essentials https://github.com/kyma-project/kyma/issues/9538
- [x] compass-runtime-agent https://github.com/kyma-project/kyma/issues/9539
- [ ] console https://github.com/kyma-project/kyma/issues/9715
- [ ] core https://github.com/kyma-project/kyma/issues/9540
- [x] dex https://github.com/kyma-project/kyma/issues/9541
- [ ] event-sources https://github.com/kyma-project/kyma/issues/9542
- [x] helm-broker https://github.com/kyma-project/kyma/issues/9543
- [x] iam https://github.com/kyma-project/kyma/issues/9544
- [x] istio https://github.com/kyma-project/kyma/issues/9545
- [x] knative-eventing https://github.com/kyma-project/kyma/issues/9546
- [ ] knative-provisioner-natss https://github.com/kyma-project/kyma/issues/9547
- [x] knative-serving https://github.com/kyma-project/kyma/issues/9548
- [x] kyma-installer https://github.com/kyma-project/kyma/issues/9549
- [x] ory https://github.com/kyma-project/kyma/issues/9550
- [x] permission-controller https://github.com/kyma-project/kyma/issues/9551
- [x] rafter https://github.com/kyma-project/kyma/issues/9552
- [x] service-catalog https://github.com/kyma-project/kyma/issues/9553
- [ ] service-catalog-addons https://github.com/kyma-project/kyma/issues/9554

**Additional info**

During investigation I used a patching script that allows patching components in parallel to installation process with privileges to `RunAsRoot` so `cluster-essentials` and `istio` are able to setup correctly allowing further investigation.

Complete table of investigated components with some of the roles and the script can be found in **Useful stuff** section.

**Useful stuff**

https://github.com/rafalpotempa/patch-kyma-policies

URLs:
- StackOverflow question with exhaustive, general answer:
  - [Is there a way to specify a k8s PodSecuirtyPolicy with container scope?
](https://stackoverflow.com/questions/64499423/is-there-a-way-to-specify-a-k8s-podsecuirtypolicy-with-container-scope)
- About:
  - [k8s/pod-security-policy](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#what-is-a-pod-security-policy)
  - [k8s/enabling-pod-security-policy](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#enabling-pod-security-policies)
  - [k8s/psp/users-and-groups](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#users-and-groups)
    - [dockerfile/user](https://docs.docker.com/engine/reference/builder/#user)
    - [docker/best-practices/user](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user)
  - [k8s/pod-security-standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/#policies)
- API:
  - [gardener/api/ShootSpec.Kubernetes.allowPrivilegedContainers](https://gardener.cloud/documentation/references/core/#core.gardener.cloud/v1beta1.Kubernetes)

**Other related stuff**
- Slack channel: #kyma-privileged-containers
- parent issue: https://github.com/kyma-project/control-plane/issues/120
- parent PR: https://github.com/kyma-project/control-plane/pull/109

> Feel free to update the content or AC if you manage to resolve your components.
