### ISSUE TITLE
Evaluation profile

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#9673]
**Description**

Provide a way to install Kyma with the evaluation profile, which contains the features but has low resource requirements (CPU & memory). The profile should work with different target platforms (GKE, AKS, Gardener, minikube, k3s or kind).
To achieve low resource consumption some trade-offs are required (e.g. short retention period of logs and metrics). Take istio [demo profile](https://istio.io/latest/docs/setup/additional-setup/config-profiles) as an example.

The profile is specified in the installation CR in the spec:
```
profile: evaluation|production
```
For kyma CLI you can select profile with the flag for install command:
```
kyma install --profile evaluation
```
We can define profile also for the component (future)

Installer can read the profile value and merge overrides with the profile-xxxx.yaml that exists in the component chart root folder (the location can be changed to installation folder if keeping the file in the chart is not recommended - @Tomasz-Smelcerz-SAP to verify)

The profile should address the request CPU, request memory, and autoscaling. 

Subtasks:
- [x] low resource settings for istio (demo with some disabled modules that are installed with monitoring and tracing) #9759 
- [x] low resource settings for ory #9757 
- [x] low resource settings for monitoring (limited metrics retention) https://github.com/kyma-project/kyma/issues/9689
- [x] evaluation profile for serverless - #9738 
- [x] evaluation profile for rafter - #9860
- [x] evaluation profile for console - #9898
- [x] evaluation profile for Application Connector #9930
- [x] evaluation profile is described in the documentation with all the limitations
- [x] provisioned should handle profile parameter https://github.com/kyma-project/control-plane/issues/322
- [x] kyma installer takes profile from installation CR
- [x] Support in CLI https://github.com/kyma-project/cli/issues/640  
- [x] Pipeline installing evaluation profile is green

Stretched:
- [ ] separate resource profile from target platform - #9442
- [ ] cleanup deprecated installation CR files - #8130 

**Reasons**

People want to try Kyma features on different platforms and do not want to pay 300$ per month for hello world examples. The default production profile is too big (expensive). The local profile is bound to minikube only and doesn't contain monitoring and tracing.

**Comment by kazydek** [comment]
I guess we would also need to document these profiles, similarly to how we did it for the production profiles (see examples for [Service Mesh](https://kyma-project.io/docs/components/service-mesh/#configuration-service-mesh-production-profile-production-profile) or [Logging](https://kyma-project.io/docs/components/logging/#configuration-logging-production-profile)). You can sync with your TWs for help :)

**Comment by pbochynski** [comment]
The evaluation profile is completed but our integration tests were not able to prove it works (or not). Therefore a new set of tests (#10050) was required to verify the story. New tests show that the evaluation profile is equally stable as the production profile, but unfortunately, both are green only for 80% of executions. Still, some instabilities are visible on Azure infrastructure:
- https://github.com/kyma-project/kyma/issues/10428 
- https://github.com/kyma-project/kyma/issues/10426
