### ISSUE TITLE
Enable providing multiple services with paths in apirules.

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/kyma#9936]
**Description**

We should have the possibility to have a single hostname and multiple paths mapped to various k8s services.
Example:

```yml
apiVersion: networking.k8s.io/v1
kind: APIRule
metadata:
  name: coolapp-ingress-wildcard-host
spec:
  rules:
  - host: "coolapp.bar.com"
    http:
      paths:
      - pathType: Prefix
        path: "/api"
        backend:
          service:
            name: customApiService
            port:
              number: 80
      - pathType: Prefix
        path: "/login"
        backend:
          service:
            name: loginService
            port:
              number: 80
      - pathType: Prefix
        path: "/.*"
        backend:
          service:
            name: staticWebsiteService
            port:
              number: 80
```

**Acceptance criteria**

- [x] [POC] expose multiple svc under same virtual host](https://github.com/kyma-project/kyma/issues/14421)
- [x] [api-gateway implementation](https://github.com/kyma-incubator/api-gateway/issues/140)
- [x] [documentation](https://github.com/kyma-project/kyma/issues/14882)
- [x] [tutorial explaining configuration scenarios](https://github.com/kyma-project/kyma/issues/14887)
- [x] [Kyma Dashboard reflecting changes](https://github.com/kyma-project/busola/issues/1767)
- [x] release notes
- [x] [automated test](https://github.com/kyma-project/kyma/issues/14890)

**Reasons**

For Single Page Applications, this will be a very simple way to consume services, without worrying about CORS overhead and also about how to pass the API endpoints as configurations to the SPA.
This is also a good practice that is used by other vendors like Firebase, and Vercel to expose and consume serverless functions to the SPA

**Comment by gabel** [comment]
Having a similar requirement but for multiple namespaces. Discussion in Slack https://kyma-community.slack.com/archives/CBLBESMST/p1612770790008100

```
Namespace foo
api.example.com/foo -> service foo

Namespace bar
api.example.com/bar -> service bar
```

The same domain should be possible to be used in multiple namespaces with different paths to different services. This works for Istio Virtual Services using https://istio.io/latest/docs/reference/config/analysis/ist0109/.

**Comment by gabel** [comment]
Any chance this topic will be picked up?

**Comment by ThuF** [comment]
Are there any updates on this issues?

The feature seems quite relevant and multiple scenarios are depending on it. For example the Eclipse Dirigible Web IDE [Debugger](https://www.dirigible.io/help/development/ide/views/debugger/) is not working on Kyma due to CORS issues.

**Comment by dapus123** [comment]
The apirule ability to have a failover service would be a good scenario in this particular issue, but it may be slightly different issue as well.
In our setup, we have apirule pointing to a single cache service, but what if cache service is down, I would go directly to service, in case we could configure apirule for that.
Thanks,
Daniel

**Comment by strekm** [comment]
@gabel we will handle support for svc from other namespaces in separate ticket. thanks for your input!
@dapus123 please open separate feature request for you request. thanks

**Comment by luizcarlospedrosogomes** [comment]
> 

Is this available in the latest version of kyma?
